### ISSUE TITLE
Make stacktraces for ZStream be actually useful

### ISSUE THREAD

**Issue by iravid** [zio/zio#1014]
Right now, they look something like this:
```
Fiber:1707 was supposed to continue to:
  a future continuation at zio.ZManaged.fork(ZManaged.scala:327)
  a future continuation at zio.ZManaged.fork(ZManaged.scala:327)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:213)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:215)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:220)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:220)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:220)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:220)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:220)
  a future continuation at zio.stream.ZStream.run(ZStream.scala:674)
```

**Comment by adamgfraser** [comment]
I think this has been addressed by the new approach to execution tracing in ZIO 2 where traces for all these internal operators would not be shown.
