### ISSUE TITLE
Unable to compile some subprojects due to dotty version of dependencies not being available on maven

### ISSUE THREAD

**Issue by softinio** [zio/zio#1077]
Unable to compile some subprojects due to dotty version of dependencies not being available on maven:

- streamsJVM
- testkitJVM
- All projects using scalajs

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalacheck#scalacheck_0.16;1.14.0: not found
[error] unresolved dependency: com.github.ghik#silencer-lib_0.16;1.4.1: not found
[error] unresolved dependency: org.typelevel#kind-projector_0.16;0.10.3: not found
[error] unresolved dependency: com.github.ghik#silencer-plugin_0.16;1.4.1: not found
[error]      at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error]      at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]      at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]      at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]      at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]      at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]      at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]      at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]      at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]      at xsbt.boot.Using$.withResource(Using.scala:10)
[error]      at xsbt.boot.Using$.apply(Using.scala:9)
[error]      at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]      at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]      at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]      at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]      at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]      at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]      at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]      at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]      at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]      at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]      at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]      at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error]      at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error]      at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]      at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error]      at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]      at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error]      at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error]      at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]      at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error]      at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error]      at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]      at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]      at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]      at sbt.Execute.work(Execute.scala:278)
[error]      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]      at java.lang.Thread.run(Thread.java:745)
[error] (streamsJVM / update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scalacheck#scalacheck_0.16;1.14.0: not found
[error] unresolved dependency: com.github.ghik#silencer-lib_0.16;1.4.1: not found
[error] unresolved dependency: org.typelevel#kind-projector_0.16;0.10.3: not found
[error] unresolved dependency: com.github.ghik#silencer-plugin_0.16;1.4.1: not found
[error] Total time: 3 s, completed Jun 23, 2019 9:08:32 PM
```

**Comment by smarter** [comment]
> [error] unresolved dependency: com.github.ghik#silencer-lib_0.16;1.4.1: not found

Since silencer should not affect the compiler output, you should be able to just remove it from the dependencies when compiling with dotty.

> [error] unresolved dependency: org.typelevel#kind-projector_0.16;0.10.3: not found

kind-projector is not needed with Dotty. To write type lambdas that work in both Scala 2 and 3, either use the type projection syntax or use kind-projector on Scala 2 side and `-Ykind-projector` when compiling with Dotty to be able to use `*` as a placeholder (requires a recent version of kind-projector: https://github.com/typelevel/kind-projector/pull/91)
