### ISSUE TITLE
Flaky test in StacktraceSpec

### ISSUE THREAD

**Issue by ioleo** [zio/zio#1186]
In #1185 I had one test fail [see report](https://circleci.com/gh/zio/zio/7022).
Upon retriggering the tests (for the same codebase) it passed [see report](https://circleci.com/gh/zio/zio/7061). 

**Full stack trace below** just in case CircleCI report is no longer available.
```
An unchecked error was produced.
java.lang.Exception
	at zio.StacktracesSpec$singleEffectTotalWithForCompFixture$.$anonfun$asyncDbCall$3(StacktracesSpec.scala:472)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:492)
	at zio.Runtime.unsafeRunAsync(Runtime.scala:93)
	at zio.Runtime.unsafeRunAsync$(Runtime.scala:79)
	at zio.BaseCrossPlatformSpec.unsafeRunAsync(BaseCrossPlatformSpec.scala:19)
	at zio.Runtime.unsafeRunSync(Runtime.scala:68)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:65)
	at zio.BaseCrossPlatformSpec.unsafeRunSync(BaseCrossPlatformSpec.scala:19)
	at zio.StacktracesSpec$CauseMust.causeMust(StacktracesSpec.scala:84)
	at zio.StacktracesSpec.singleSuspendWithForComp(StacktracesSpec.scala:463)
	at zio.StacktracesSpec.$anonfun$new$20(StacktracesSpec.scala:47)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:17)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$result$1(Execution.scala:340)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$3(Execution.scala:358)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$2(Execution.scala:358)
	at zio.TestRuntime$$anon$1.result$lzycompute$1(TestRuntime.scala:25)
	at zio.TestRuntime$$anon$1.result$1(TestRuntime.scala:25)
	at zio.TestRuntime$$anon$1.$anonfun$around$3(TestRuntime.scala:27)
	at org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:21)
	at org.specs2.matcher.Expectable.value(Expectable.scala:21)
	at org.specs2.matcher.TerminationMatcher.$anonfun$apply$1(TerminationMatchers.scala:33)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kaishh** [comment]
@ioleo 
Seems like the test that this trace belongs to passed: 
```
+ single effectTotal for-comprehension
```

it just prints the traces into stdout, they're not actually thrown

**Comment by ioleo** [comment]
@kaishh I might have misread the stack trace (I have yet to learn where & what ZIO reports), but the build did fail, any idea why? :thinking:

**Comment by kaishh** [comment]
The only line with failure is the last `.Exited with code 1`, there are no `[error]` lines and no failed specs, so that's a mystery to me too...

**Comment by ioleo** [comment]
@kaishh Seems like you're right, failed tests should output
```
[error] Failed: Total N, Failed X, Errors Y, Passed Z
[error] Failed tests:
(list of tests)
```

Since you've created a seperate issue for StacktracesSpec confusing output, I guess this one can be closed - it's probably on CircleCI end / nothing we can do about it.
