### ISSUE TITLE
Flaky queue test

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1216]
```
[info]     make a bounded queue, offer 4 values, `takeUpTo` with max = 2, and then `takeUpTo` again with max = 2;
[info]      the first result must contain the first 2 values and the second one must
[error] java.lang.Exception: TIMEOUT: 60 seconds
[error] 	at zio.BaseCrossPlatformSpec$$anon$1.run(BaseCrossPlatformSpec.scala:66)
[error] 	at java.util.TimerThread.mainLoop(Timer.java:555)
[error] 	at java.util.TimerThread.run(Timer.java:505)
[error] Error: Total 620, Failed 0, Errors 1, Passed 619
```

Might be unrelated to queue, actually.

**Comment by ghostdogpr** [comment]
Migrating the tests to ZIO Test may have revealed the actual error: https://circleci.com/gh/zio/zio/17876

@jdegoes looks like something wrong with `interruptChildren`. Since it will go away with #1161, it might not be a big deal. I could change the tests to interrupt the fork fibers explicitly in the meantime.

```
- offers are suspended by back pressure
[info]     Fiber failed.
[info]     An unchecked error was produced.
[info]     java.lang.NullPointerException
[info]     	at zio.Fiber$.$anonfun$interruptAll$2(Fiber.scala:296)
[info]     	at zio.ZIO$ZipLeftFn.apply(ZIO.scala:2490)
[info]     	at zio.ZIO$ZipLeftFn.apply(ZIO.scala:2488)
[info]     	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:270)
[info]     	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:602)
[info]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]     	at java.lang.Thread.run(Thread.java:748)
[info]     
[info]     Fiber:12547 was supposed to continue to:
[info]       a future continuation at zio.ZIO.ensuring(ZIO.scala:285)
[info]       a future continuation at zio.ZIO.run(ZIO.scala:1007)
[info]       a future continuation at zio.ZIO.bracket_(ZIO.scala:131)
[info]       a future continuation at zio.ZIO.run(ZIO.scala:1007)
[info]       a future continuation at zio.ZIO.bracket_(ZIO.scala:131)
[info]       a future continuation at zio.ZIO.run(ZIO.scala:1007)
[info]       a future continuation at zio.ZManaged.use(ZManaged.scala:634)
[info]       a future continuation at zio.test.TestExecutor$.managed(TestExecutor.scala:25)
[info]       a future continuation at zio.test.Spec.foreachExec(Spec.scala:95)
[info]       a future continuation at zio.ZIOFunctions.foreachParN(ZIO.scala:1896)
[info]       a future continuation at zio.ZIO.forever(ZIO.scala:406)
[info]     
[info]     Fiber:12547 execution trace:
[info]       at zio.Fiber$.interruptAll(Fiber.scala:296)
[info]       at zio.ZIOFunctions.handleChildrenWith(ZIO.scala:2030)
[info]       at zio.internal.FiberContext.getFibers(FiberContext.scala:560)
[info]       at zio.ZIOFunctions.children(ZIO.scala:1595)
[info]       at zio.ZIO.ensuring(ZIO.scala:283)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:146)
[info]       at zio.ZQueueSpec$$anonfun$$lessinit$greater$1.new(ZQueueSpec.scala:55)
[info]       at zio.Ref$.get$extension(Ref.scala:39)
[info]       at zio.ZQueueSpec$$anonfun$$lessinit$greater$1.new(ZQueueSpec.scala:54)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:155)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:146)
[info]       at zio.ZIOFunctions.bracketExit(ZIO.scala:1563)
[info]       at zio.internal.FiberContext.evaluateNow(FiberContext.scala:473)
[info]       at zio.ZIO.bracket_(ZIO.scala:131)
[info]       at zio.ZIO.run(ZIO.scala:1007)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:146)
[info]       at zio.ZIO.repeatOrElse(ZIO.scala:930)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:946)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:945)
[info]       at zio.ZIO.as(ZIO.scala:102)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:155)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:146)
[info]       at zio.ZIO.ensuring(ZIO.scala:285)
[info]       at zio.ZIO.onInterrupt(ZIO.scala:568)
[info]       at zio.ZIO.ensuring(ZIO.scala:283)
[info]       at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:146)
[info]       at zio.ZIO$._IdentityFn(ZIO.scala:2392)
[info]       at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1701)
[info]       at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1697)
[info]       at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1697)
[info]       at zio.clock.Clock$Live$$anon$1.sleep(Clock.scala:48)
[info]       at zio.clock.package$.sleep(clock.scala:50)
[info]       at zio.ZQueueSpecUtil$.waitForSize(ZQueueSpec.scala:673)
[info]       at zio.Queue$$anon$1.size(Queue.scala:263)
[info]       at zio.Queue$$anon$1.checkShutdownState(Queue.scala:194)
[info]       at zio.Promise$.poll(Promise.scala:149)
[info]       at zio.Promise$.poll$extension(Promise.scala:149)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:951)
[info]       at zio.ZIO.bracket_(ZIO.scala:131)
[info]       at zio.internal.FiberContext.evaluateNow(FiberContext.scala:469)
[info]       at zio.ZQueueSpec$$anonfun$$lessinit$greater$1.new(ZQueueSpec.scala:54)
[info]       at zio.ZQueueSpec$$anonfun$$lessinit$greater$1.new(ZQueueSpec.scala:52)
[info]       at zio.Ref$.make(Ref.scala:142)
[info]       at zio.ZQueueSpec$$anonfun$$lessinit$greater$1.new(ZQueueSpec.scala:51)
[info]       at zio.ZIO.repeatOrElse(ZIO.scala:930)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:946)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZSchedule$.unfoldM(ZSchedule.scala:746)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:945)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:244)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:252)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:252)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:248)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:244)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:236)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:235)
[info]       at zio.Queue$$anon$1.checkShutdownState(Queue.scala:194)
[info]       at zio.Promise$.poll(Promise.scala:149)
[info]       at zio.Promise$.poll$extension(Promise.scala:149)
[info]       at zio.UIO$.effectSuspendTotal(UIO.scala:147)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:947)
[info]       at <unknown>.<unknown>(ZIO.scala:0)
[info]       at zio.test.mock.MockClock$Mock.sleep(MockClock.scala:64)
[info]       at zio.Promise$.complete$extension(Promise.scala:93)
[info]       at zio.test.mock.MockClock$Mock.sleep(MockClock.scala:58)
[info]       at zio.Ref$.modify$extension(Ref.scala:47)
[info]       at zio.test.mock.MockClock$Mock.sleep(MockClock.scala:57)
[info]       at zio.Promise$.make(Promise.scala:239)
[info]       at zio.clock.package$.sleep(clock.scala:50)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:946)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZSchedule$.unfoldM(ZSchedule.scala:746)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:945)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:244)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:252)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:252)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:248)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:244)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:236)
[info]       at zio.Queue$$anon$1.offerAll(Queue.scala:235)
[info]       at zio.Queue$$anon$1.checkShutdownState(Queue.scala:194)
[info]       at zio.Promise$.poll(Promise.scala:149)
[info]       at zio.Promise$.poll$extension(Promise.scala:149)
[info]       at zio.UIO$.effectSuspendTotal(UIO.scala:147)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:947)
[info]       at <unknown>.<unknown>(ZIO.scala:0)
[info]       at zio.test.mock.MockClock$Mock.sleep(MockClock.scala:64)
[info]       at zio.Promise$.complete$extension(Promise.scala:93)
[info]       at zio.test.mock.MockClock$Mock.sleep(MockClock.scala:58)
[info]       at zio.Ref$.modify$extension(Ref.scala:47)
[info]       at zio.test.mock.MockClock$Mock.sleep(MockClock.scala:57)
[info]       at zio.Promise$.make(Promise.scala:239)
[info]       at zio.clock.package$.sleep(clock.scala:50)
[info]       at zio.ZIO.repeatOrElseEither(ZIO.scala:946)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]       at zio.ZSchedule.check(ZSchedule.scala:211)
[info]     
[info]     Fiber:12547 was spawned by:
[info]     
[info]     Fiber:12539 was supposed to continue to:
[info]       a future continuation at zio.ZIO.zipWith(ZIO.scala:1362)
[info]       a future continuation at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       a future continuation at zio.ZIOFunctions.foreachParN(ZIO.scala:1898)
[info]       a future continuation at zio.ZIO.run(ZIO.scala:1007)
[info]       a future continuation at zio.ZIOFunctions.foreachParN(ZIO.scala:1891)
[info]       a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:873)
[info]       a future continuation at zio.test.Spec.foldM(Spec.scala:70)
[info]       a future continuation at zio.ZIO.summarized(ZIO.scala:1115)
[info]       a future continuation at zio.test.TestRunner.run(TestRunner.scala:41)
[info]       a future continuation at zio.ZIO.run(ZIO.scala:1007)
[info]     
[info]     Fiber:12539 execution trace:
[info]       at zio.ZIO.zipWith(ZIO.scala:1362)
[info]       at zio.ZIOFunctions.foreachParN(ZIO.scala:1895)
[info]       at zio.ZIOFunctions.foreachParN(ZIO.scala:1894)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
[info]       at zio.ZIOFunctions.foreach(ZIO.scala:1832)
```

**Comment by jdegoes** [comment]
@ghostdogpr Wow, that's phenomenal. Know right where to look.

I like your "temp" approach now and I will write up the other issue.
