### ISSUE TITLE
Streams tests getting stuck

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1486]
Example builds:
https://circleci.com/gh/zio/zio/19133
https://circleci.com/gh/zio/zio/19128
https://circleci.com/gh/zio/zio/19205

It seems to happen after #1477 or #1478 ?

Not sure what's happening since there's no detail, just a timeout. I wasn't able to reproduce locally.

cc @vasilmkd

**Comment by ghostdogpr** [comment]
May be unrelated but after several local runs, I got this:
```
[info]   Stream.flatMapPar/flattenPar/mergeAll
[info]     + guarantee ordering
[error] zio.FiberFailure: Fiber failed.
[error] An unchecked error was produced.
[error] java.lang.NullPointerException
[error] 	at zio.stream.ZStream.$anonfun$flatMap$6(ZStream.scala:823)
[error] 	at zio.internal.FiberContext.nextInstr(FiberContext.scala:709)
[error] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:324)
[error] 	at zio.internal.FiberContext.$anonfun$fork$1(FiberContext.scala:595)
[error] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] 
[error] Fiber:12008 was supposed to continue to:
[error]   a future continuation at zio.stream.ZStream.flatMap(ZStream.scala:839)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1030)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1031)
[error]   a future continuation at zio.ZIO.forever(ZIO.scala:428)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1033)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1033)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:238)
[error]   a future continuation at zio.ZManaged.use_(ZManaged.scala:647)
[error]   a future continuation at zio.ZIO.run(ZIO.scala:1033)
[error]   a future continuation at zio.ZManaged.use(ZManaged.scala:640)
[error]   a future continuation at zio.stream.ZStream.flatMapPar(ZStream.scala:887)
[error] 
[error] Fiber:12008 execution trace:
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:823)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:832)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2168)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2168)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2167)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2166)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2165)
[error]   at zio.ZManaged$.make(ZManaged.scala:1008)
[error]   at zio.Promise$.complete$extension(Promise.scala:93)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2160)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.ZIO.flatten(ZIO.scala:376)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:839)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:827)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:826)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:826)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:825)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:238)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2158)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2158)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:237)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.ZIO.as(ZIO.scala:102)
[error]   at zio.Ref$.update$extension(Ref.scala:103)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:235)
[error]   at zio.ZManaged.map(ZManaged.scala:380)
[error]   at zio.ZManaged.map(ZManaged.scala:380)
[error]   at zio.ZManaged$.finalizerRef(ZManaged.scala:851)
[error]   at zio.ZManaged$.finalizerRef(ZManaged.scala:851)
[error]   at zio.Ref$.make(Ref.scala:142)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:234)
[error]   at zio.Ref$.make(Ref.scala:142)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:233)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.ZIO.as(ZIO.scala:102)
[error]   at zio.Ref$.update$extension(Ref.scala:103)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:231)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:824)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:227)
[error]   at zio.Ref$.make(Ref.scala:142)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:823)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2168)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2168)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2167)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2166)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2165)
[error]   at zio.Semaphore.withPermitsManaged(Semaphore.scala:120)
[error]   at zio.Ref$.modify$extension(Ref.scala:47)
[error]   at zio.Semaphore.prepare(Semaphore.scala:142)
[error]   at zio.Promise$.make(Promise.scala:239)
[error]   at zio.stream.ZStream$.managed(ZStream.scala:2160)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:839)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:838)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:838)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:832)
[error]   at zio.ZIO.flatten(ZIO.scala:376)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:839)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.Ref$.set$extension(Ref.scala:90)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:838)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:838)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.stream.ZStream.flatMap(ZStream.scala:832)
[error]   at zio.ZIO.flatten(ZIO.scala:376)
[error]   at zio.Ref$.get$extension(Ref.scala:39)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:237)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.ZIO.as(ZIO.scala:102)
[error]   at zio.Ref$.update$extension(Ref.scala:103)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:235)
[error]   at zio.ZManaged.map(ZManaged.scala:380)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:234)
[error] 
[error] Fiber:12008 was spawned by:
[error] 
[error] Fiber:12004 was supposed to continue to:
[error]   a future continuation at zio.ZIO.raceWith(ZIO.scala:875)
[error]   a future continuation at zio.ZIO.raceWith(ZIO.scala:881)
[error]   a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:899)
[error]   a future continuation at zio.ZIO.race(ZIO.scala:812)
[error] 
[error] Fiber:12004 execution trace:
[error]   at zio.ZIO.raceWith(ZIO.scala:871)
[error]   at zio.Ref$.make(Ref.scala:142)
[error]   at zio.ZIO.raceWith(ZIO.scala:870)
[error]   at zio.Promise$.make(Promise.scala:239)
[error] 
[error] Fiber:12004 was spawned by:
[error] 
[error] Fiber:12002 was supposed to continue to:
[error]   a future continuation at zio.stream.ZStream.flatMapPar(ZStream.scala:893)
[error]   a future continuation at zio.ZIO.as(ZIO.scala:102)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1030)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1031)
[error]   a future continuation at zio.ZIO.forever(ZIO.scala:428)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1033)
[error]   a future continuation at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1033)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:238)
[error]   a future continuation at zio.ZIO.sandbox(ZIO.scala:1060)
[error]   a future continuation at zio.ZManaged.foldM(ZManaged.scala:318)
[error] 
[error] Fiber:12002 execution trace:
[error]   at zio.stream.ZStream.flatMapPar(ZStream.scala:879)
[error]   at zio.stream.ZStream.flatMapPar(ZStream.scala:879)
[error]   at zio.Promise$.make(Promise.scala:239)
[error]   at zio.stream.ZStream.foreachWhileManaged(ZStream.scala:1030)
[error]   at zio.ZIO.flatten(ZIO.scala:376)
[error]   at zio.stream.StreamEffect$$anonfun$$lessinit$greater$1.apply(StreamEffect.scala:25)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:237)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.ZIO.as(ZIO.scala:102)
[error] 
[error] Fiber:12002 was spawned by:
[error] 
[error] Fiber:12000 was supposed to continue to:
[error]   a future continuation at zio.ZManaged.fork(ZManaged.scala:347)
[error]   a future continuation at zio.ZManaged.fork(ZManaged.scala:347)
[error]   a future continuation at zio.ZManaged.map(ZManaged.scala:380)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:235)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:237)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:238)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:238)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:238)
[error]   a future continuation at zio.ZManaged.flatMap(ZManaged.scala:234)
[error]   a future continuation at zio.stream.ZStream.run(ZStream.scala:1514)
[error] 
[error] Fiber:12000 execution trace:
[error]   at zio.ZManaged.fork(ZManaged.scala:343)
[error]   at zio.Ref$.make(Ref.scala:142)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:234)
[error]   at zio.Promise$.make(Promise.scala:239)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:233)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:156)
[error]   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:147)
[error]   at zio.ZIO.as(ZIO.scala:102)
[error]   at zio.Ref$.update$extension(Ref.scala:103)
[error]   at zio.ZManaged.flatMap(ZManaged.scala:231)
[error] 
[error] Fiber:12000 was spawned by: <empty trace>
```

**Comment by vasilmkd** [comment]
cc @iravid

I'll try to take a look as soon as possible.

**Comment by iravid** [comment]
It reproduced locally. I ran a thread dump on the process and saw that all the arbitraries were hanging; two threads were waiting on `Stream$.<init>, Stream$.<clinit>` and `ZStream$.<init>, ZStream$.<clinit>`.

I changed all `val` definitions on the companion objects of `ZStream` and `Stream` to `def`, and now the timeouts are gone.

Pretty weird! @neko-kai @jdegoes do you have any insight on that?

**Comment by iravid** [comment]
(I did not manage to reproduce the NPE, though, even with `nonFlaky`)

**Comment by vasilmkd** [comment]
For context, #1478 changed `ZStream` from a `trait` with `def process: ZManaged[...]` to `class ZStream(val process: ZManaged[...])`.

**Comment by iravid** [comment]
Oh! It's a circular dependency. in `object ZStream`:
```
  final val never: Stream[Nothing, Nothing] =
    Stream[Nothing, Nothing](ZManaged.succeed(UIO.never))
```

This definition is waiting on the static initializer of `Stream`, while the static initializer of `Stream` is waiting on the static initializer of `ZStream`. 😂

Will submit a fix.

**Comment by vasilmkd** [comment]
Yes, sorry about this.

**Comment by iravid** [comment]
No worries! Pretty subtle.
