### ISSUE TITLE
ZIO Test: Report timeouts in a prettier way

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1599]
In case of timeout from TestAspect, we're displaying this:
```
[info]     Fiber failed.
[info]     An unchecked error was produced.
[info]     java.util.concurrent.TimeoutException: Timeout of Finite(1000000000) exceeded
[info]     	at zio.test.TestAspect$$anon$12.$anonfun$perTest$14(TestAspect.scala:293)
[info]     	at zio.internal.FiberContext.nextInstr(FiberContext.scala:709)
[info]     	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:332)
[info]     	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:601)
[info]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]     	at java.lang.Thread.run(Thread.java:748)
[info]     No ZIO Trace available.
```

Instead, display something like this:
```
[info] Timeout of 60 seconds exceeded
```

**Comment by ghostdogpr** [comment]
I'm working on it
