### ISSUE TITLE
Hanging thread

### ISSUE THREAD

**Issue by KadekM** [zio/zio#1841]
Ignoring discussion about why you shouldn't have code like this, following code rather surprisingly hangs forever.

```scala
import zio.{DefaultRuntime, ZIO}

class Runtime extends DefaultRuntime

object Another {
  val ef = ZIO.effectTotal("got")
  val f = ef.fork.flatMap(_.join)
}

object Other{
  val ef = ZIO.effectTotal("got")
  val f = ef.fork.flatMap(_.join)
  val rt = new Runtime

//  val a0 = rt.unsafeRun(Another.f) // works fine
  val a1 = rt.unsafeRun(f) // hangs
//  val a2 = rt.unsafeRun(ef) // works fine
}

object Test {
  def main(args: Array[String]): Unit = {
    Other
  }
}
```
This is reduced use case to minimum. Real use case was manual (unsafe) acquiring of Reservation in _object_ in the impure side of the world.

**Comment by KadekM** [comment]
Similiar
```
object Other {
  //val ef = ZIO.effect { "got" } // works
  val ef = ZIO.effect { "got" }.on(scala.concurrent.ExecutionContext.global) // doesnt work
  val a0 = runtime.unsafeRun(ef)
}

object MyNotWorkingImperativeApp extends scala.App {
  Other.a0 // hangs forever
}
```

**Comment by jdegoes** [comment]
I wonder if this could be some `synchronized` stuff that Scala inserts. May be necessary to decompile to understand what's going on.

**Comment by fsvehla** [comment]
Defining the lines containing the `unsafeRun` as a `lazy val` solves the issue, so I’m thinking it’s _sometimes_ an issue to refer to some members of the object while it’s initialization `cinit` / `init` is not complete yet.

**Comment by yurikpanic** [comment]
Looks like it is actually synchronization stuff, but not inserted by Scala. It comes from the JVM itself.

Here is the code, which is similar to that in the `zio.Runtime.unsafeRunSync`, which is called by `unsafeRun`. It uses Scala `Future`, not zio's fiber, but the meaning is the same. 

```scala
object X {
  val z = {
    val res = zio.internal.OneShot.make[String]
    val tt = Future {
      res.set("done")
    }
    res.get()
  }
}
```

All the code in the `X.z` goes to the `static {}` initializer section of the `X$` class. Static initializers are run by the JVM at class initialization time. And the JVM holds an initialization lock which is released only after initialization is complete (JLS 12.4.2).

The `Future.apply` parameter is a by-name parameter, which is actually a lambda inside of the `X$`. 

The `Future` starts but immediately blocks trying to obtain the value of a by-name (lambda function) parameter.  Because the `X$` initialization is not complete yet.

And the `X$` initialization never completes, because it's blocked in the `res.get()`. 

And here it is - a deadlock. 

Making the value `lazy`, as mentioned in the comment above, or changing the `object X` to `class X` makes everything to work, because the corresponding code is no longer in the `static {}` section. 

So, this is probably not a "bug", but rather "works as expected". 

But it may affect an "interactive experience". E.g. a simple code like this `rt.unsafeRun(ZIO.collectAllPar(ZIO.effectTotal(1) :: Nil))` hangs a REPL. That's actually a stripped-down example, I came up with while verifying some ideas during porting some Future based production code to ZIO. So this may be a likely use case and either a workaround for it is required or it should be properly documented.

**Comment by fanf** [comment]
I'm having something similar for `RC18`, but somehow it is worse than in `RC16` and makes use of a personnal runtime hard - actually I didn't find a way for now. I tried to adapt my code to use `class` in place of object where possible, and `lazy val` everywhere, but it still deadlock. 

I really need to be able to have a stable reference to `ZioRuntime`, and I really need to be able to have object which uses `ZioRuntime.unsafeRun` (the one with `blocking`). 

```scala
class internalRuntime {
  lazy val platform : _root_.zio.internal.Platform = _root_.zio.internal.Platform.makeDefault()
  lazy val environment = {
    // that platform is just for init zlayer
    val r = Runtime((), platform)
    r.unsafeRun(ZEnv.live.build.memoize.map(ZLayer(_)).use(ZIO.succeed(_)))
  }
  lazy val runtime = Runtime.unsafeFromLayer(environment, platform)
  runtime.unsafeRun(UIO.effectTotal(println("**** case 0: non blocking")))
  unsafeRun(UIO.effectTotal(println("**** case 1: blocking")))

  def blocking[E, A](e: ZIO[Any, E, A]): ZIO[Any, E, A] = {
    ZIO.accessM[_root_.zio.blocking.Blocking](_.get.blocking(e)).provideLayer(environment)
  }
  def unsafeRun[E, A](e: => ZIO[Any, E, A]): Unit = {
    runtime.unsafeRun(blocking(e))
  }

}

object someRoot { // this is the entry point for my runtime
  lazy val zioRuntime = new internalRuntime()
}

object Elsewhere { // somewhere else, a blocking unsafe run is called

  someRoot.zioRuntime.runtime.unsafeRun(UIO.effectTotal(println("**** case 1000: non blocking")))
  someRoot.zioRuntime.unsafeRun(UIO.effectTotal(println("**** case 2000: blocking")))

  def print()= println("ok")
}

object TestRuntime {
  def main(args: Array[String]): Unit = {
    // in internal, it blocks
    someRoot.zioRuntime.runtime.unsafeRun(UIO.effectTotal(println("**** case 100: non blocking")))
    someRoot.zioRuntime.unsafeRun(UIO.effectTotal(println("**** case 200: blocking")))

    // it blocks here, when calling the blocking variant
    Elsewhere.print()
    println("done")

/* console output:
**** case 0: non blocking
**** case 1: blocking
**** case 100: non blocking
**** case 200: blocking
**** case 1000: non blocking
 -- blocks here --
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:328)
	  at zio.internal.OneShot.get(OneShot.scala:79)
	  at zio.Runtime.unsafeRunSync(Runtime.scala:82)
	  at zio.Runtime.unsafeRunSync$(Runtime.scala:77)
	  at zio.Runtime$Managed$$anon$1.unsafeRunSync(Runtime.scala:215)
	  at zio.Runtime.unsafeRun(Runtime.scala:57)
	  at zio.Runtime.unsafeRun$(Runtime.scala:56)
	  at zio.Runtime$Managed$$anon$1.unsafeRun(Runtime.scala:215)
	  at com.normation.internalRuntime.unsafeRun(ZioCommonsTest.scala:96)
	  at com.normation.Elsewhere$.<clinit>(ZioCommonsTest.scala:108)
	  at com.normation.TestRuntime$.main(ZioCommonsTest.scala:120)
	  at com.normation.TestRuntime.main(ZioCommonsTest.scala:-1)

"zio-default-blocking-1-692483103@1960" daemon prio=5 tid=0x20 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.normation.Elsewhere$$$Lambda$418.1976870338.apply$mcV$sp(Unknown Source:-1)
	  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:383)
	  at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:679)
	  at zio.internal.FiberContext$$Lambda$206.1601318205.run(Unknown Source:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:834)
*/
```
Given the threaddump traces, it really looks like @yurikpanic explanation.
 
The previous code was using `val internal = new DefaultRuntime()` (https://github.com/Normation/rudder/blob/6.0/webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala#L306) and was working fine. 
If anybody has an idea, any help would be much appreciated.

**Comment by fanf** [comment]
It is also reproducible by using current `1.0.0-RC18-1+44-24f507c2+20200310-2150-SNAPSHOT` with the `Runtime.default` object: 

```
class internalRuntime {

  lazy val runtime = Runtime.default
  runtime.unsafeRun(UIO.effectTotal(println("**** case 0: non blocking")))
  unsafeRun(UIO.effectTotal(println("**** case 1: blocking")))

  def blocking[E, A](e: ZIO[Any, E, A]): ZIO[Any, E, A] = {
    ZIO.accessM[_root_.zio.blocking.Blocking](_.get.blocking(e)).provideLayer(ZLayer.succeedMany(runtime.environment))
  }
  def unsafeRun[E, A](e: => ZIO[Any, E, A]): Unit = {
    runtime.unsafeRun(ZIO.accessM[_root_.zio.blocking.Blocking](_.get.blocking(e)))
  }

}
... other part identical to previous comment - block at the same point with the same threaddump...
```

**Comment by fanf** [comment]
I tried to minimuze reproduce our working env in `RC16` to get insight about difference, because given explanation about object lock, it should not, and... Actually it does not work in `RC16`. So now, I don't get why it works on our app at all. That may be phase 3 of grief^W bug hunting, or something.

**Comment by fanf** [comment]
Hum. So it seems that by pure happenstance, we only used the `someRoot.zioRuntime.runtime.unsafeRun(...)` version in objects in RC16 code, and that I changed some of these call to `someRoot.zioRuntime.unsafeRun(...)` while migrating to RC18 when attempting to debug things (some blocking effects where not marked as being so). So maybe it's not more broken, I was just observing compensating bugs.

**Comment by fanf** [comment]
I confirm that the situation is similar in `RC16` and  `RC18-2`. It's extremely suprising but not more than before.

**Comment by KadekM** [comment]
@fanf I confirm it can be rather suprising. I initially spent nontrivial amount of time figuring it out. I worry when mainstream large imperative apps try to plug in ZIO to some specific module of their software "for trial" and they hit this issue and back away very quickly.

**Comment by jdegoes** [comment]
Wrapping `unsafeRun` always in `lazy val` variable should solve this problem, shouldn't it?

Possibly we could do something like this:

Maybe:

```scala
final class Lazy[A](val get: () => A)
object Lazy {
  def apply[A](a: => A): Lazy[A] = {
    lazy val computed = a
    new Lazy(() => computed)
  }
}
implicit def computeLazy[A](l: Lazy[A]): A = l.get()
...
class Runtime[+R] {
  def unsafeRun[R, E, A](zio: => ZIO[R, E, A]): Lazy[A] = ???
}
```

Any volunteers to test?

**Comment by fanf** [comment]
@jdegoes not sure I understood correctly what you meant, but that still block (with a different trace for main:
```scala
final class Lazy[A](val get: () => A)
object Lazy {
  def apply[A](a: => A): Lazy[A] = {
    lazy val computed = a
    new Lazy(() => computed)
  }
}

class internalRuntime {
  lazy val runtime = new Runtime[ZEnv]() {
    override val environment: ZEnv     = Runtime.default.environment
    override val platform   : Platform = Runtime.default.platform
    final def unsafeRun2[E, A](zio: => ZIO[ZEnv, E, A]): Lazy[A] = Lazy(unsafeRunSync(zio).getOrElse(c => throw FiberFailure(c)))
  }
  runtime.unsafeRun2(UIO.effectTotal(println("**** case 0: non blocking"))).get()
  unsafeRun(UIO.effectTotal(println("**** case 1: blocking")))

  def blocking[E, A](e: ZIO[Any, E, A]): ZIO[Any, E, A] = {
    ZIO.accessM[_root_.zio.blocking.Blocking](_.get.blocking(e)).provideLayer(ZLayer.succeedMany(runtime.environment))
  }
  def unsafeRun[E, A](e: => ZIO[Any, E, A]): A = {
    runtime.unsafeRun2(ZIO.accessM[_root_.zio.blocking.Blocking](_.get.blocking(e))).get()
  }
}
```
```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:328)
	  at zio.internal.OneShot.get(OneShot.scala:79)
	  at zio.Runtime.unsafeRunSync(Runtime.scala:82)
	  at zio.Runtime.unsafeRunSync$(Runtime.scala:77)
	  at com.normation.forissue.internalRuntime$$anon$1.unsafeRunSync(TestRuntime.scala:20)
	  at com.normation.forissue.internalRuntime$$anon$1.$anonfun$unsafeRun2$1(TestRuntime.scala:23)
	  at com.normation.forissue.internalRuntime$$anon$1$$Lambda$83.210652080.apply(Unknown Source:-1)
	  at com.normation.forissue.Lazy$.computed$lzycompute$1(TestRuntime.scala:14)
	  - locked <0x602> (a scala.runtime.LazyRef)
	  at com.normation.forissue.Lazy$.computed$1(TestRuntime.scala:14)
	  at com.normation.forissue.Lazy$.$anonfun$apply$1(TestRuntime.scala:15)
	  at com.normation.forissue.Lazy$$$Lambda$84.1107730949.apply(Unknown Source:-1)
	  at com.normation.forissue.internalRuntime.unsafeRun(TestRuntime.scala:33)
	  at com.normation.forissue.Elsewhere$.<clinit>(TestRuntime.scala:45)
	  at com.normation.forissue.TestRuntime$.main(TestRuntime.scala:57)
	  at com.normation.forissue.TestRuntime.main(TestRuntime.scala:-1)
```

**Comment by jdegoes** [comment]
You can't call `.get()` on the `Lazy`

**Comment by fanf** [comment]
I don't get it. If I don't call `get()`, thet value is not computed. Calling `get()` at the outermost possible place (in `main`) leads to the same lock. Not calling it leads to, well, nothing.

**Comment by jdegoes** [comment]
> Calling get() at the outermost possible place (in main) leads to the same lock.

Interesting. So there is a deadlock even if there is only one top-level `get` in `main`?

In that case we may be able to do something.

Have you tried only using `unsafeRunToFuture`?

**Comment by fanf** [comment]
There was two `get()`: one in main, and one in object `Elsewhere`. It's the one in `Elsewhere` (the one which should write `2000` that block. I need that one, because in my case, `Elsewhere` is where all the initialisation side effects happen. 

`unsafeRunToFuture` also block with:
```
class internalRuntime {
 ....
  def unsafeRun[E, A](e: => ZIO[Any, Throwable, A]) = {
    runtime.unsafeRunToFuture(ZIO.accessM[_root_.zio.blocking.Blocking](_.get.blocking(e)))
  }

}
object Elsewhere { // somewhere else, a blocking unsafe run is called
  Await.result(someRoot.zioRuntime.unsafeRun(UIO.effectTotal(println("**** case 2000: blocking"))), FiniteDuration(10, TimeUnit.SECONDS))
}
```


```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	  at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:205)
	  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
	  at zio.CancelableFuture.result(CancelableFuture.scala:45)
	  at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	  at scala.concurrent.Await$$$Lambda$143.411506101.apply(Unknown Source:-1)
	  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	  at scala.concurrent.Await$.result(package.scala:124)
	  at com.normation.forissue.Elsewhere$.<clinit>(TestRuntime.scala:48)
	  at com.normation.forissue.TestRuntime$.main(TestRuntime.scala:60)
	  at com.normation.forissue.TestRuntime.main(TestRuntime.scala:-1)```

**Comment by fanf** [comment]
And as previously, if I remove the call to `Blocking` in my `unsafeRun`, it does not block (sorry for that pun)

**Comment by fanf** [comment]
Oups previous comment is actually false, something didn't compile correctly.

So: contrary to previous case, `unsafeRunToFuture` blocks with or without calling `Blocking` in my unsafe methode

**Comment by hearnadam** [comment]
Is this still an issue with ZIO 2.x? Feel free to reopen if so.
