### ISSUE TITLE
unchecked error while interrupting task created from future.

### ISSUE THREAD

**Issue by schernichkin** [zio/zio#2253]
Version: 1.0-RC5

```scala
object App extends zio.App {
  val program: ZIO[Clock, Throwable, Int] = for {
    fiber <- Task.fromFuture { implicit ctx => Future { /* simulate some work */ Thread.sleep(1000); 10 } }.fork
    _ <- (ZIO.sleep(500 millis) *> fiber.interrupt).fork
    result <- fiber.join
  } yield result


  override def run(args: List[String]): ZIO[sc.App.Environment, Nothing, Int] =
    program.foldM(error => console.putStrLn(error.toString) *> ZIO.succeed(1), _ => ZIO.succeed(0))
}
```
Output:
```
Exception in thread "main" scalaz.zio.FiberFailure: Fiber failed.
An unchecked error was produced.
No ZIO Trace available.
	at scalaz.zio.Runtime.$anonfun$unsafeRun$1(Runtime.scala:56)
	at scalaz.zio.Exit.getOrElse(Exit.scala:31)
	at scalaz.zio.Exit.getOrElse$(Exit.scala:29)
	at scalaz.zio.Exit$Failure.getOrElse(Exit.scala:187)
	at scalaz.zio.Runtime.unsafeRun(Runtime.scala:56)
	at scalaz.zio.Runtime.unsafeRun$(Runtime.scala:55)
	at beams.akka.sc.App$.unsafeRun(Store.scala:141)
	at scalaz.zio.App.main(App.scala:56)
	at scalaz.zio.App.main$(App.scala:52)
	at App$.main(Main.scala:141)
	at App.main(Main.scala)
```

**Comment by adamgfraser** [comment]
Reviewing this I don't think there is any issue here, at least on `master`. Currently this snippet fails with `zio.FiberFailure: Fiber failed. An interrupt was produced by #3`. The effect is interrupted before being joined. Expected behavior is that joining an interrupted fiber should produce a fiber failure that can be recovered using combinators such as `foldCauseM` that expose the full cause but not combinators such as `foldM` that only expose the typed error channel (since interruption is not a typed error).

Replacing `foldM` with `foldCauseM` in the snippet above results in a successful effect that prints the interruption cause to the console. Behavior is the same if the effect is not created from a `Future`.

@schernichkin Please feel free to reopen if you think there is still something we need to do here.
