### ISSUE TITLE
Allow `Fiber.dump` to dump all fibers (even from other `unsafeRunSync`)

### ISSUE THREAD

**Issue by fanf** [zio/zio#2266]
Today (1.0-RC17), `Fiber.dump` does not print fiber dumps for fibers started from an other `unsafeRun`. This is extremely problematic in app which need to integrate with existing non `ZIO` code (typically: integration with existing Java API, porting a big non `ZIO` app to `ZIO`). In these case, you don't (and can't easely) now where a deadlock comes from. 

But with today behavior, you need to know where the problematic fiber(s) are:
```
object TestTwoRunNow {
  def main (args: Array[String] ): Unit = {
    val runtime = new DefaultRuntime {}

    val deadlock = {
      def plop(s: String, sem: Semaphore) = sem.withPermit((s + "plop").succeed)
      def foo (s: String, sem: Semaphore) = sem.withPermit(plop(s + "foo" , sem))

      for {
        sem <- Semaphore.make(1)
        res <- foo("oups", sem)
        _   <- IO.effect(println(res))
      } yield ()
    }

    val printDumps = (for {
      dumps <- Fiber.dump.delay(2.seconds).provide(runtime.environment)
      _     <- IO.effect(println("************* fiber dump  ************"))
      s     <- ZIO.traverse(dumps) { _.prettyPrintM}
      _     <- IO.effect(println(s.mkString("\n")))
      _     <- IO.effect(println("************* /fiber dump ************"))
    } yield ())

    // case 1
    runtime.unsafeRun(deadlock.fork *> printDumps)

    // case 2
//    runtime.unsafeRun(deadlock.fork)
//    runtime.unsafeRun(printDumps)

    Thread.sleep(5*1000)
  }
}
```

Case 1 leads to (GOOD!):
```
************* fiber dump  ************

#0 (2s2686ms) 
   Status: Running
Fiber:Id(1574086710145,0) was supposed to continue to:
  a future continuation at zio.ZIO.$amp$amp$amp(ZIO.scala:1642)
  a future continuation at zio.Fiber$.dump(Fiber.scala:574)
  a future continuation at zio.ZIO.zipWith(ZIO.scala:1543)
  a future continuation at zio.Fiber$.dump(Fiber.scala:579)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:147)
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:568)
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:574)

Fiber:Id(1574086710145,0) execution trace:
  at zio.internal.FiberContext.trace(FiberContext.scala:704)
  at zio.Fiber.dump(Fiber.scala:115)
  at zio.internal.FiberContext.status(FiberContext.scala:702)
  at zio.Fiber.dump(Fiber.scala:114)
  at zio.internal.FiberContext.id(FiberContext.scala:689)
  at zio.Fiber.dump(Fiber.scala:113)
  at zio.internal.FiberContext.getRef(FiberContext.scala:682)
  at zio.ZIO.zipWith(ZIO.scala:1543)
  at zio.internal.FiberContext.children(FiberContext.scala:675)
  at zio.UIO$.effectSuspendTotal(UIO.scala:189)
  at <unknown>.<unknown>(ZIO.scala:0)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:150)
  at zio.ZIO.ensuring(ZIO.scala:352)
  at zio.ZIO.onInterrupt(ZIO.scala:689)
  at zio.ZIO.ensuring(ZIO.scala:350)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:150)
  at zio.ZIO$._IdentityFn(ZIO.scala:2630)
  at zio.clock.Clock$Live$$anon$1.sleep(Clock.scala:49)
  at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1952)
  at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1952)
  at zio.clock.Clock$Live$$anon$1.sleep(Clock.scala:48)
  at zio.clock.package$.sleep(clock.scala:50)
  at zio.ZIO.bracket_(ZIO.scala:147)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:531)
  at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:574)

Fiber:Id(1574086710145,0) was spawned by: <empty trace>


#1 (2s2516ms) waiting on #1
   Status: Suspended(interruptible, 0 asyncs, zio.Promise.await(Promise.scala:49))
Fiber:Id(1574086710324,1) was supposed to continue to:
  a future continuation at zio.ZIO$._IdentityFn(ZIO.scala:2630)
  a future continuation at zio.ZIO.ensuring(ZIO.scala:350)
  a future continuation at zio.Semaphore.withPermits(Semaphore.scala:102)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.Semaphore.withPermits(Semaphore.scala:101)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.Semaphore.withPermits(Semaphore.scala:101)
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:562)

Fiber:Id(1574086710324,1) execution trace:
  at zio.Promise.await(Promise.scala:49)
  at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1952)
  at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1952)
  at zio.Semaphore.withPermits(Semaphore.scala:102)
  at zio.Ref$.modify$extension(Ref.scala:53)
  at zio.Semaphore.prepare(Semaphore.scala:131)
  at zio.Promise$.makeAs(Promise.scala:248)
  at zio.Promise$.make(Promise.scala:241)
  at zio.ZIOFunctions.fiberId(ZIO.scala:2054)
  at zio.ZIOFunctions.descriptor(ZIO.scala:1874)
  at zio.Semaphore.withPermits(Semaphore.scala:102)
  at zio.Semaphore.withPermits(Semaphore.scala:102)
  at zio.Ref$.modify$extension(Ref.scala:53)
  at zio.Semaphore.prepare(Semaphore.scala:131)
  at zio.Promise$.makeAs(Promise.scala:248)
  at zio.Promise$.make(Promise.scala:241)
  at zio.ZIOFunctions.fiberId(ZIO.scala:2054)
  at zio.ZIOFunctions.descriptor(ZIO.scala:1874)
  at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:561)
  at zio.Semaphore$.make(Semaphore.scala:174)
  at zio.Ref$.make(Ref.scala:169)

Fiber:Id(1574086710324,1) was spawned by:

Fiber:Id(1574086710145,0) was supposed to continue to:
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:574)
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:574)

Fiber:Id(1574086710145,0) ZIO Execution trace: <empty trace>

Fiber:Id(1574086710145,0) was spawned by: <empty trace>

************* /fiber dump ************
```

Case 2 leads to (BAD):
```
************* fiber dump  ************

#2 (2s2442ms) 
   Status: Running
Fiber:Id(1574086880664,2) was supposed to continue to:
  a future continuation at zio.ZIO.$amp$amp$amp(ZIO.scala:1642)
  a future continuation at zio.Fiber$.dump(Fiber.scala:574)
  a future continuation at zio.ZIO.zipWith(ZIO.scala:1543)
  a future continuation at zio.Fiber$.dump(Fiber.scala:579)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:147)
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:568)
  a future continuation at com.normation.TestTwoRunNow$.main(ZioCommonsTest.scala:579)

Fiber:Id(1574086880664,2) execution trace:
  at zio.internal.FiberContext.trace(FiberContext.scala:704)
  at zio.Fiber.dump(Fiber.scala:115)
  at zio.internal.FiberContext.status(FiberContext.scala:702)
  at zio.Fiber.dump(Fiber.scala:114)
  at zio.internal.FiberContext.id(FiberContext.scala:689)
  at zio.Fiber.dump(Fiber.scala:113)
  at zio.internal.FiberContext.getRef(FiberContext.scala:682)
  at zio.ZIO.zipWith(ZIO.scala:1543)
  at zio.internal.FiberContext.children(FiberContext.scala:675)
  at zio.UIO$.effectSuspendTotal(UIO.scala:189)
  at <unknown>.<unknown>(ZIO.scala:0)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:150)
  at zio.ZIO.ensuring(ZIO.scala:352)
  at zio.ZIO.onInterrupt(ZIO.scala:689)
  at zio.ZIO.ensuring(ZIO.scala:350)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:150)
  at zio.ZIO$._IdentityFn(ZIO.scala:2630)
  at zio.clock.Clock$Live$$anon$1.sleep(Clock.scala:49)
  at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1952)
  at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1952)
  at zio.clock.Clock$Live$$anon$1.sleep(Clock.scala:48)
  at zio.clock.package$.sleep(clock.scala:50)
  at zio.ZIO.bracket_(ZIO.scala:147)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:531)

Fiber:Id(1574086880664,2) was spawned by: <empty trace>

************* /fiber dump ************
```

**Comment by adamgfraser** [comment]
Thanks for reporting! Just to clarify, this was on `RC17`, right? I don't believe the fiber dump feature was available on `RC16`.

**Comment by fanf** [comment]
@adamgfraser oups, yes, sorry: RC17. Corrected in main text for accuracy, thanks!

**Comment by iravid** [comment]
It looks like the `onDone` of the `FiberContext` created in the first run is getting called after `unsafeRun` returns.

**Comment by iravid** [comment]
Ah yeah. `FiberContext#done` is called after the deadlocking fiber is forked. That causes that parent fiber to be removed from the roots because it's done.

However, that causes its children to be "lost" and become invisible to the fiber dump.

@jdegoes Should we "transplant" children of exited fibers to the `_rootFibers` set?

**Comment by jdegoes** [comment]
@iravid 

So we have three options:

1. We can transplant children to "orphan node" list (`_rootFibers`)
2. We can place children on grandparent's node, thus adding new children to a fiber that might not necessarily be expecting those children to be there.
3. We can replace the parent node with a "virtual" fiber that just holds the children, so it will appear in the hierarchy as normal.

Whatever we do, we should take into consideration the children set is used for parent-to-descendent interruption. So if a parent can't find it (and right now it can't, it seems, if the parent ends before the child), then it will not feature in auto-interruption. 

Both (2) and (3) play nicely with auto-interruption. Between them, (2) may be a little surprising to some code that thinks it knows what the children set is; and (3), while not as potentially surprising, would imply (naively) that hierarchies only grow, which potentially has some GC implications.

**Comment by jdegoes** [comment]
In any case, we should fix this ASAP, I won't have time in the next week, way too busy, but can take a look after that.

**Comment by adamgfraser** [comment]
@jdegoes @iravid I'm not as close to this work as you are but happy to jump in here if we need additional capacity on this.

**Comment by iravid** [comment]
3 makes the most sense to me. I've been already feeling that the impedance mismatch between lexical scoping and the actual fibers that show up in `ZIO.children` can be surprising, so let's not amplify that.

@adamgfraser Would be great if you could pick this up!

**Comment by adamgfraser** [comment]
@iravid Okay I will take this.
