### ISSUE TITLE
ClassCastException BoxedUnit in ZIO.raceWith / Fiber.mapM#interrupt / Exit.foreach

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#2344]
Found this stacktrace in prod, it seems to happen randomly every 5kk-th item pulled from fs2.Stream on ZIO RC16:

Unfortunately, sane ordering is lost for the error message, but it seems to happen on a path:

```
fs2.Stream.merge->
fs2.Stream.interruptibleEval->
ZIO.raceWith->
ZIO.Fiber.mapM#interrupt->
Exit.foreach->
java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class zio.Exit (scala.runtime.BoxedUnit and zio.Exit are in unnamed module of loader 'app')
	at zio.Exit.$anonfun$foreach$2(Exit.scala:106)
	at zio.Exit.fold$(Exit.scala:86)
	at zio.Exit.fold(Exit.scala:88)
	at zio.Exit$Success.fold(Exit.scala:223)
	at zio.Exit.foreach(Exit.scala:106)
	at zio.Exit.foreach$(Exit.scala:105)
	at zio.Exit$Success.foreach(Exit.scala:223)
	at zio.Fiber$$anon$3.$anonfun$interrupt$4(Fiber.scala:232)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:710)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:602)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

<details>

```
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║
║ Fiber:2456136774 execution trace:
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║
║ Fiber:1 was supposed to continue to:
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║   a future continuation at zio.interop.CatsEffect.bracketCase(cats.scala:237)
║   a future continuation at zio.ZIO.sandbox(ZIO.scala:1150)
║
║ Fiber:1 execution trace:
║   at zio.Promise$.make(Promise.scala:260)
║   at zio.Ref$.make(Ref.scala:169)
║   at izumi.functional.bio.BIOCatsConversions$BIOCatsMonad.tailRecM(BIOCatsConversions.scala:102)
║   at cats.syntax.FoldableOps$.collectFirstSomeM(foldable.scala:139)
║
║ Fiber:1 was spawned by:
║
║ Fiber:0 was supposed to continue to:
║   a future continuation at izumi.functional.bio.package$BIOForkInstances$BIOForkZio$.fork(package.scala:235)
║   a future continuation at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:82)
║   a future continuation at izumi.functional.bio.impl.BIOZio.sandbox(BIOZio.scala:64)
║   a future continuation at izumi.distage.roles.services.RoleAppExecutor$Impl.doRun(RoleAppExecutor.scala:46)
║   a future continuation at izumi.functional.bio.impl.BIOZio.bracket(BIOZio.scala:55)
║ Fiber:0 execution trace:
║   at izumi.distage.model.monadic.DIEffect.suspendF(DIEffect.scala:37)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:81)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:81)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.doRun(RoleAppExecutor.scala:45)
║   at izumi.distage.roles.services.StartupPlanExecutor$Impl.execute(StartupPlanExecutor.scala:49)
║   at izumi.distage.model.definition.DIResource$DIResourceUse$.use(DIResource.scala:132)
║ Fiber:0 was spawned by: <empty trace>
	at zio.Exit.fold(Exit.scala:88)
	at zio.Exit$Success.fold(Exit.scala:223)
	at zio.Exit.foreach(Exit.scala:106)
	at zio.Exit.foreach$(Exit.scala:105)
	at zio.Exit$Success.foreach(Exit.scala:223)
	at zio.Fiber$$anon$3.$anonfun$interrupt$4(Fiber.scala:232)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:710)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:602)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:269)
║   at fs2.internal.CompileScope.open(CompileScope.scala:129)
║   at cats.effect.concurrent.Ref$SyncRef.modify(Ref.scala:255)
║   at fs2.internal.CompileScope.open(CompileScope.scala:125)
║   at fs2.internal.CompileScope.open(CompileScope.scala:120)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:267)
║ Fiber:2456136774 was spawned by:
║
║   a future continuation at izumi.distage.model.definition.DIResource$DIResourceUse$.use(DIResource.scala:132)
║   a future continuation at zio.ZIO.sandbox(ZIO.scala:1150)
║   a future continuation at izumi.distage.model.monadic.DIEffect$$anon$2.definitelyRecover(DIEffect.scala:113)
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║
║   at izumi.distage.model.definition.DIResource$DIResourceUse$.use$extension(DIResource.scala:131)
║   at izumi.distage.model.monadic.DIEffect.suspendF(DIEffect.scala:37)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:86)
║   at izumi.distage.model.definition.DIResource$DIResourceUse$.use$extension(DIResource.scala:132)
║
▼
java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class zio.Exit (scala.runtime.BoxedUnit and zio.Exit are in unnamed module of loader 'app')
	at zio.Exit.$anonfun$foreach$2(Exit.scala:106)
	at zio.Exit.fold$(Exit.scala:86)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║ Fiber:2456136774 was spawned by:
║ Fiber:1 was supposed to continue to:
║   a future continuation at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:82)
║   a future continuation at zio.ZIO.sandbox(ZIO.scala:1150)
║   a future continuation at izumi.functional.bio.impl.BIOZio.sandbox(BIOZio.scala:64)
║   a future continuation at izumi.distage.model.monadic.DIEffect$$anon$2.definitelyRecover(DIEffect.scala:113)
║   a future continuation at izumi.distage.roles.services.RoleAppExecutor$Impl.doRun(RoleAppExecutor.scala:46)
║   a future continuation at izumi.functional.bio.impl.BIOZio.bracket(BIOZio.scala:55)
║ Fiber:0 execution trace:
║   at izumi.distage.model.definition.DIResource$DIResourceUse$.use$extension(DIResource.scala:131)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:81)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:86)
║   at izumi.distage.roles.services.StartupPlanExecutor$Impl.execute(StartupPlanExecutor.scala:49)
║ Fiber:0 was spawned by: <empty trace>
║
╠─An unchecked error was produced.
║ java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class zio.Exit (scala.runtime.BoxedUnit and zio.Exit are in unnamed module of loader 'app')
║   at zio.Fiber$$anon$3.poll(Fiber.scala:234)
║   at zio.Fiber$$anon$3.poll(Fiber.scala:234)
║   at zio.ZIO$._IdentityFn(ZIO.scala:2582)
║   at zio.Ref$.modify$extension(Ref.scala:53)
║   at zio.ZIO.raceWith(ZIO.scala:956)
║   at zio.ZIO.run(ZIO.scala:1123)
║ Fiber:2584639384 was spawned by:
║ Fiber:2583502873 was supposed to continue to:
║   a future continuation at zio.ZIO.forkInternal(ZIO.scala:1593)
║   a future continuation at zio.ZIO.raceWith(ZIO.scala:955)
║   a future continuation at zio.ZIO.raceWith(ZIO.scala:955)
║   a future continuation at zio.ZIO.raceWith(ZIO.scala:968)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:241)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:330)
║   a future continuation at fs2.internal.Algebra$.compile(Algebra.scala:128)
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║
║ Fiber:2583502873 execution trace:
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:952)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:951)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:947)
║   at zio.Ref$.make(Ref.scala:169)
║   at zio.ZIO.raceWith(ZIO.scala:946)
║   at zio.Ref$.make(Ref.scala:169)
║
║ Fiber:2583502873 was spawned by:
║
║ Fiber:2456136774 was supposed to continue to:
║   a future continuation at zio.interop.CatsConcurrent.start(cats.scala:192)
║   a future continuation at cats.syntax.FlatMapOps$.$greater$greater(flatMap.scala:33)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at fs2.internal.CompileScope.acquireResource(CompileScope.scala:163)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:250)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║
║
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║   a future continuation at zio.interop.CatsEffect.bracketCase(cats.scala:237)
║   a future continuation at zio.ZIO.sandbox(ZIO.scala:1150)
║
║ Fiber:1 execution trace:
║   at zio.Promise$.make(Promise.scala:260)
║   at zio.Ref$.make(Ref.scala:169)
║   at izumi.functional.bio.BIOCatsConversions$BIOCatsMonad.tailRecM(BIOCatsConversions.scala:102)
║   at cats.syntax.FoldableOps$.collectFirstSomeM(foldable.scala:139)
║
║ Fiber:1 was spawned by:
║
║ Fiber:0 was supposed to continue to:
║   a future continuation at izumi.functional.bio.package$BIOForkInstances$BIOForkZio$.fork(package.scala:235)
║   a future continuation at izumi.distage.model.definition.DIResource$DIResourceUse$.use(DIResource.scala:132)
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║
║   at izumi.distage.model.monadic.DIEffect.suspendF(DIEffect.scala:37)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.runRoles(RoleAppExecutor.scala:81)
║   at izumi.distage.model.monadic.DIEffect.suspendF(DIEffect.scala:37)
║   at izumi.distage.roles.services.RoleAppExecutor$Impl.doRun(RoleAppExecutor.scala:45)
║   at izumi.distage.model.definition.DIResource$DIResourceUse$.use$extension(DIResource.scala:132)
║   at izumi.distage.model.definition.DIResource$DIResourceUse$.use(DIResource.scala:132)
║
║ 	at zio.Exit.$anonfun$foreach$2(Exit.scala:106)
║ 	at zio.Exit.fold(Exit.scala:88)
║ 	at zio.Exit.fold$(Exit.scala:86)
║ 	at zio.Exit$Success.fold(Exit.scala:223)
║ 	at zio.Exit.foreach(Exit.scala:106)
║ 	at zio.Exit.foreach$(Exit.scala:105)
║ 	at zio.Exit$Success.foreach(Exit.scala:223)
║ 	at zio.Fiber$$anon$3.$anonfun$interrupt$4(Fiber.scala:232)
║ 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:710)
║ 	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:602)
║ 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
║ 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
║ 	at java.base/java.lang.Thread.run(Thread.java:834)
║
║ Fiber:2584639384 was supposed to continue to:
║   a future continuation at zio.ZIO.raceAttempt(ZIO.scala:893)
║   a future continuation at zio.ZIO.raceWith(ZIO.scala:939)
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║   a future continuation at zio.ZIO.to(ZIO.scala:1338)
║   a future continuation at zio.ZIO.ensuring(ZIO.scala:318)
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║
║ Fiber:2584639384 execution trace:
║   at zio.Fiber$$anon$3.interrupt(Fiber.scala:232)
║   at zio.internal.FiberContext.interrupt(FiberContext.scala:615)
║   at zio.ZIO.raceWith(ZIO.scala:939)
║   at zio.UIO$.effectSuspendTotal(UIO.scala:183)
║   at zio.ZIO.raceWith(ZIO.scala:936)
║   at zio.ZIO.run(ZIO.scala:1123)
║   at zio.internal.FiberContext.poll(FiberContext.scala:622)
║   at zio.Fiber$$anon$3.await(Fiber.scala:228)
║   at zio.internal.FiberContext.await(FiberContext.scala:619)
║
║
║   a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:986)
║   a future continuation at fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:386)
║   at zio.ZIO.onInterrupt(ZIO.scala:620)
║   at zio.ZIO.ensuring(ZIO.scala:318)
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.raceWith(ZIO.scala:946)
║   at zio.Promise$.make(Promise.scala:260)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at fs2.internal.CompileScope.acquireResource(CompileScope.scala:163)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:250)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:269)
║   at fs2.internal.CompileScope.open(CompileScope.scala:129)
║   at cats.effect.concurrent.Ref$SyncRef.modify(Ref.scala:255)
║   at fs2.internal.CompileScope.open(CompileScope.scala:125)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:267)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
║   at zio.ZIO.ensuring(ZIO.scala:320)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
║   at zio.ZIO$._IdentityFn(ZIO.scala:2582)
║   at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1891)
║   at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1887)
║   at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1887)
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:952)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:951)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:947)
║   at zio.Ref$.make(Ref.scala:169)
║   at zio.Ref$.make(Ref.scala:169)
║   at zio.ZIO.raceWith(ZIO.scala:945)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║   at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║   at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:241)
║   at fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:386)
║   at zio.ZIO.refailWithTrace(ZIO.scala:986)
║   at zio.ZIO.raceWith(ZIO.scala:968)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
║
║ Fiber:2583502873 was spawned by:
║
║ Fiber:2456136774 was supposed to continue to:
║   a future continuation at zio.interop.CatsConcurrent.start(cats.scala:192)
║   a future continuation at cats.syntax.FlatMapOps$.$greater$greater(flatMap.scala:33)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║
║ Fiber:2456136774 execution trace:
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.CompileScope.open(CompileScope.scala:120)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.raceWith(ZIO.scala:952)
║   at zio.ZIO.raceWith(ZIO.scala:951)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:946)
║   at zio.Promise$.make(Promise.scala:260)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:211)
║   at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:241)
║   at fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:386)
║   at zio.ZIO.refailWithTrace(ZIO.scala:986)
║   at zio.ZIO.raceWith(ZIO.scala:968)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
║   at zio.ZIO.raceWith(ZIO.scala:966)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
║   at zio.ZIO.ensuring(ZIO.scala:320)
║   at zio.ZIO.onInterrupt(ZIO.scala:620)
║   at zio.ZIO.ensuring(ZIO.scala:318)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
║   at zio.ZIO$ZipLeftFn.apply(ZIO.scala:2673)
║   at zio.UIO$.effectSuspendTotal(UIO.scala:183)
║   at zio.ZIO.raceWith(ZIO.scala:959)
║   at zio.Ref$.get$extension(Ref.scala:41)
W 2019-11-23T01:42:04.117             (LoggingZioRunner.scala:26)  ….c.L.apply.customHandler.20 [   81:zio-1349007635-2    ] Fiber terminated erroneously with unhandled defect=java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class zio.Exit (scala.runtime.BoxedUnit and zio.Exit are in unnamed module of loader 'app') trace=Fiber failed.
╥
╠─An error was rethrown with a new trace.
║
║ Fiber:2583502873 was supposed to continue to:
║   a future continuation at fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:386)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:241)
║   a future continuation at fs2.internal.Algebra$.compileLoop(Algebra.scala:330)
║   a future continuation at fs2.internal.Algebra$.compile(Algebra.scala:128)
║   a future continuation at zio.ZIO.run(ZIO.scala:1123)
║   a future continuation at zio.interop.CatsEffect.bracketCase(cats.scala:237)
║   a future continuation at fs2.Stream$CompileOps.foldChunks(Stream.scala:4213)
║   a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   a future continuation at fs2.Stream$.merge(Stream.scala:1814)
║
║ Fiber:2583502873 execution trace:
║   at zio.ZIO.refailWithTrace(ZIO.scala:986)
║   at zio.ZIO.ensuring(ZIO.scala:315)
║   at zio.ZIO.onInterrupt(ZIO.scala:620)
║   at zio.ZIO.ensuring(ZIO.scala:313)
║   at zio.ZIO.ensuring(ZIO.scala:315)
║   at zio.ZIO.onInterrupt(ZIO.scala:620)
║   at zio.ZIO.ensuring(ZIO.scala:313)
║   at zio.ZIO$._IdentityFn(ZIO.scala:2582)
║   at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1891)
║   at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1887)
║   at zio.ZIOFunctions.effectAsyncInterrupt(ZIO.scala:1887)
║   at zio.ZIO.raceWith(ZIO.scala:955)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.forkInternal(ZIO.scala:1593)
║   at zio.ZIO.raceWith(ZIO.scala:947)
║   at zio.Ref$.make(Ref.scala:169)
║   at zio.Ref$.make(Ref.scala:169)
║   at zio.ZIO.raceWith(ZIO.scala:945)
║   at cats.effect.concurrent.Ref$SyncRef.get(Ref.scala:221)
║   at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:2669)
║   at fs2.internal.Algebra$.compileLoop(Algebra.scala:192)
║   at zio.ZIO.raceWith(ZIO.scala:965)
║   at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
```

</details>

**Comment by guizmaii** [comment]
@neko-kai Is it fixed? Can we close this issue?

**Comment by neko-kai** [comment]
> @neko-kai Is it fixed? Can we close this issue?

No idea, but this was back in ZIO1, so whatever
