### ISSUE TITLE
Schedule combination fails the Fiber

### ISSUE THREAD

**Issue by sderosiaux** [zio/zio#2396]
Hi,

I'm running with ZIO 1.0.0-RC17.

In the following program, when both `Schedule`s are combined, the fiber fails. When there is only one `Schedule` used, it works. Is this expected?

```scala
override def run(args: List[String]) = 
    ZIO.fromEither(Either.cond(false, -1, 1))
      .retry(Schedule.recurs(2) && Schedule.spaced(1.second))
      .catchAll(ZIO.succeed)
```

Error:
```
Fiber failed.
A checked error was not handled.
()

Fiber:Id(1575338432813,12) was supposed to continue to: <empty trace>

Fiber:Id(1575338432813,12) execution trace:
  at zio.Schedule.check(Schedule.scala:238)
Fiber:Id(1575338432813,12) was spawned by:

Fiber:Id(1575338432813,11) was supposed to continue to: <empty trace>

Fiber:Id(1575338432813,11) ZIO Execution trace: <empty trace>

Fiber:Id(1575338432813,11) was spawned by:

Fiber:Id(1575338430587,1) was supposed to continue to:
  a future continuation at zio.ZIO.zipWithPar(ZIO.scala:1574)
  a future continuation at zio.ZIO.retryOrElseEither(ZIO.scala:1150)
  a future continuation at zio.ZIO.retryOrElse(ZIO.scala:1132)
...
```
The related code in `Schedule.check`:
```scala
          test(a, self.extract(a, s)).flatMap {
            case false => ZIO.fail(())
            case true  => update(a, s)
          }
```

**Comment by adamgfraser** [comment]
This is not expected behavior. It is a variant of #2309.  We have a work in process PR #2339 to address this.

**Comment by sderosiaux** [comment]
Ah yes sorry, I didn't see it. Closing this one. Thanks!
