### ISSUE TITLE
[zio-test] java.lang.IllegalArgumentException: n must be positive

### ISSUE THREAD

**Issue by guizmaii** [zio/zio#2444]
Hi everyone,

I encountered a strange behavior in my tests. I have the following error that make my tests execution crash:

```scala
[info]       Fiber failed.
[info]       An unchecked error was produced.
[info]       java.lang.IllegalArgumentException: n must be positive
[info]           at zio.test.environment.TestRandom$Test.randomInt(TestRandom.scala:273)
[info]           at zio.test.environment.TestRandom$Test.nextInt(TestRandom.scala:352)
[info]           at zio.random.package$.$anonfun$nextInt$1(random.scala:28)
[info]           at zio.internal.FiberContext.evaluateNow(FiberContext.scala:525)
[info]           at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:661)
[info]           at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]           at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]           at java.base/java.lang.Thread.run(Thread.java:834)
```

When I put a breakpoint where it's throwing, here's the result: https://www.dropbox.com/s/9f27lkrmld2uuxa/Screenshot%202019-12-08%2018.39.25.png?dl=0

Here's how I declare my test environment:

```scala
val testingBackend: Task[SttpBackendStub[Task, Nothing]] = AsyncHttpClientZioBackend().map(SttpBackendStub(_))

def testingEnv[T](response: => Response[T]): RIO[TestEnvironment, Random with Sized with MyService] =
  (ZIO.runtime[TestEnvironment] <*> testingBackend).map {
    case (runtime, backend) =>
      new Random with Sized with MyService {
        override val random: Random.Service[Any] = runtime.environment.random
        override val sized: Sized.Service[Any]   = runtime.environment.sized
        override val myService: MyService.Service[Any] =
          new MyService {
            override implicit val sttpBackend: SttpBackend[Task, Nothing, NothingT] =
              backend
                .whenRequestMatches(r =>
                  r.method == Method.POST && r.uri == uri"https://example.com/api/endpoint"
                )
                .thenRespond(response)
            }.myService
          }
  }
```

And here's an example of my tests:

```scala
testM("with an error") {
  val error = HttpError("Network Partition")
  checkM(genRequest) { request =>
    assertM(execute(request).flip, equalTo(error))
  }.provideSomeM(testingEnv(Response(error.asLeft, StatusCode.NotFound)))
}
```

**Comment by adamgfraser** [comment]
@guizmaii Thanks for reporting! Would you mind sharing the code for the generator you are using as well?

**Comment by adamgfraser** [comment]
@guizmaii Just wanted to follow up on this. Would you happen to have the code for the generator you were using. I tried locally with a version of the testEnvironment and wasn’t able to replicate. I think the issue may be a bug in a generator but would help me track it down if I could see the generator that you were using. Thanks in advance!

**Comment by guizmaii** [comment]
Hey @adamgfraser,

Sorry for the delay.

Here's the gens generating the problem:

```
import eu.timepit.refined.refineV
import eu.timepit.refined.types.string.NonEmptyString
import zio.random.Random
import zio.test.{Gen, Sized}

trait ZioGens {

  final val genNonEmptyString: Gen[Random with Sized, NonEmptyString] = Gen.alphaNumericString.filter(_.nonEmpty).map(refineV.unsafeFrom(_))
  final val genScore: Gen[Random, Score]                              = Gen.int(0, 700).map(refineV.unsafeFrom(_))
  final val genSalary: Gen[Random, Salary]                            = Gen.int(0, Int.MaxValue).map(refineV.unsafeFrom(_))
  final val genRating: Gen[Random, Rating]            = Gen.double(0.0, 1.0).map(refineV.unsafeFrom(_))
  final val genABC: Gen[Random, ABC]                                  = Gen.double(0.0, Double.MaxValue).filter(_ == 0.0).map(refineV.unsafeFrom(_))

  final val genCard: Gen[Random with Sized, Card] =
    for {
      cardName       <- genNonEmptyString
      abc            <- genABC
      rating <- genRating
    } yield Card(card = cardName, abc = abc, rating = rating)

  final val genCardsRequest: Gen[Random with Sized, CardRequest] =
    for {
      name   <- genNonEmptyString
      score  <- genScore
      salary <- genSalary
    } yield CardRequest(name = name, score = score, salary = salary)

}
```

**Comment by adamgfraser** [comment]
@guizmaii No worries and thanks for sharing! Should the `filter` call in `genABC` be `(_ != 0.0)` instead of `(_ == 0.0)`?

**Comment by guizmaii** [comment]
@adamgfraser Yep you're right, the filter should be `(_ != 0.0)` but if I correct that an relaunch my tests, I still have the problem. 😕

**Comment by adamgfraser** [comment]
@guizmaii Thanks again for reporting! The issue turned out to be with the `Gen#int` when the range was larger than `Int.MaxValue` . It is fixed on master and will be available in the next release but to get your tests working now you can use the version below.

```scala
   final def int(min: Int, max: Int): Gen[Random, Int] =
    Gen.fromEffectSample {
      val difference = max - min + 1
      val effect =
        if (difference > 0) nextInt(difference).map(min + _)
        else nextInt.doUntil(n => min <= n && n <= max)
      effect.map(Sample.shrinkIntegral(min))
    }
```

**Comment by guizmaii** [comment]
Thanks @adamgfraser. Awesome work!
