### ISSUE TITLE
Fiber methods aren't stack-safe: awaitAll, collectAll, joinAll

### ISSUE THREAD

**Issue by evis** [zio/zio#2637]
Given such a big sequence:

```scala
val sequence = ZIO.sequence(List.fill(100000)(ZIO.unit.fork))
```

All of these programs fail with StackOverflowError:

```scala
sequence.flatMap(Fiber.awaitAll)
sequence.flatMap(Fiber.joinAll)
sequence.map(Fiber.collectAll).flatMap(_.join)
```

Stack trace:

```
java.lang.StackOverflowError
	at zio.Fiber$$anon$4.await(Fiber.scala:388)
	at zio.Fiber$$anon$4.await(Fiber.scala:388)
	at zio.Fiber$$anon$4.await(Fiber.scala:388)
	at zio.Fiber$$anon$4.await(Fiber.scala:388)
	...
```

**Comment by adamgfraser** [comment]
@evis Are you working on this?

**Comment by evis** [comment]
Not yet, feel free to take it.

**Comment by adamgfraser** [comment]
Okay, I will take it.
