### ISSUE TITLE
Handle shutdown (SIGTERM / SIGINT) of `zio.App` gracefully.

### ISSUE THREAD

**Issue by megri** [zio/zio#2661]
Currently, when the following application is terminated from the outside (either with `kill` or as part of a container shutdown) a FiberFailed trace will be logged, indicating that the process ended with an error.

```scala
import zio._

object Main extends App {
  def run(args: List[String]): ZIO[ZEnv, Nothing, Int] =
    (putStrLn("Started") *> ZIO.never).onInterrupt(putStrLn("Stopped"))
}
```

It would be nice if termination was expected and didn't result in a trace.

**Comment by adamgfraser** [comment]
I believe this was resolved by #2354. If I run your program on `master` and terminate it with control C I get the following output:

```
sbt:zio> run
[info] Compiling 4 Scala sources to /Users/adamfraser/zio/core/jvm/target/scala-2.12/classes ...
[info] running zio.Server 
Started
^C
[warn] Canceling execution...
[error] Total time: 16 s, completed Jan 20, 2020 7:12:29 AM
```

**Comment by iravid** [comment]
Just to verify, I'd try to run it standalone; SBT doesn't always forward the SIGINT to the running application.

**Comment by megri** [comment]
> I believe this was resolved by #2354. If I run your program on `master` and terminate it with control C I get the following output:
> 
> ```
> sbt:zio> run
> [info] Compiling 4 Scala sources to /Users/adamfraser/zio/core/jvm/target/scala-2.12/classes ...
> [info] running zio.Server 
> Started
> ^C
> [warn] Canceling execution...
> [error] Total time: 16 s, completed Jan 20, 2020 7:12:29 AM
> ```

Ah, I've only tried with RC17. I'll try it with a locally compiled release.

**Comment by adamgfraser** [comment]
@megri Did you get a chance to try this?

**Comment by tylerprete** [comment]
For what it's worth -- I just tried this on RC17 and on the latest snapshot. Was able to reproduce on RC17:

```scala
tprete-C02YT62SLVDQ:zio-playground tprete$ java -jar out/playground/assembly/dest/out.jar
Started
^CStopped
Exception in thread "main" zio.FiberFailure: Fiber failed.
An interrupt was produced by #2.

Fiber:Id(1580149373183,1) was supposed to continue to:
  a future continuation at zio.ZIO.ensuring(ZIO.scala:350)

Fiber:Id(1580149373183,1) execution trace:
  at zio.ZIOFunctions.never(ZIO.scala:2371)
  at other.Main$.run(Main.scala:8)
  at zio.console.Console$Live$$anon$1.putStrLn(Console.scala:59)
  at zio.console.package$.putStrLn(console.scala:35)

Fiber:Id(1580149373183,1) was spawned by:

Fiber:Id(1580149373064,0) was supposed to continue to:
  a future continuation at zio.App.main(App.scala:57)
  a future continuation at zio.App.main(App.scala:56)

Fiber:Id(1580149373064,0) ZIO Execution trace: <empty trace>

Fiber:Id(1580149373064,0) was spawned by: <empty trace>
```

And then with the snapshot ```1.0.0-RC17+281-0351fa8d-SNAPSHOT"``` there was no error:
```
tprete-C02YT62SLVDQ:zio-playground tprete$ java -jar out/playground/assembly/dest/out.jar
Started
^CStopped
```

**Comment by regiskuckaertz** [comment]
@megri gonna close this as it's been resolved, but please feel free to reopen if your experience with the latest build is different.

**Comment by zynque** [comment]
Hello, I'm seeing what appears to be the same or similar issue in ZIO 2.0.4

```scala
import zio._
import zio.Console._

object Main extends zio.ZIOAppDefault {
  override def run: ZIO[Any, Any, Any] =
    (printLine("Started") *> ZIO.never).onInterrupt(printLine("Stopped").orDie)
}
```

Attempting to terminate with Ctrl-C, the app logs some fiber errors and does not terminate. (I'm running via sbt)


This issue only seems to occur in Windows.

Example Windows output:
```scala
[info] running Main
Started
"zio-fiber-0" (4s 225ms) waiting on #3
        Status: Suspended((Interruption, CooperativeYielding, FiberRoots), <no trace>)
"zio-fiber-3" (3s 912ms)
        Status: Suspended((Interruption, CooperativeYielding, FiberRoots), <no trace>)
"zio-fiber-4" (3s 913ms)
        Status: Suspended((Interruption, CooperativeYielding, FiberRoots), <empty>.Main.run(Main.scala:15))
        at <empty>.Main.run(Main.scala:15)
```

Example Ubuntu output:
```scala
[info] running Main
Started
^C
[warn] Canceling execution...
Cancelled: run
[error] Cancelled: run
[error] Use 'last' for the full log.
Exception in thread "sbt-bg-threads-1" java.lang.Error: java.lang.InterruptedException
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at zio.internal.OneShot.get(OneShot.scala:83)
        at zio.Runtime$UnsafeAPIV1.run(Runtime.scala:133)
        at zio.ZIOAppPlatformSpecific.main$$anonfun$1(ZIOAppPlatformSpecific.scala:48)
        at zio.Unsafe$.unsafeCompat(Unsafe.scala:36)
        at zio.ZIOAppPlatformSpecific.main(ZIOAppPlatformSpecific.scala:48)
        at zio.ZIOAppPlatformSpecific.main$(ZIOAppPlatformSpecific.scala:6)
        at Main$.main(Main.scala:4)
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:143)
        at sbt.Run.execute$1(Run.scala:93)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
        at sbt.Run$.executeSuccess(Run.scala:186)
        at sbt.Run.runWithLoader(Run.scala:120)
        at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1981)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1920)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
```
