### ISSUE TITLE
ZIO Test: omitting a mock from Expectation results in an exception

### ISSUE THREAD

**Issue by arjun-1** [zio/zio#2670]
Recently I started using zio-test successfully with mocks. An example of such a mock I used:
```
def okManagedMock(sessionId: String) = {
  val mockMomaClient: Managed[Nothing, MomaClient] = (
    (MockMomaClient.getNodeUrl(equalTo(sessionId)) returns value(
      uri"localhost"
    )) *>
    (MockMomaClient.getFrameCount(anything) returns value(1)) *>
    (MockMomaClient.getPosition(anything) returns value(position))
  )
  mockMomaClient.map(createEnv)
}
```
Whenever we omit a mock from the Expectation, e.g.:
```
def incompleteManagedMock(sessionId: String) = {
  val mockMomaClient: Managed[Nothing, MomaClient] = (
    (MockMomaClient.getNodeUrl(equalTo(sessionId)) returns value(
      uri"localhost"
    )) *>
    (MockMomaClient.getFrameCount(anything) returns value(1))
  )
  mockMomaClient.map(createEnv)
}
```
In that case, my test will fail with a not so helpful error message:
```
[info] - A main server route
[info]   - returns positions
[info]     Fiber failed.
[info]     ╥
[info]     ╠─An error was rethrown with a new trace.
[info]     ║ 
[info]     ║ Fiber:Id(1579528206274,28) was supposed to continue to:
[info]     ║   a future continuation at com.foo.PositionService$.getPositions(PositionService.scala:14)
[info]     ║   a future continuation at com.foo.PositionController$$anonfun$1.applyOrElse(PositionController.scala:33)
[info]     ║   a future continuation at cats.instances.OptionInstances$$anon$1.traverse(option.scala:67)
[info]     ║   a future continuation at cats.data.OptionT.orElseF(OptionT.scala:101)
[info]     ║   a future continuation at cats.data.OptionT.getOrElse(OptionT.scala:68)
```
it does not tell what went wrong, nor whether I should look for my mistake in production or test code :). As was mentioned in the Discord channel, this appears to be a bug

**Comment by ioleo** [comment]
@jdegoes Yes, I'll do it tomorrow.

**Comment by adamgfraser** [comment]
@ioleo Thank you! 🙏
