### ISSUE TITLE
After `Make Fiber a Sum type` commit I get NoClassDefFoundError: zio/Fiber$Runtime

### ISSUE THREAD

**Issue by scalavision** [zio/zio#2725]
I get this stacktrace:

<--snip-->
```
Fiber failed.
An unchecked error was produced.
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: zio/Fiber$Runtime
        at zio.stream.ZStream.$anonfun$mapMPar$3(ZStream.scala:1896)
        at zio.ZManaged.$anonfun$flatMap$6(ZManaged.scala:306)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:797)
        at zio.internal.FiberContext.$anonfun$fork$2(FiberContext.scala:655)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: zio/Fiber$Runtime
        ... 7 more
Caused by: java.lang.ClassNotFoundException: zio.Fiber$Runtime
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

Fiber:Id(1580041368969,1) was supposed to continue to:
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:307)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:306)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:307)
  a future continuation at zio.stream.ZStream.fold(ZStream.scala:1452)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.ZManaged.use(ZManaged.scala:748)
  a future continuation at workflow.ZStreamTutorial$.countLinesInFiles(ZStreamTutorial.scala:67)
  a future continuation at workflow.ZStreamTutorial$.run(ZStreamTutorial.scala:77)
  a future continuation at workflow.ZStreamTutorial$.run(ZStreamTutorial.scala:81)
  a future continuation at workflow.WorkFlow$.run(WorkFlow.scala:21)

Fiber:Id(1580041368969,1) execution trace:
  at zio.ZManaged.flatMap(ZManaged.scala:306)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:150)
  at zio.Semaphore$.make(Semaphore.scala:174)
  at zio.Ref$.make(Ref.scala:169)
  at zio.ZManaged.flatMap(ZManaged.scala:305)
  at zio.Ref$.update$extension(Ref.scala:123)
  at zio.ZManaged.flatMap(ZManaged.scala:305)
  at zio.ZManaged.flatMap(ZManaged.scala:307)
  at zio.Ref$.update$extension(Ref.scala:123)
  at zio.ZManaged.flatMap(ZManaged.scala:307)
  at zio.ZManaged.flatMap(ZManaged.scala:301)
  at zio.Ref$.make(Ref.scala:169)
  at zio.ZManaged.flatMap(ZManaged.scala:306)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:150)
  at zio.ZManaged.flatMap(ZManaged.scala:305)
  at zio.Ref$.update$extension(Ref.scala:123)
  at zio.ZManaged.flatMap(ZManaged.scala:305)
  at zio.ZManaged$.make(ZManaged.scala:1194)
  at zio.Queue$.createQueue(Queue.scala:402)
  at zio.Promise$.makeAs(Promise.scala:248)
  at zio.Promise$.make(Promise.scala:241)
  at zio.ZIOFunctions.fiberId(ZIO.scala:2054)
  at zio.ZIOFunctions.descriptor(ZIO.scala:1874)
  at zio.Queue$.bounded(Queue.scala:357)
  at zio.Queue$.bounded(Queue.scala:357)
  at zio.ZManaged.flatMap(ZManaged.scala:305)
  at zio.Ref$.update$extension(Ref.scala:123)
  at zio.ZManaged.flatMap(ZManaged.scala:305)
  at zio.ZManaged.flatMap(ZManaged.scala:301)
  at zio.Ref$.make(Ref.scala:169)
  at zio.ZManaged.use(ZManaged.scala:748)
  at zio.ZManaged.flatMap(ZManaged.scala:301)
  at zio.Ref$.make(Ref.scala:169)
  at workflow.ZStreamTutorial$.run(ZStreamTutorial.scala:76)
  at zio.console.Console$Live$$anon$1.putStrLn(Console.scala:59)
  at zio.console.package$.putStrLn(console.scala:35)
  at workflow.ZStreamTutorial$.run(ZStreamTutorial.scala:76)
  at workflow.ZStreamTutorial$.workDir(ZStreamTutorial.scala:54)
  at workflow.ZStreamTutorial$.run(ZStreamTutorial.scala:75)
  at zio.Promise$.makeAs(Promise.scala:248)
  at zio.Promise$.make(Promise.scala:241)
  at zio.ZIOFunctions.fiberId(ZIO.scala:2054)
  at zio.ZIOFunctions.descriptor(ZIO.scala:1874)
```
EDIT: Added more of the stacktrace
<--snip-->

From this code, when executing the `run` method, it uses Lihaoyis `os-lib` library, but I think this already is available in ammonite:

```scala
// The example is slightly changed from the talk:
// Functional Scala - Modern Data Driven Applications with ZIO Streams by Itamar Ravid
import zio._
import stream._
import console._
import java.nio.file.Files
import java.nio.file.Paths
import java.nio.file.LinkOption
import java.io.InputStream
import java.io.IOExceptio

val workDir: Task[os.Path] = Task { os.pwd / "some_path" }

val paths: Task[java.util.stream.Stream[java.nio.file.Path]] = 
    workDir.map { wd => Files.walk(wd.wrapped) }

  def countLinesInFiles(lock: Promise[Nothing, Int]): ZIO[zio.console.Console, Throwable, Boolean] = 
    ZStream.fromJavaStream(paths).filter(p => Files.isRegularFile(p, LinkOption.NOFOLLOW_LINKS)).mapMPar(6) { path =>
     ZStream.fromInputStream(Files.newInputStream(path))
      .chunks
      .aggregate(ZSink.utf8DecodeChunk)
      .aggregate(ZSink.splitLines)
      .fold(0)(_ + _.size)
    }.fold(0)(_ + _)
    .flatMap{ lines => 
      putStrLn(lines.toString) *>
      lock.succeed(42)
    }

def run =  (for {
      promise <- Promise.make[Nothing, Int]
      wd      <- workDir
      _       <- putStrLn(s"Workdir: ${wd}")
      _       <- countLinesInFiles(promise)
      _   <- promise.await 
    } yield 0) orElse ZIO.succeed(1)
```

I have published the different commits locally and used them in my project. I am not that familiar with zio at the moment, so this might be only some local problem.

When switching back to commit 0f1dc5b311351006812050ac63381dfb2a42a24e (Update scalafmt to 2.3.2) everything works fine.

Hope this might be helpful.

**Comment by adamgfraser** [comment]
@scalavision We made two different subtypes of fibers in that PR and had methods return the specific type of fiber. It looks like it is an issue where the compiler is not finding the new version of the file that has that class definition. I think if you clean and rebuild your project that may help.

**Comment by scalavision** [comment]
looks like you are correct @adamgfraser , sorry about the inconvenience!!! 

I was using `mill`, seems it was not able to clean the project properly. Using sbt, everything works!

**Comment by adamgfraser** [comment]
No problem at all! Thanks for using ZIO!
