### ISSUE TITLE
Running hello world with graalvm fails with scala.MatchError: null

### ISSUE THREAD

**Issue by protocarl** [zio/zio#2940]
Running a zio hello world with graalvm fails with scala.MatchError: null

I put together a hello world app with zio `1.0.0-RC17+421-424ddcd4-SNAPSHOT` and graalvm `graalvm-ce:20.0.0-java11`

https://github.com/protocarl/zio-graalvm-hello-world

compile with:
`sbt graalvm-native-image:packageBin`

run with:
`docker run -it -v $(pwd)/target:/target oracle/graalvm-ce:20.0.0-java11 /target/graalvm-native-image/zio-graalvm-hello-world`

this fails with:
```
Fiber failed.
An unchecked error was produced.
scala.MatchError: null
	at zio.internal.stacktracer.impl.AkkaLineNumbers$.apply(AkkaLineNumbers.scala:63)
	at zio.internal.stacktracer.impl.AkkaLineNumbersTracer.traceLocation(AkkaLineNumbersTracer.scala:31)
	at zio.internal.stacktracer.Tracer$$anon$1.traceLocation(Tracer.scala:35)
	at zio.internal.FiberContext.traceLocation(FiberContext.scala:106)
	at zio.internal.FiberContext.pushContinuation(FiberContext.scala:113)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:371)
	at zio.Runtime.unsafeRunAsync(Runtime.scala:111)
	at zio.Runtime.unsafeRunAsync$(Runtime.scala:91)
	at protocarl.ziograalvmhelloworld.Main$.unsafeRunAsync(Main.scala:6)
	at zio.Runtime.unsafeRunSync(Runtime.scala:80)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:77)
	at protocarl.ziograalvmhelloworld.Main$.unsafeRunSync(Main.scala:6)
	at zio.Runtime.unsafeRun(Runtime.scala:57)
	at zio.Runtime.unsafeRun$(Runtime.scala:56)
	at protocarl.ziograalvmhelloworld.Main$.unsafeRun(Main.scala:6)
	at zio.App.main(App.scala:64)
	at zio.App.main$(App.scala:52)
	at protocarl.ziograalvmhelloworld.Main$.main(Main.scala:6)
	at protocarl.ziograalvmhelloworld.Main.main(Main.scala)

Fiber:Id(1582228210244,0) was supposed to continue to: <empty trace>

Fiber:Id(1582228210244,0) ZIO Execution trace: <empty trace>

Fiber:Id(1582228210244,0) was spawned by: <empty trace>
Exception in thread "main" zio.FiberFailure: Fiber failed.
An unchecked error was produced.
scala.MatchError: null
	at zio.internal.stacktracer.impl.AkkaLineNumbers$.apply(AkkaLineNumbers.scala:63)
	at zio.internal.stacktracer.impl.AkkaLineNumbersTracer.traceLocation(AkkaLineNumbersTracer.scala:31)
	at zio.internal.stacktracer.Tracer$$anon$1.traceLocation(Tracer.scala:35)
	at zio.internal.FiberContext.traceLocation(FiberContext.scala:106)
	at zio.internal.FiberContext.pushContinuation(FiberContext.scala:113)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:371)
	at zio.Runtime.unsafeRunAsync(Runtime.scala:111)
	at zio.Runtime.unsafeRunAsync$(Runtime.scala:91)
	at protocarl.ziograalvmhelloworld.Main$.unsafeRunAsync(Main.scala:6)
	at zio.Runtime.unsafeRunSync(Runtime.scala:80)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:77)
	at protocarl.ziograalvmhelloworld.Main$.unsafeRunSync(Main.scala:6)
	at zio.Runtime.unsafeRun(Runtime.scala:57)
	at zio.Runtime.unsafeRun$(Runtime.scala:56)
	at protocarl.ziograalvmhelloworld.Main$.unsafeRun(Main.scala:6)
	at zio.App.main(App.scala:64)
	at zio.App.main$(App.scala:52)
	at protocarl.ziograalvmhelloworld.Main$.main(Main.scala:6)
	at protocarl.ziograalvmhelloworld.Main.main(Main.scala)

Fiber:Id(1582228210244,0) was supposed to continue to: <empty trace>

Fiber:Id(1582228210244,0) ZIO Execution trace: <empty trace>

Fiber:Id(1582228210244,0) was spawned by: <empty trace>
```

**Comment by protocarl** [comment]
zio version `1.0.0-RC17` works as expected:
```
Hello, World!
```

**Comment by neko-kai** [comment]
Looks like just a typo https://github.com/zio/zio/pull/2941
@protocarl I guess you better disable Tracing on graal-native-image because it only works on the JVM/GraalVM-JIT (by wrapping `run` in `.untraced`)
