### ISSUE TITLE
unsafeFromLayer fails with ScalaJS

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#3021]
Found this in the interop-cats project, we need to build a `Runtime[ZEnv]` in a test and calling `unsafeFromLayer` fails on ScalaJS. In particular `addShutdownHook` calls `js.Dynamic.global.onunload = { (_: Any) => action() }` which throws in this context (ZIO Test).

```
An unchecked error was produced.
java.lang.Error: stub
	at scala.scalajs.runtime.package$.linkingInfo(package.scala:201)
	at scala.scalajs.runtime.package$.environmentInfo(package.scala:195)
	at scala.scalajs.js.Dynamic$.global(Dynamic.scala:81)
	at zio.internal.PlatformSpecific.addShutdownHook(PlatformSpecific.scala:36)
	at zio.internal.PlatformSpecific.addShutdownHook$(PlatformSpecific.scala:35)
	at zio.internal.Platform$.addShutdownHook(Platform.scala:85)
	at zio.Runtime$.$anonfun$unsafeFromLayer$6(Runtime.scala:256)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:329)
	at zio.Runtime.unsafeRunAsync(Runtime.scala:110)
	at zio.Runtime.unsafeRunAsync$(Runtime.scala:91)
	at zio.Runtime$$anon$2.unsafeRunAsync(Runtime.scala:225)
	at zio.Runtime.unsafeRunSync(Runtime.scala:80)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:77)
	at zio.Runtime$$anon$2.unsafeRunSync(Runtime.scala:225)
	at zio.Runtime.unsafeRun(Runtime.scala:57)
	at zio.Runtime.unsafeRun$(Runtime.scala:56)
	at zio.Runtime$$anon$2.unsafeRun(Runtime.scala:225)
	at zio.Runtime$.unsafeFromLayer(Runtime.scala:249)
	at zio.interop.catzQueueSpec$.spec(catzQueueSpec.scala:68)
	at zio.test.RunnableSpec.main(RunnableSpec.scala:43)
	at zio.test.RunnableSpec.main$(RunnableSpec.scala:41)
	at zio.interop.catzQueueSpec$.main(catzQueueSpec.scala:13)
	at zio.interop.catzQueueSpec.main(catzQueueSpec.scala)
```

**Comment by neko-kai** [comment]
A global shutdownHook won't work. Not only this won't work on JS, it also doesn't work in sbt (https://github.com/sbt/sbt/issues/4794)

**Comment by adamgfraser** [comment]
Yes, I think we should probably just remove it and say that on ScalaJS the caller is responsible for shutting down the managed runtime. I don't think there is a way to support this in ScalaJS. I can fix.
