### ISSUE TITLE
ZIO Test: surpress fiber failures

### ISSUE THREAD

**Issue by ioleo** [zio/zio#3121]
Currently when running ZIO's tests we're seeing fiber failure traces printed in between suites, even though all tests succeed.

```[info] + TSemaphore
[info]   + factories
[info]     + make
[info]   + acquire and release
[info]     + acquiring and releasing a permit should not change the availability
[info]     + used capacity must be equal to the # of acquires minus # of releases
[info]     + acquireN/releaseN(n) is acquire/release repeated N times
[info]     + withPermit automatically acquires and releases a permit once an action completes
[info] Ran 5 tests in 1 s 93 ms: 5 succeeded, 0 ignored, 0 failed

#44196 (88ms) waiting on #44189
   Status: Suspended(interruptible, 0 asyncs, zio.Promise.await(Promise.scala:50))
Fiber:Id(1584107208852,44196) was supposed to continue to:
  a future continuation at zio.ZIO$._IdentityFn(ZIO.scala:3224)
  a future continuation at zio.ZIO.onInterrupt(ZIO.scala:902)
  | => zio.StackTracesSpec 5s
Fiber:Id(1584107208852,44196) execution trace:
  at zio.Promise.await(Promise.scala:50)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2193)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2193)

Fiber:Id(1584107208852,44196) was spawned by:

Fiber:Id(1584107208845,44189) was supposed to continue to:
  a future continuation at zio.RTSSpec$.spec(RTSSpec.scala:63)
  a future continuation at zio.test.package$ZTest$.apply(package.scala:104)
  a future continuation at zio.ZIO.run(ZIO.scala:1450)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:244)
  a future continuation at zio.ZIO$.zio$ZIO$$_succeedRight(ZIO.scala:3358)

Fiber:Id(1584107208845,44189) execution trace:
  at zio.RTSSpec$.spec(RTSSpec.scala:62)
  at zio.Promise$.makeAs(Promise.scala:243)
  at zio.Promise$.make(Promise.scala:236)
  at zio.ZIO$.fiberId(ZIO.scala:2305)
  at zio.ZIO$.descriptor(ZIO.scala:2089)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2260)
  at zio.ZIO.bracket_(ZIO.scala:244)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:523)

Fiber:Id(1584107208845,44189) was spawned by:

Fiber:Id(1584107208844,44186) was supposed to continue to:
  a future continuation at zio.ZIO.forkDaemon(ZIO.scala:693)
  a future continuation at zio.ZIO.disconnect(ZIO.scala:433)
  a future continuation at zio.ZIO.timeout(ZIO.scala:1619)
  a future continuation at zio.ZIO.run(ZIO.scala:1450)

Fiber:Id(1584107208844,44186) execution trace:
  at zio.ZIO.disconnect(ZIO.scala:432)
  at zio.ZIO$.fiberId(ZIO.scala:2305)
  at zio.ZIO$.descriptor(ZIO.scala:2089)

Fiber:Id(1584107208844,44186) was spawned by:

Fiber:Id(1584107208790,43988) was supposed to continue to:
  a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:1274)
  a future continuation at zio.ZIO.raceFirst(ZIO.scala:1228)
  a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:1274)
  a future continuation at zio.test.TestAspect$$anon$23.perTest(TestAspect.scala:661)
  a future continuation at zio.ZIO.run(ZIO.scala:1450)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:244)
  a future continuation at zio.test.package$Annotations$$anon$1.withAnnotation(package.scala:504)
  a future continuation at zio.ZIO.run(ZIO.scala:1450)
  a future continuation at zio.ZIO$BracketRelease_.apply(ZIO.scala:3310)
  a future continuation at zio.FiberRef.locally(FiberRef.scala:92)

Fiber:Id(1584107208790,43988) execution trace:
  at zio.ZIO.race(ZIO.scala:1155)
  at zio.ZIO$.fiberId(ZIO.scala:2305)
  at zio.ZIO$.descriptor(ZIO.scala:2089)
  at zio.ZIO.bracket_(ZIO.scala:244)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:523)
  at zio.test.environment.package$Live$.live(package.scala:164)
  at zio.test.environment.package$Live$.withLive(package.scala:174)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:3338)
  at zio.ZIO$BracketRelease_.apply(ZIO.scala:3310)
  at zio.FiberRef.locally(FiberRef.scala:91)

Fiber:Id(1584107208790,43988) was spawned by:

Fiber:Id(1584107208651,43473) was supposed to continue to:
  a future continuation at zio.ZIO.zipWith(ZIO.scala:1831)
  a future continuation at zio.ZIO$.foreach(ZIO.scala:2364)
  a future continuation at zio.ZIO$.foreach(ZIO.scala:2364)
  a future continuation at zio.ZIO$.foreach(ZIO.scala:2364)
  a future continuation at zio.ZIO$.foreachParN(ZIO.scala:2535)
  a future continuation at zio.ZIO.run(ZIO.scala:1450)
  a future continuation at zio.ZIO$.foreachParN(ZIO.scala:2528)
  a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:1274)
  a future continuation at zio.test.Spec.foldM(Spec.scala:197)

Fiber:Id(1584107208651,43473) execution trace:
  at zio.ZIO.zipWith(ZIO.scala:1831)
  at zio.ZIO.zipWith(ZIO.scala:1831)
  at zio.ZIO.zipWith(ZIO.scala:1831)
  at zio.ZIO$.foreachParN(ZIO.scala:2532)
  at zio.ZIO$.foreachParN(ZIO.scala:2531)
  at zio.ZIO$.foreach(ZIO.scala:2364)
  at zio.ZIO$.foreach(ZIO.scala:2364)
  at zio.ZIO$.foreach(ZIO.scala:2364)
  at zio.ZIO$.foreach(ZIO.scala:2364)
  at zio.ZIO$.foreach(ZIO.scala:2364)

Fiber:Id(1584107208651,43473) was spawned by: <empty trace>

Fiber failed.
An interrupt was produced by #44616.
No ZIO Trace available.
[info] + OneShotSpec
[info]   + OneShotSpec
[info]     + Make a new OneShot
[info]       + set must accept a non-null value
[info]       + set must not accept a null value
[info]       + isSet must report if a value is set
[info]       + get must fail if no value is set
[info]       + cannot set value twice
[info] Ran 5 tests in 10 s 237 ms: 5 succeeded, 0 ignored, 0 failed
```

**Comment by adamgfraser** [comment]
I will take a look at this. I'm not sure we should suppress fiber failures as much as understand why fiber failures are being logged in general. For example in the code above it looks like the fiber failure was an interruption which shouldn't normally be logged in production or test environments.
