### ISSUE TITLE
ZIO Macros: Fails with method with type parameter

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3165]
Given the following module:
```
@accessible
object Vertx {
  type VertxService = Has[Vertx.Service]
  type Address = String

  trait Service {
    def subscribe[T](address: Address, onMessage: Message[T] => Task[Unit]): Task[MessageConsumer[T]]
  }
}
```

It will fail to compile with the following error:
```
exception during macro expansion:
[error] scala.reflect.macros.TypecheckException: not found: type T
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:38)
[error] 	at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:37)
[error] 	at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:51)
[error] 	at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:32)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] 	at zio.macros.AccessibleMacro$typeInfo$1$.unapply(AccessibleMacro.scala:54)
[error] 	at zio.macros.AccessibleMacro$$anonfun$2.applyOrElse(AccessibleMacro.scala:98)
[error] 	at zio.macros.AccessibleMacro$$anonfun$2.applyOrElse(AccessibleMacro.scala:97)
[error] 	at scala.collection.immutable.List.collect(List.scala:316)
[error] 	at zio.macros.AccessibleMacro.apply(AccessibleMacro.scala:97)
```

**Comment by nadenf** [comment]
@ioleo .. Not working for me. I did just cherry-pick your fix into the latest ZIO master.

Original code:
```
@accessible
object Zendesk {
  type Zendesk = Has[Zendesk.Service]

  trait Service {
    def getSearchResults[T <: SearchResultEntity](cls: Class[T], query: String): IO[ZendeskError, List[T]]
  }
}
```

Error:
```
[error]  found   : zio.IO[com.harana.modules.zendesk.models.ZendeskError,List[T]]
[error]     (which expands to)  zio.ZIO[Any,com.harana.modules.zendesk.models.ZendeskError,List[T]]
[error]  required: zio.ZIO[zio.Has[com.harana.modules.zendesk.Zendesk.Service] with Any,com.harana.modules.zendesk.models.ZendeskError,com.harana.modules.zendesk.models.ZendeskError]
```

**Comment by ioleo** [comment]
Thanks. Looking into it.

**Comment by ioleo** [comment]
@nadenf Judging by the error message I'd say you've got your type annotation wrong somewhere. Basically, the accessors add `Has[Service]` to your `R` environment. Check the updated examples in the PR.

**Comment by nadenf** [comment]
@jdegoes .. I don't think this should be closed yet.

@ioleo .. If you look at what it says is required:

```
ZIO[zio.Has[com.harana.modules.zendesk.Zendesk.Service] with Any,com.harana.modules.zendesk.models.ZendeskError,com.harana.modules.zendesk.models.ZendeskError]
```

Notice how ZendeskError is in both E and A "slots" ?

**Comment by ioleo** [comment]
@nadenf You're right, I missed that and the examples I added were not sufficient to catch that, I'll have it fixed soon. Thanks!

**Comment by ioleo** [comment]
@nadenf Updated the examples to catch this error and fixed the logic. Thanks again for reporting! :pray:

**Comment by nadenf** [comment]
@ioleo @jdegoes  .. Looks great. Thanks for the amazing turnaround time !
