### ISSUE TITLE
ZIO Test: More precise test selection?

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3331]
Right now the `-t` flag is a contains match. This is convenient and works in the common case, but I wonder if we need an additional option. For example, consider this case:

```scala
suite("ParserSpec")(
  suite("JSON")(
    test("parse correctly") {
      ...
    },
    test("parse correctly from file") {
      ...
    },
    test("something else") {
      ...
    }
  ),
  suite("YAML")(
    test("parse correctly") {
      ...
    }
  )
)
```

If you run `testOnly *.ParserSpec -- -t "parse correctly"` 3 tests are going to run.

There are cases where you want precise matching (for example, when using this with a tool like @hmemcpy is with IntelliJ).

I'm not sure what a good solution to this would be though. An `--exact` flag or something only solves it partially (the nested suite case would still an issue). I think you'd need some sort of path matching that is level aware to solve this 100%. But maybe there are other ideas I haven't yet considered.

**Comment by adamgfraser** [comment]
I think you would have to specify a path. Like "JSON" "parseCorrectly" and then we would first find the matching suite and then look for a match for the next term within its children and so on.

**Comment by hmemcpy** [comment]
In these cases, I always delegate to the "established" norms, aka WWSD ([what would sbt do](https://www.scala-sbt.org/1.x/docs/Testing.html)). I think the default should be an exact match, with possible wildcard support.

**Comment by reibitto** [comment]
I originally based this feature on scalatest's `-z` flag which is also a contains match. I think it sort of makes sense as a default because labels can get quite long (depending on how you name your tests). It's easier to just type a phrase that is contained in it.

A new option for path matching sounds alright to me though. That could be stricter.

**Comment by reibitto** [comment]
But I see your point that adding asterisks on both sides is not much extra typing.

**Comment by vasilmkd** [comment]
Can anyone confirm if there's an issue with `coreTestsJS/testOnly zio.ZIOSpec -- -t "blah"` failing with the following trace:
```
[error] org.scalajs.testcommon.RPCCore$RPCException: java.lang.UnsupportedOperationException: blah
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:79)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:77)
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:57)
[error]         at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:60)
[error]         at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:57)
[error]         at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:34)
[error] Caused by: java.lang.UnsupportedOperationException: blah
[error]         at java.lang.UnsupportedOperationException.fillInStackTrace(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:49523)
[error]         at java.lang.UnsupportedOperationException.<init>(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:49647)
[error]         at java.lang.UnsupportedOperationException.<init>(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:170727)
[error]         at com.novocode.junit.JUnitFramework.parseRunSettings(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:34427)
[error]         at com.novocode.junit.JUnitFramework.runner(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:34470)
[error]         at com.novocode.junit.JUnitFramework.runner(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:34375)
[error]         at <jscode>.{anonymous}()(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:12611)
[error]         at scala.scalajs.runtime.AnonFunction1.apply(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:74691)
[error]         at <jscode>.{anonymous}()(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:11082)
[error]         at scala.scalajs.runtime.AnonFunction1.apply(/Users/vasil/Code/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:74691)
[error] (coreTestsJS / Test / testOnly) org.scalajs.testcommon.RPCCore$RPCException: java.lang.UnsupportedOperationException: blah
```

**Comment by hearnadam** [comment]
Is this still an issue? Feel free to reopen if so.

**Comment by reibitto** [comment]
This issue isn't resolved as far as I can tell, but also I never really proposed a workable solution back when I wrote this.

This actually overlaps with #3226 (as far as what it seeks to achieve) and there's more demand for that feature so I'm fine with closing discussion on this issue for the `TestAspect.only` feature. Since that one is an actual concrete solution.
