### ISSUE TITLE
ClassTag on Chunk is having issue in ScalaJS

### ISSUE THREAD

**Issue by ahoy-jon** [zio/zio#3360]
while working on #3358, found a bug on the master.

To reproduce : 
```scala
zio.test.test("0 to 128") {
      (1 to 128).foldLeft(Chunk(1))(_ + _).materialize
      assertCompletes
    }
```
The error:
```scala
[info] ZIO Test
[info] - ChunkSpec
[info]   - 0 to 128
[info]     Fiber failed.
[info]     An unchecked error was produced.
[info]     scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: 128 is not an instance of java.lang.Byte
[info]       at scala.scalajs.runtime.UndefinedBehaviorError.fillInStackTrace(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:49052:14)
[info]       at scala.scalajs.runtime.UndefinedBehaviorError.fillInStackTrace(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:197175:67)
[info]       at scala.scalajs.runtime.UndefinedBehaviorError.<init>(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:49176:10)
[info]       at scala.scalajs.runtime.UndefinedBehaviorError.<init>(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:197182:58)
[info]       at scala.scalajs.runtime.UndefinedBehaviorError.<init>(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:197178:67)
[info]       at $throwClassCastException(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:217:46)
[info]       at $asByte(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:650:5)
[info]       at $uB(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:689:10)
[info]       at scala.runtime.ScalaRunTime$.array$undupdate(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:33744:17)
[info]       at zio.Chunk$Singleton.toArray(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:222574:25)
[info]     Caused by: java.lang.ClassCastException: 128 is not an instance of java.lang.Byte
[info]       at java.lang.ClassCastException.fillInStackTrace(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:49052:14)
[info]       at java.lang.ClassCastException.<init>(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:49176:10)
[info]       at java.lang.ClassCastException.<init>(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:171184:58)
[info]       at $throwClassCastException(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:218:36)
[info]       at $asByte(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:650:5)
[info]       at $uB(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:689:10)
[info]       at scala.runtime.ScalaRunTime$.array$undupdate(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:33744:17)
[info]       at zio.Chunk$Singleton.toArray(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:222574:25)
[info]       at zio.Chunk$Concat.toArray(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:222205:12)
[info]       at zio.Chunk.toArray(/Users/jon/Projects/zio/core-tests/js/target/scala-2.12/core-tests-test-fastopt.js:216701:9)
[info]     
[info]     Fiber:Id(1586828934537,12975) was supposed to continue to: <empty trace>
[info]     
[info]     Fiber:Id(1586828934537,12975) ZIO Execution trace: <empty trace>
[info]     
[info]     Fiber:Id(1586828934537,12975) was spawned by: <empty trace>
[info] Done
[error] Failed: Total 64, Failed 1, Errors 0, Passed 63, Ignored 2
[error] Failed tests:
[error]         zio.ChunkSpec

```

using 
```
sbt> coreTestsJS/testOnly *.ChunkSpec
```

**Comment by adamgfraser** [comment]
Yes, I noticed the same thing. I think the issue is that there is no underlying representation of these types on ScalaJS, so `1` is a valid `Int`,`Byte`, and so on. We end up casting to the first value that the number "fits into"`, which can be the wrong one. I think the way we need to address it just remove the `Tag.fromValue` machinery on ScalaJS altogether and just treat everything as `Any` internally.

**Comment by jdegoes** [comment]
To fix this, on Scala.js specifically, we can ignore class tags entirely and just use `Array[Any]`.

**Comment by vasilmkd** [comment]
Treating everything as `Any` inside the chunk will lead to boxing.

**Comment by jdegoes** [comment]
Possibly we could differentiate between "number" and "not number".

**Comment by vasilmkd** [comment]
I was interested to look into this but I was missing a nice reproduction. I'll check it out, see what I can come up with.

**Comment by TobiasPfeifer** [comment]
discovered the same issue for `zio.Chunk$PrependN.toArray` in #3914 on master
can be reproduced with https://github.com/zio/zio/pull/3914/commits/73f14a989b98d15369cd9e389f6453f253153133 with ScalaJs 2.13, jdk8 (see https://app.circleci.com/pipelines/github/zio/zio/8228/workflows/25f29f1e-ed92-46e4-9987-76113cf7d47a/jobs/83141/steps)

#3418 does not fix this one

```scala
        testM("preserves data")(checkM(Gen.chunkOf(Gen.anyInt.filter(_ != 0))) { ints =>
          val splitSequence: Chunk[Int] = Chunk(0, 1)
          val data: Chunk[Int]          = ints.flatMap((i: Int) => i +: splitSequence)
          val parser                    = ZTransducer.splitOnChunk[Int, Chunk[Int]](splitSequence, identity)
          assertM(run(parser, List(data)).map(_.flatten))(equalTo(ints))
        })
```

```
[info]         Fiber failed.
[info]         An unchecked error was produced.
[info]         org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.ClassCastException: -246096894 is not an instance of java.lang.Byte
[info]           at $c_jl_Throwable(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:39949:5)
[info]           at $c_jl_Error(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:63107:1)
[info]           at $c_jl_VirtualMachineError(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:77047:1)
[info]           at $c_Lorg_scalajs_linker_runtime_UndefinedBehaviorError(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:96837:5)
[info]           at $throwClassCastException(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:27:9)
[info]           at $uB(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:378:52)
[info]           at scala.runtime.ScalaRunTime$.array_update(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:15165:19)
[info]           at scala.Array$.slowcopy(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:48189:27)
[info]           at scala.Array$.copy(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:48235:7)
[info]           at zio.Chunk$PrependN.toArray(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:209348:19)
[info]         Caused by: java.lang.ClassCastException: -246096894 is not an instance of java.lang.Byte
[info]           at $c_jl_Throwable(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:39949:5)
[info]           at $c_jl_Exception(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:63140:1)
[info]           at $c_jl_RuntimeException(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:76701:1)
[info]           at $c_jl_ClassCastException(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:94786:1)
[info]           at $throwClassCastException(/home/circleci/project/streams-tests/js/target/scala-2.13/streams-tests-test-fastopt.js:27:98)
[info]           ... 5 more
```
