### ISSUE TITLE
Chunk.fromIterable doesn't work with iterables of size > max array size

### ISSUE THREAD

**Issue by iravid** [zio/zio#3449]
```scala
scala> Chunk.fromIterable(Range(1, Int.MaxValue))
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
  at scala.reflect.ManifestFactory$IntManifest.newArray(Manifest.scala:145)
  at scala.reflect.ManifestFactory$IntManifest.newArray(Manifest.scala:143)
  at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:290)
  at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
  at scala.collection.AbstractTraversable.toArray(Traversable.scala:108)
  at zio.Chunk$.fromIterable(Chunk.scala:843)
  ... 26 elided
```

Some possible solutions:
- Split to two arrays
- Convert iterables that aren't Vector/Array to a `scala.collection.mutable.Buffer`

**Comment by tampler** [comment]
This was fixed as per "1.0.0-RC20+50-e27a7ee7-SNAPSHOT"

**Comment by joprice** [comment]
Should that fix be in the latest release? I just tried this on 1.0.0 and got the same error.

**Comment by iravid** [comment]
Sorry @joprice, this was not fixed yet.

**Comment by 987Nabil** [comment]
While the limitation is still there, the issue exists for 5 years and has no interest shown for these 5 years.
If someone has this issue again, please open a new issue
