### ISSUE TITLE
Mocking framework doesn't provide the means to test the absence of method calls

### ISSUE THREAD

**Issue by nartamonov** [zio/zio#3563]
I want to test that `ServiceB` does not call some method of `ServiceA` in specific circumstances. In order to do that I made a mock implementation for `ServiceA` and wrote following test:

```scala
object SampleSpec extends DefaultRunnableSpec {

  val spec = testM("service B does not calls service A if it's not required") {
    val mock = MockServiceA.MethodA.returns(unit).atMost(0)

    assertM(ServiceB.methodB(mustCallA = false))(anything)
      .provideLayer(mock >>> ServiceB.live)
  }

  trait ServiceA {
    def methodA: UIO[Unit]
  }

  trait ServiceB {
    def methodB(mustCallA: Boolean): UIO[Unit]
  }

  object ServiceB {
    def methodB(mustCallA: Boolean): URIO[Has[ServiceB],Unit] =
      ZIO.accessM(_.get.methodB(mustCallA))

    def live: URLayer[Has[ServiceA],Has[ServiceB]] =
      ZLayer.fromService(new ServiceBImpl(_))
  }

  class ServiceBImpl(serviceA: ServiceA) extends ServiceB {
    def methodB(mustCallA: Boolean): UIO[Unit] =
      if (mustCallA)
        serviceA.methodA
      else UIO.unit
  }

  object MockServiceA {
    sealed trait Tag[I,A] extends Method[Has[ServiceA],I,A] {
      def envBuilder: URLayer[Has[mock.Proxy], Has[ServiceA]] = EnvBuilder
    }

    object MethodA extends Tag[Unit,Unit]

    private val EnvBuilder: URLayer[Has[mock.Proxy], Has[ServiceA]] =
      ZLayer.fromService { invoke =>
        new ServiceA {
          def methodA: UIO[Unit] =
            invoke(MethodA)
        }
      }
  }
}
```

zio-test failed to execute test:

```
Fiber failed.
An unchecked error was produced.
java.util.NoSuchElementException: head on empty Range
        at scala.collection.immutable.Range$.scala$collection$immutable$Range$$emptyRangeError(Range.scala:631)
        at scala.collection.immutable.Range.head(Range.scala:126)
        at scala.collection.immutable.Range.min(Range.scala:413)
        at zio.test.FailureRenderer$.loop$4(DefaultTestReporter.scala:449)
        at zio.test.FailureRenderer$.renderUnsatisfiedExpectations(DefaultTestReporter.scala:459)
        at zio.test.FailureRenderer$.renderMockException(DefaultTestReporter.scala:371)
        at zio.test.FailureRenderer$.renderCause(DefaultTestReporter.scala:350)
        at zio.test.DefaultTestReporter$.renderCause(DefaultTestReporter.scala:151)
        at zio.test.DefaultTestReporter$.$anonfun$render$16(DefaultTestReporter.scala:83)
        at zio.test.DefaultTestReporter$$$Lambda$766/0000000000000000.apply(Unknown Source)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:320)
        at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:687)
        at zio.internal.FiberContext$$Lambda$364/0000000000000000.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

It seems that combinator `atMost` doesn't support zero value as argument. As well as `atLeast` and `repeats` combinators.

I think mocking framework should provide some means to test no calls were made.

**Comment by ioleo** [comment]
What you're looking for is a way to express expectation for no calls #3115.
`atMost` was not intented to be called with 0 or negative numbers, although the API does not prevent you from doing that. So there are two problems here:
* the #3115 problem
* dealing with invalid arguments in `atMost`/`atLeast`

**Comment by nartamonov** [comment]
@ioleo yes, #3115 is exactly what I'm looking for! Thanks for pointing to that issue. I'm ok to close this issue as duplicate. Should I open another one for "dealing with invalid arguments in `atMost` / `atLeast`"? It could be solved by documenting the limitation in API docs or by doing `require` checks internally and throwing more user-friendly error. It's a usability issue in a sence. Anyway, it's not a big issue for me and may be it's not worth to do anything with it.

**Comment by ioleo** [comment]
@nartamonov Let's leave it open until the invalid arguments are dealt with. I'm not yet sure which direction should the final solution take.

**Comment by hearnadam** [comment]
ZIO Mock is no longer supported.
