### ISSUE TITLE
ZTransducer.splitLines fails with OutOfMemoryError

### ISSUE THREAD

**Issue by TobiasPfeifer** [zio/zio#3659]
I encounter an `OutOfMemoryError` when using `ZTransducer.splitLines`. However I can read the full file content into a String using Apache Commons `FileUtils.readFileToString`.

I would expect a streaming library to not consume more heap space when processing a file line by line than the file length.
The file has a size of ~107 MB (110,499.590 Bytes) with 1568 lines. The largest line is a String of ~224,000 characters.
JVM InitialHeapSize is set to 512MB, MaxHeapSize to 4GB (shouldn't matter since FileUtils can read the file to String).

```scala
for {
      file <- args.headOption
        .map(filePath => IO(Paths.get(filePath)))
        .getOrElse(IO.fail("No file specified"))

      inputStream <- IO(Files.newInputStream(file))
      //_ <- console.putStrLn("reading file to memory using FileUtils.readFileToString...")
      //s = FileUtils.readFileToString(file.toFile, Charset.forName("UTF-8"))
      //_ <- console.putStrLn(s"lenght of file in memeory: ${s.length}")
      stream = ZStream.fromInputStream(inputStream)
        .transduce(ZTransducer.utf8Decode)
        .transduce[ZEnv, IOException, String](ZTransducer.splitLines)
      _ <- stream.runDrain
} yield ()
```

```
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at zio.stream.ZTransducer$.$anonfun$splitLines$6(ZTransducer.scala:635)
    at zio.stream.ZTransducer$.$anonfun$splitLines$6$adapted(ZTransducer.scala:634)
    at zio.stream.ZTransducer$$$Lambda$205/1628294067.apply(Unknown Source)
    at zio.Chunk$Singleton.foreach(Chunk.scala:1146)
    at zio.Chunk$Concat.foreach(Chunk.scala:1124)
    at zio.stream.ZTransducer$.$anonfun$splitLines$4(ZTransducer.scala:634)
```

I'm willing to fix this bug myself, with some help.
From the implementation I'd suggest to also replace String concat in `ZTransducer.splitLines` with a `StringBuilder` stored as local mutable state. However I'm not sure if there is a restriction on using local state in `ZTransducers`.

**Comment by iravid** [comment]
Hmm interesting. This should definitely not happen. Thank you for reporting.

I somehow doubt replacing the String with a StringBuilder would fix the problem. Here's the implementation of the transducer using a builder; could you try it out and let me know if it changes the memory consumption?
```scala
  val splitLines: ZTransducer[Any, Nothing, String, String] =
    ZTransducer {
      ZRef.makeManaged[(Option[String], Boolean)]((None, false)).map { stateRef =>
        {
          case None =>
            stateRef.getAndSet((None, false)).flatMap {
              case (None, _)      => ZIO.succeedNow(Chunk.empty)
              case (Some(str), _) => ZIO.succeedNow(Chunk(str))
            }

          case Some(strings) =>
            stateRef.modify {
              case (leftover, wasSplitCRLF) =>
                val buf    = mutable.ArrayBuffer[String]()
                var inCRLF = wasSplitCRLF
                var carry  = leftover getOrElse ""

                (Chunk.fromIterable(leftover) ++ strings).foreach { string =>
                  val concat = new StringBuilder(carry)
                  concat ++= string

                  if (concat.length() > 0) {
                    var i =
                      // If we had a split CRLF, we start reading
                      // from the last character of the leftover (which was the '\r')
                      if (inCRLF && carry.length > 0) carry.length - 1
                      // Otherwise we just skip over the entire previous leftover as
                      // it doesn't contain a newline.
                      else carry.length
                    var sliceStart = 0

                    while (i < concat.length()) {
                      if (concat(i) == '\n') {
                        buf += concat.substring(sliceStart, i)
                        i += 1
                        sliceStart = i
                      } else if (concat(i) == '\r' && (i + 1) < concat.length && concat(i + 1) == '\n') {
                        buf += concat.substring(sliceStart, i)
                        i += 2
                        sliceStart = i
                      } else if (concat(i) == '\r' && i == concat.length - 1) {
                        inCRLF = true
                        i += 1
                      } else {
                        i += 1
                      }
                    }

                    carry = concat.substring(sliceStart, concat.length)
                  }
                }

                (Chunk.fromArray(buf.toArray), (if (carry.length() > 0) Some(carry) else None, inCRLF))
            }
        }
      }
    }

```

**Comment by TobiasPfeifer** [comment]
Same Exception. I'll try to reproduce the bug with a file I can share to you

**Comment by TobiasPfeifer** [comment]
added repository to reproduce the bug: https://github.com/TobiasPfeifer/ZStream-splitlines-bug
note: file "input.cap" in resources must be unzipped first

**Comment by iravid** [comment]
Thanks @TobiasPfeifer. Will dig into that soon.

**Comment by iravid** [comment]
@TobiasPfeifer Thank you for providing the sample, super helpful. Fix coming shortly!
