### ISSUE TITLE
Stacktracer loses stack frames

### ISSUE THREAD

**Issue by runtologist** [zio/zio#3719]
Steps to reproduce: 
* set `yieldOpCount` to 1, e.g. by modifying `TestRunner.scala` as follows: 
  ```scala
  platform: Platform = Platform.makeDefault().withReportFailure(_ => ()),
  ===
  platform: Platform = Platform.makeDefault(1).withReportFailure(_ => ()),
  ```
* run `coreTestsJVM/testOnly *StackTracesSpec`

The expected outcome is that tests run slower, but have the same result (and that is the case for all other tests :+1: ). However, for this spec several tests fail: 

```
 - StackTracesSpec
[info]   - fiber ancestry example with uploads
[info]     3 did not satisfy equalTo(4)
[info]   - execution trace example with conditional
[info]     false did not satisfy isTrue()
[info]   - mapError fully preserves previous stack trace
[info]     5 did not satisfy equalTo(6)
[info]     false did not satisfy isTrue()
[info]     false did not satisfy isTrue()
[info]   - catchSome with optimized effect path
[info]     5 did not satisfy equalTo(6)
[info]     false did not satisfy isTrue()
[info]     false did not satisfy isTrue()
[info]     false did not satisfy isTrue()
[info]   - single effect for-comprehension
[info]     2 did not satisfy equalTo(3)
[info]     false did not satisfy isTrue()
```

All affected traces lose the first frame of the stack trace. For example in case of `fiber ancestry example with uploads`:

```
Fiber:Id(1590693150204,8) was supposed to continue to:
  a future continuation at zio.ZIO.tapCause(ZIO.scala:1674)
  a future continuation at zio.ZIO.ensuring(ZIO.scala:546)
  a future continuation at zio.ZIO.unit(ZIO.scala:1836)
```
vs

```
Fiber:Id(1590694227618,8) was supposed to continue to:
  a future continuation at zio.ZIO$.foreachPar(ZIO.scala:2679)
  a future continuation at zio.ZIO.tapCause(ZIO.scala:1674)
  a future continuation at zio.ZIO.ensuring(ZIO.scala:546)
  a future continuation at zio.ZIO.unit(ZIO.scala:1836)
```

**Comment by hearnadam** [comment]
Is this still an issue? Reopen if so.
