### ISSUE TITLE
Update dotty to 0.24.0-RC1

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#3723]
Following https://github.com/zio/izumi-reflect/issues/33, it's time to update to dotty 0.24.0-RC1 & izumi-reflect 1.0.0-M3

**Comment by adamgfraser** [comment]
I'll do this.

**Comment by adamgfraser** [comment]
@neko-kai Hmmm, getting some errors on Dotty regarding tags being available for tuples of concrete types for the mocking package in ZIO Test. Everything works correctly on Scala 2.

```scala
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockRandom.scala:27:76 
[error] 27 |  object NextDoubleBetween extends Effect[(Double, Double), Nothing, Double]
[error]    |                                                                            ^
[error]    |could not find implicit value for izumi.reflect.Tag[(Double, Double)]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (Double, Double)? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(Double, Double)](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(Double, Double)]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(Double, Double)].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockRandom.scala:29:73 
[error] 29 |  object NextFloatBetween  extends Effect[(Float, Float), Nothing, Float]
[error]    |                                                                         ^
[error]    |could not find implicit value for izumi.reflect.Tag[(Float, Float)]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (Float, Float)? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(Float, Float)](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(Float, Float)]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(Float, Float)].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockRandom.scala:32:67 
[error] 32 |  object NextIntBetween    extends Effect[(Int, Int), Nothing, Int]
[error]    |                                                                   ^
[error]    |could not find implicit value for izumi.reflect.Tag[(Int, Int)]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (Int, Int)? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(Int, Int)](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(Int, Int)]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(Int, Int)].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockRandom.scala:35:70 
[error] 35 |  object NextLongBetween   extends Effect[(Long, Long), Nothing, Long]
[error]    |                                                                      ^
[error]    |could not find implicit value for izumi.reflect.Tag[(Long, Long)]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (Long, Long)? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(Long, Long)](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(Long, Long)]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(Long, Long)].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockSystem.scala:25:85 
[error] 25 |  object EnvOrElse        extends Effect[(String, String), SecurityException, String]
[error]    |                                                                                     ^
[error]    |could not find implicit value for izumi.reflect.Tag[(String, String)]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (String, String)? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(String, String)](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(String, String)]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(String, String)].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockSystem.scala:26:101 
[error] 26 |  object EnvOrOption      extends Effect[(String, Option[String]), SecurityException, Option[String]]
[error]    |                                                                                                     ^
[error]    |could not find implicit value for izumi.reflect.Tag[(String, Option[String])]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (String, Option[String])? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(String, Option[String])](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(String, Option[String])]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(String, Option[String])].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockSystem.scala:27:86 
[error] 27 |  object Envs             extends Effect[Unit, SecurityException, Map[String, String]]
[error]    |                                                                                      ^
[error]    |could not find implicit value for izumi.reflect.Tag[Map[String, String]]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in Map[String, String]? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[Map[String, String]](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[Map[String, String]]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[Map[String, String]].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockSystem.scala:28:78 
[error] 28 |  object Properties       extends Effect[Unit, Throwable, Map[String, String]]
[error]    |                                                                              ^
[error]    |could not find implicit value for izumi.reflect.Tag[Map[String, String]]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in Map[String, String]? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[Map[String, String]](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[Map[String, String]]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[Map[String, String]].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockSystem.scala:30:77 
[error] 30 |  object PropertyOrElse   extends Effect[(String, String), Throwable, String]
[error]    |                                                                             ^
[error]    |could not find implicit value for izumi.reflect.Tag[(String, String)]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (String, String)? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(String, String)](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(String, String)]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(String, String)].
[error] -- Error: /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/mock/MockSystem.scala:31:93 
[error] 31 |  object PropertyOrOption extends Effect[(String, Option[String]), Throwable, Option[String]]
[error]    |                                                                                             ^
[error]    |could not find implicit value for izumi.reflect.Tag[(String, Option[String])]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in (String, Option[String])? e.g. def x[T: Tag, F[_]: TagK] = ....
[error]    |I found:
[error]    |
[error]    |    {
[error]    |      izumi.reflect.Tag.apply[(String, Option[String])](classOf[Any], 
[error]    |        {
[error]    |          <empty> :izumi.reflect.macrortti.LightTypeTag
[error]    |        }
[error]    |      ):izumi.reflect.Tag[(String, Option[String])]
[error]    |    }
[error]    |
[error]    |But method tagFromTagMacro in object Tag does not match type izumi.reflect.Tag[(String, Option[String])].
```

**Comment by neko-kai** [comment]
@adamgfraser 
I reproduced that:
```
Error:(12, 10) Exception occurred while executing macro expansion.
java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.ast.tpd$.polyDefDef(tpd.scala:239)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:225)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:222)
	at dotty.tools.dotc.tastyreflect.FromSymbol$.classDef(FromSymbol.scala:33)
	at dotty.tools.dotc.tastyreflect.FromSymbol$.definitionFromSym(FromSymbol.scala:16)
	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.Symbol_tree(ReflectionCompilerInterface.scala:1672)
	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.Symbol_tree(ReflectionCompilerInterface.scala:1671)
	at scala.tasty.Reflection$SymbolOps$.tree(Reflection.scala:2161)
	at izumi.reflect.dottyreflection.Inspector.inspectTType(DbInspector.scala:55)
	at izumi.reflect.dottyreflection.Inspector.inspectTree(DbInspector.scala:121)
	at izumi.reflect.dottyreflection.Inspector.buildTypeRef(DbInspector.scala:42)
	at izumi.reflect.dottyreflection.TypeInspections$.apply(DbInspector.scala:265)
	at izumi.reflect.dottyreflection.Inspect$.inspectAny(DbInspector.scala:21)
  inspect[(Double, Double)]
```
Something happened to Tuple's `ClassDef#tree`. It's either a regression in dotty - could you check if current nightly wokrs? or a more fundamental change to how we should inspect types (e.g. switch from trees to other apis, there were some relevant functions exposed recently), i've added ticket for this at https://github.com/zio/izumi-reflect/issues/38
