### ISSUE TITLE
./sbt issue - java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by myFree** [zio/zio#3948]
I am trying to follow the steps https://github.com/myFree/zio/blob/master/docs/about/contributing.md

After cloning the repo; I'm hitting

```
./sbt 
[info] welcome to sbt 1.3.13 (Ubuntu Java 11.0.7)
[info] loading global plugins from /home/brent/.sbt/1.0/plugins
[info] loading settings for project zio-build from plugins.sbt ...
[info] loading project definition from /home/brent/repos/zio/project
[info] loading settings for project root from build.sbt ...
[info] resolving key references (31663 settings) ...
[error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@3ce53abe rejected from java.util.concurrent.ThreadPoolExecutor@66ed726a[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
```
and the output of last is huge; and ends with

```
[info] resolving key references (31663 settings) ...
[error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@3ce53abe rejected from java.util.concurrent.ThreadPoolExecutor@66ed726a[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
[error] 	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
[error] 	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
[error] 	at org.eclipse.jgit.util.FS$FileStoreAttributes.getFileStoreAttributes(FS.java:329)
[error] 	at org.eclipse.jgit.util.FS$FileStoreAttributes.get(FS.java:296)
[error] 	at org.eclipse.jgit.util.FS.getFileStoreAttributes(FS.java:767)
[error] 	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:224)
[error] 	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:205)
[error] 	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:102)
[error] 	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:209)
[error] 	at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:55)
[error] 	at scalafix.internal.sbt.JGitCompletion.<init>(JGitCompletions.scala:23)
[error] 	at scalafix.internal.sbt.ScalafixCompletions.gitDiffParser$lzycompute(ScalafixCompletions.scala:99)
[error] 	at scalafix.internal.sbt.ScalafixCompletions.gitDiffParser(ScalafixCompletions.scala:98)
[error] 	at scalafix.internal.sbt.ScalafixCompletions.parser(ScalafixCompletions.scala:167)
[error] 	at scalafix.sbt.ScalafixPlugin$.$anonfun$parser$1(ScalafixPlugin.scala:175)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@3ce53abe rejected from java.util.concurrent.ThreadPoolExecutor@66ed726a[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
[error] Use 'last' for the full log.
```

The error is being thrown after 5 seconds or so, so maybe I need to increase a timeout setting somewhere?

**Comment by BananaPlantain** [comment]
Reverting the ScalaFix upgrade seems to resolve the issue on my end

**Comment by myFree** [comment]
++ 
after `git revert a4cadb24d5a6dab1275e0b309d790cb5f341b4f3` I am able to load sbt; thank you for the pointer.

**Comment by myFree** [comment]
Should I close this issue; or should we revert the scalaFix upgrade in master? There are a few others reporting sbt issues in https://discord.com/channels/629491597070827530/629491597070827534

**Comment by ghostdogpr** [comment]
Seems it's failing the CI as well: https://circleci.com/gh/zio/zio/83812?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ghostdogpr** [comment]
There is a v0.9.18-1 that maybe solve this issue: https://github.com/scalacenter/sbt-scalafix/releases/tag/v0.9.18-1
