### ISSUE TITLE
CCE in FiberContext

### ISSUE THREAD

**Issue by iravid** [zio/zio#3977]
Looks like something we've fixed before here: https://github.com/zio/zio/pull/3079/files#diff-b53adcb54f013ee1630f875cdc6d23af

```
[info]         Fiber failed.
 
[info]         An unchecked error was produced.
 
[info]         java.lang.ClassCastException: scala.None$ cannot be cast to scala.Tuple2
 
[info]         	at zio.stream.SinkUtils$$anonfun$zipParLaw$1$$anonfun$apply$8$$anonfun$apply$9.apply(SinkUtils.scala:48)
 
[info]         	at zio.stream.SinkUtils$$anonfun$zipParLaw$1$$anonfun$apply$8$$anonfun$apply$9.apply(SinkUtils.scala:44)
 
[info]         	at zio.ZIO$MapFn.apply(ZIO.scala:3961)
 
[info]         	at zio.ZIO$MapFn.apply(ZIO.scala:3959)
 
[info]         	at zio.internal.FiberContext.nextInstr(FiberContext.scala:895)
 
[info]         	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:389)
 
[info]         	at zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:773)
 
[info]         	at zio.internal.FiberContext$$anonfun$25.run(FiberContext.scala:773)
 
[info]         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 
[info]         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 
[info]         	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jdegoes** [comment]
These type of errors always indicate the stack is wrong.
