### ISSUE TITLE
@accessible can't handle a type alias in a return type

### ISSUE THREAD

**Issue by vsuharnikov** [zio/zio#4099]
## How to reproduce

```scala
// build.sbt
scalaVersion := "2.13.3"
scalacOptions ++= Seq(
  "-Ymacro-annotations",
  "-language:higherKinds"
)
libraryDependencies ++= Seq(
  "dev.zio" %% "zio" % "1.0.0",
  "dev.zio" %% "zio-macros" % "1.0.0"
)

// src/main/scala/bug/Module.scala
package bug

import zio.Task
import zio.macros.accessible

@accessible
object Module {
  type SomeIO[A] = Task[A]
  trait Service {
    def foo(x: Int): SomeIO[Unit]
  }
}
```

The result:
```
[info] Compiling 1 Scala source to accessible-bug/target/scala-2.13/classes ...
[error] accessible-bug/src/main/scala/bug/Module.scala:6:2: exception during macro expansion: 
[error] scala.reflect.macros.TypecheckException: not found: type SomeIO
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:38)
[error] 	at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:37)
[error] 	at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:51)
[error] 	at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:32)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] 	at zio.macros.AccessibleMacro.zio$macros$AccessibleMacro$$typeInfo$1(AccessibleMacro.scala:93)
[error] 	at zio.macros.AccessibleMacro$$anonfun$3.applyOrElse(AccessibleMacro.scala:192)
[error] 	at zio.macros.AccessibleMacro$$anonfun$3.applyOrElse(AccessibleMacro.scala:190)
[error] 	at scala.collection.immutable.List.collect(List.scala:267)
[error] 	at zio.macros.AccessibleMacro.apply(AccessibleMacro.scala:190)
[error] @accessible
[error]  ^
[error] one error found
```

If I replace:
```scala
def foo(x: Int): SomeIO[Unit]
```
by:
```scala
def foo(x: Int): bug.Module.SomeIO[Unit]
```
I get:
```
[info] Compiling 1 Scala source to accessible-bug/target/scala-2.13/classes ...
[error] ## Exception when compiling 1 sources to accessible-bug/target/scala-2.13/classes
[error] java.lang.StackOverflowError
[error] scala.reflect.api.Trees$Transformer.transformValDefs(Trees.scala:2597)
...
[error] scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] zio.macros.AccessibleMacro.zio$macros$AccessibleMacro$$typeInfo$1(AccessibleMacro.scala:93)
[error] zio.macros.AccessibleMacro$$anonfun$3.applyOrElse(AccessibleMacro.scala:192)
[error] zio.macros.AccessibleMacro$$anonfun$3.applyOrElse(AccessibleMacro.scala:190)
[error] scala.collection.immutable.List.collect(List.scala:267)
[error] zio.macros.AccessibleMacro.apply(AccessibleMacro.scala:190)
...
[error] scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] zio.macros.AccessibleMacro.zio$macros$AccessibleMacro$$typeInfo$1(AccessibleMacro.scala:93)
[error] zio.macros.AccessibleMacro$$anonfun$3.applyOrElse(AccessibleMacro.scala:192)
[error] zio.macros.AccessibleMacro$$anonfun$3.applyOrElse(AccessibleMacro.scala:190)
[error] scala.collection.immutable.List.collect(List.scala:267)
[error] zio.macros.AccessibleMacro.apply(AccessibleMacro.scala:190)
...
```

**Comment by hearnadam** [comment]
Do you still run into this issue? I think macro annotations aren't supported in Scala 3 if I remember correctly - we may not pursue a fix. Reopen if so.
