### ISSUE TITLE
ZLayer constructed with `>+>` takes exponential time to build

### ISSUE THREAD

**Issue by Nekdo** [zio/zio#4126]
zio 1.0.1

When a layer is defined like `l1 >+> l2 >+> ...` the time to build the resulting layer seems to be exponential to the number of layers chained together.
Having 25 layers chained causes the build time to be in seconds (see the following test case).

It would be nice, if the time is linear to the number of layers.
Or at least have some warning in the scaladoc.

When I hit this issue, one thread seemed to be running forever. 
This was the thread dump of the tread:

```
"zio-default-async-1-628148496" - Thread t@21
   java.lang.Thread.State: RUNNABLE
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$Fold.hashCode(ZLayer.scala:293)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:64)
        at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:211)
        at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:168)
        at zio.ZLayer$ZipWithPar.hashCode(ZLayer.scala:301)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.collection.immutable.HashMap.elemHashCode(HashMap.scala:80)
        at scala.collection.immutable.HashMap.computeHash(HashMap.scala:89)
        at scala.collection.immutable.HashMap.$plus(HashMap.scala:60)
        at scala.collection.immutable.HashMap.$plus(HashMap.scala:37)
        at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
        at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
        at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
        at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
        at scala.collection.TraversableLike$class.$plus$plus(TraversableLike.scala:147)
        at scala.collection.AbstractTraversable.$plus$plus(Traversable.scala:104)
        at scala.collection.immutable.HashMap.$plus(HashMap.scala:63)
        at scala.collection.immutable.Map$Map4.updated(Map.scala:179)
        at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
        at zio.ZLayer$MemoMap$$anonfun$make$1$$anon$1$$anonfun$getOrElseMemoize$1$$anonfun$apply$513$$anonfun$apply$514$$anonfun$apply$535.apply(ZLayer.scala:2287)
        at zio.ZLayer$MemoMap$$anonfun$make$1$$anon$1$$anonfun$getOrElseMemoize$1$$anonfun$apply$513$$anonfun$apply$514$$anonfun$apply$535.apply(ZLayer.scala:2253)
        at zio.ZIO$MapFn.apply(ZIO.scala:4018)
        at zio.ZIO$MapFn.apply(ZIO.scala:4016)
        at zio.internal.FiberContext.nextInstr(FiberContext.scala:898)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:389)
        at zio.internal.FiberContext.zio$internal$FiberContext$$run$body$1(FiberContext.scala:770)
        at zio.internal.FiberContext$$anonfun$24.run(FiberContext.scala:770)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Test case:

    class L[T](sub: T)
    object L {
      val emptyLayer = ZLayer.succeed(new L(()))
      def partialLayer[T: zio.Tag] = ZLayer.fromService[T, L[T]](new L(_))

      def fullLayer[X](implicit ev: LBuilder[X]): ULayer[Has[X]] = ev.build
    }

    type L0 = L[Unit]

    // 23 layers - build time ~ 1.6 second
    type LMax = L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L0]]]]]]]]]]]]]]]]]]]]]]]
    // 24 layers - build time ~ 3.2 seconds
    // type LMax = L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L[L0]]]]]]]]]]]]]]]]]]]]]]]]

    trait LBuilder[X] {
      def build: ZLayer[Any, Nothing, Has[X]]
    }
    object LBuilder {
      implicit def l0: LBuilder[L0] =
        new LBuilder[L0] { def build = L.emptyLayer }
      implicit def lNext[X: zio.Tag](implicit ev: LBuilder[X]): LBuilder[L[X]] =
        new LBuilder[L[X]] {
          def build: ZLayer[Any, Nothing, Has[L[X]]] = (ev.build >+> L.partialLayer[X]).map(identity)
        }
    }

    val layer = L.fullLayer[LMax]

    ZIO.access[Has[LMax]](
      assert(_)(not(isNull))
    ).provideLayer(layer)

**Comment by adamgfraser** [comment]
@Nekdo Thanks for reporting! Will spend some time thinking about this.

**Comment by bjarkevad** [comment]
After a refactor of how we construct layers, our app never finishes constructing layers. This is with 44 top-level layers.

**Comment by adamgfraser** [comment]
@bjarkevad That is a lot of layers! Okay, I will prioritize this one.

**Comment by bjarkevad** [comment]
It's a lot of layers indeed, probably even too many. Irregardless, this issue came as a surprise :) 
Thank you for prioritizing, let me know if you need me to test a PR.

**Comment by neko-kai** [comment]
@bjarkevad 
Your app should assemble successfully if you replace `>+>` with distage's layer support([[1]](https://izumi.7mind.io/distage/basics#zio-has-bindings)). There's also a library `chopsticks` built on top of distage that provides a nicer syntax for layers[[2]](https://github.com/shopstic/chopsticks/blob/master/chopsticks-fp/src/main/scala/dev/chopsticks/fp/DiLayers.scala)[[3]](https://github.com/shopstic/chopsticks/blob/master/chopsticks-fp/src/main/scala/dev/chopsticks/fp/DiEnv.scala) - using or copying these classes will allow you to use distage's layer engine without having to specify the return type of each layer and more easily adapt your code (e.g. [[4]](https://github.com/shopstic/chopsticks/blob/3fe321e23900be0cfd32c959563b330c00c5902f/chopsticks-fp/src/main/scala/dev/chopsticks/fp/AkkaDiApp.scala#L92))

**Comment by adamgfraser** [comment]
@bjarkevad Just opened a PR to fix this. If you could try it out and let me know if it resolves your issue would be very appreciative!

**Comment by bjarkevad** [comment]
I just tried `1.0.1+86-1774c8e3-SNAPSHOT`, and the problem is indeed fixed! :partying_face: Thanks a bunch!

**Comment by bjarkevad** [comment]
> @bjarkevad
> Your app should assemble successfully if you replace `>+>` with distage's layer support([[1]](https://izumi.7mind.io/distage/basics#zio-has-bindings)). There's also a library `chopsticks` built on top of distage that provides a nicer syntax for layers & better integration with ZIO[[2]](https://github.com/shopstic/chopsticks/blob/master/chopsticks-fp/src/main/scala/dev/chopsticks/fp/DiLayers.scala?rgh-link-date=2020-09-29T15%3A30%3A33Z)[[3]](https://github.com/shopstic/chopsticks/blob/master/chopsticks-fp/src/main/scala/dev/chopsticks/fp/DiEnv.scala?rgh-link-date=2020-09-29T15%3A30%3A33Z) - using or copying these classes will allow you to use distage's layer engine without having to specify the return type of each layer and more easily adapt your code (e.g. [[4]](https://github.com/shopstic/chopsticks/blob/3fe321e23900be0cfd32c959563b330c00c5902f/chopsticks-fp/src/main/scala/dev/chopsticks/fp/AkkaDiApp.scala#L92))

Thanks for the tip, I'll check out distage and chopsticks!
