### ISSUE TITLE
ClassCastException when calling ZStream.fromIterable provided with an Array[Any]

### ISSUE THREAD

**Issue by FrancisToth** [zio/zio#4288]
I came upon an exception while calling `ZStream.fromIterable` and providing it with an `Array[Any]`:
```scala
object TestFromIterable extends App {
  import zio.stream._
  
  val as: Array[Any] = Array(1, "test")
  val runtime = zio.Runtime.default
  runtime.unsafeRun(ZStream.fromIterable(as).run(ZSink.collectAll))
}
```

```console
Fiber failed.
An unchecked error was produced.
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
    at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:76)
    at scala.Array$.slowcopy(Array.scala:72)
    at scala.Array$.copy(Array.scala:98)
    at scala.collection.mutable.ArraySeq.copyToArray(ArraySeq.scala:82)
    at scala.collection.mutable.ArraySeq.copyToArray(ArraySeq.scala:77)
    at scala.collection.IterableOnceOps.toArray(IterableOnce.scala:1286)
    at scala.collection.IterableOnceOps.toArray$(IterableOnce.scala:1283)
    at scala.collection.AbstractIterable.toArray(Iterable.scala:920)
    at zio.Chunk$.fromIterable(Chunk.scala:1178)
```
I believe the problem comes from here (Chunk.scala::1170):
```scala
  def fromIterable[A](it: Iterable[A]): Chunk[A] =
    it match {
      // ...
      case iterable =>
        val first                   = iterable.head
        implicit val A: ClassTag[A] = Tags.fromValue(first)
        fromArray(it.toArray)
    }
```
In the case of an Array containing different types of objects, we would get a ClassCastException.

**Comment by runtologist** [comment]
The problem is not specific to `Array`, but happens for any `Iterable[Any]`, if the first element is a (possibly boxed) primitive type:

```scala
    zio.test.test("fromIterable[Any], first element primitive") {
      val it: Iterable[Any] = Seq(0, "", None)
      assert(Chunk.fromIterable(it))(hasSameElements(it))
    } @@ TestAspect.failing,
    zio.test.test("fromIterable[Any], first element object type") {
      val it: Iterable[Any] = Seq(None, 0, "")
      assert(Chunk.fromIterable(it))(hasSameElements(it))
    }
```

I see only two options for fixing this:
1. Do `Tags.fromValue` for each element of `it`, which would be super inefficient, or 
2. Require an implicit `ClassTag`, which would break binary compatibility.

**Comment by adamgfraser** [comment]
I think we can modify the `ChunkBuilder` to try to construct the `Chunk` and if it fails with a `ClassCastException` fall back to building a `Chunk` backed by an `AnyRef` array. Will work on this.
