### ISSUE TITLE
Defect in zio.Has: N statically known to be contained within the environment are missing

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#4340]
Hi

just bumped into an error:

```scala
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Set(SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]) statically known to be contained within the environment are missing
  at zio.Has$HasSyntax$.prune$extension(Has.scala:197)
  at zio.Has$HasSyntax$.union$extension(Has.scala:209)
...
```

I can see there was a [similar issue](https://github.com/zio/zio/issues/3558), but it looks it was fixed.

Got the error when was trying to build a test with sttp + zio.

_versions:_
```
"dev.zio" %% "zio" % "1.0.3"
"com.softwaremill.sttp.client3" %% "async-http-client-backend-zio" % "3.0.0-RC5" 
```

_code:_

```scala
import sttp.client3._
import sttp.client3.asynchttpclient.zio.stubbing._
import sttp.client3.asynchttpclient.zio.{ send, AsyncHttpClientZioBackend, SttpClient, SttpClientStubbing }
import sttp.model.Uri
import zio.test.Assertion._
import zio.test._
import zio.{ Layer, ZIO }

object SendSpec extends DefaultRunnableSpec {

  private val eventsUri = Uri("https://some-url.org/")
  private val request   = basicRequest.get(eventsUri)

  override def spec: ZSpec[Environment, Failure] =
    suite("SendSpec")(
      testM("can be tested with an sttp stub") {
        val httpEnv: Layer[Throwable, SttpClient with SttpClientStubbing] = AsyncHttpClientZioBackend.stubLayer

        val runEffect: ZIO[SttpClient, Throwable, TestResult] = for {
          res <- send(request)
        } yield assert(res.body)(isRight)

        val stubEffect: ZIO[SttpClientStubbing, Throwable, Unit] = for {
          _ <- whenAnyRequest.thenRespond("RESPONSE")
        } yield ()

        val program: ZIO[SttpClient with SttpClientStubbing, Throwable, TestResult] = stubEffect *> runEffect

        program.provideCustomLayer(httpEnv)
      }
    )
}
```

Setting a breakpoint inside of `Has.prune` ( [val missingServices = set -- self.map.keySet](https://github.com/zio/zio/blob/33f8b4c119cd3cd1ee6533b3bc071612b862e82b/core/shared/src/main/scala/zio/Has.scala#L195) ), gives us:

`missingServices` has size 1 and contains:
```scala
SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]
```

set:
```scala
set = {Set$Set2@3055} "Set$Set2" size = 2
 0 = {LightTypeTag$$anon$1@3063} "package::SttpClientStubbing::Service"
 1 = {LightTypeTag$$anon$1@3064} "SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]"
```

self.map.keySet:
```scala
keySet = {MapOps$ImmutableKeySet@3089} "MapOps$ImmutableKeySet" size = 2
 0 = {LightTypeTag$ParsedLightTypeTag@3087} "package::SttpClientStubbing::Service"
 1 = {LightTypeTag$ParsedLightTypeTag@3088} "SttpBackend[=λ %1:0 → ZIO[-Any,+Throwable,+1:0],+{package::WebSockets & ZioStreams}]"
```

we can see that `SttpBackend` that was not found exists in both sets but slightly different ('%2:0' vs. '%1:0').

Not sure what is wrong.
Any advice is appreciated.

Thank you,
Grigorii

**Comment by gchudnov** [comment]
looks like a binary incompatibility between the sttp 3.0.0-RC5 and zio 1.0.3,
will roll back to zio 1.0.0 for the time being.
closing the issue.
