### ISSUE TITLE
NullPointerException in ZTrace 

### ISSUE THREAD

**Issue by atooni** [zio/zio#4384]
Running an application with ZMX diagnostics enabled and a panopticon instance connected, panopticon regularly executes the dump command on the ZMX server. Non-deterministically, the request fails with:

```
Fiber failed.
An unchecked error was produced.
java.lang.NullPointerException
	at zio.ZTrace.$anonfun$prettyPrint$1(ZTrace.scala:36)
	at scala.collection.immutable.List.map(List.scala:246)
	at zio.ZTrace.prettyPrint(ZTrace.scala:36)
	at zio.internal.FiberRenderer$.$anonfun$prettyPrint$5(FiberRenderer.scala:52)
	at scala.Option.fold(Option.scala:263)
	at zio.internal.FiberRenderer$.prettyPrint(FiberRenderer.scala:52)
	at zio.internal.FiberRenderer$.$anonfun$prettyPrintM$1(FiberRenderer.scala:20)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:344)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:778)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by hearnadam** [comment]
Is this still an issue with 2.x? Reopen if so.
