### ISSUE TITLE
Issue with ZLayer/Has on Scala 3

### ISSUE THREAD

**Issue by vigoo** [zio/zio#4564]
This issue came up while trying to compile zio-logging for Scala 3.0.0-M3. 
Small test to reproduce:

```scala
testM("reproduce zio-logging issue") {
        trait Svc[A]
        def testBaseLayer[R, A : Tag]: ZLayer[R, Nothing, Has[Svc[A]]] = ZIO.access[R](env => new Svc[A] {}).toLayer[Svc[A]]
        def testSecondLayer[A : Tag]: ZLayer[Has[Svc[A]], Nothing, Has[Svc[A]]] = ZLayer.fromFunction[Has[Svc[A]], Svc[A]] { s =>
          s.get
        }

        val layer = testBaseLayer[Any, String] >>> testSecondLayer[String]
        assertM(ZIO.unit.provideCustomLayer(layer))(equalTo(()))
      }
```

fails with

```
[info]     java.lang.Error: Defect in zio.Has: Set(package$::ZSpec[-Has[=Any],+Any]::_$Svc[=String]) statically known to be contained within the environment are missing
[info]     	at zio.Has$HasSyntax$.prune$extension(Has.scala:198)
[info]     	at zio.Has$HasSyntax$.union$extension(Has.scala:210)
[info]     	at zio.Has$$anon$2.union(Has.scala:92)
[info]     	at zio.Has$$anon$2.union(Has.scala:91)
[info]     	at zio.ZLayer.$plus$plus$$anonfun$1(ZLayer.scala:54)
[info]     	at zio.ZManaged.zipWithPar$$anonfun$4$$anonfun$3$$anonfun$3(ZManaged.scala:1139)
[info]     	at zio.ZIO.coordinate$1$$anonfun$1$$anonfun$1(ZIO.scala:2159)
[info]     	at zio.ZIO$MapFn.apply(ZIO.scala:4173)
[info]     	at zio.ZIO$MapFn.apply(ZIO.scala:4172)
[info]     	at zio.internal.FiberContext.nextInstr(FiberContext.scala:914)
[info]     	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:388)
[info]     	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:776)
[info]     	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]     	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]     	at java.base/java.lang.Thread.run(Thread.java:834)
```

Works without problem with 2.13

**Comment by neko-kai** [comment]
@vigoo 
Try changing `testSecondLayer` signature to
```
 def testSecondLayer[A](implicit t: Tag[Has[Svc[A]]): ZLayer[Has[Svc[A]], Nothing, Has[Svc[A]]]
```
See https://github.com/zio/izumi-reflect/issues/103, polymorphic usages of Tags are not implemented yet for Scala 3

**Comment by vigoo** [comment]
Thanks! I was not aware that it's not implemented yet.

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/izumi-reflect/issues/103
