### ISSUE TITLE
Trying to run tests with ZIO 1.0.4.-1 fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio#4643]
When I try running tests on a project that uses ZIO 1.0.4.-1, it fails with
```
java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
	at zio.test.sbt.BaseTestTask.specInstance$lzycompute(BaseTestTask.scala:18)
	at zio.test.sbt.BaseTestTask.specInstance(BaseTestTask.scala:15)
	at zio.test.sbt.BaseTestTask.execute(BaseTestTask.scala:42)
	at sbt.TestRunner.runTest$1(TestFramework.scala:139)
	at sbt.TestRunner.run(TestFramework.scala:154)
	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:317)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)
	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
	at sbt.TestFunction.apply(TestFramework.scala:329)
	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:422)
	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
	at sbt.internal.BottomClassLoader.lambda$findClass$0(BottomClassLoader.java:56)
	at sbt.internal.ClassLoadingLock.withLock(ClassLoadingLock.java:29)
	at sbt.internal.BottomClassLoader.findClass(BottomClassLoader.java:51)
	at sbt.internal.ReverseLookupClassLoader.lambda$findClass$0(ReverseLookupClassLoader.java:130)
	at sbt.internal.ClassLoadingLock.withLock(ClassLoadingLock.java:29)
	at sbt.internal.ReverseLookupClassLoader.findClass(ReverseLookupClassLoader.java:119)
	at sbt.internal.ReverseLookupClassLoader.loadClass(ReverseLookupClassLoader.java:110)
	at sbt.internal.ReverseLookupClassLoader.loadClass(ReverseLookupClassLoader.java:101)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 25 more
[error] Test suite zio.interop.GuavaSpec failed with java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator.
[error] This may be due to the ClassLoaderLayeringStrategy (AllLibraryJars) used by your task.
[error] To improve performance and reduce memory, sbt attempts to cache the class loaders used to load the project dependencies.
[error] The project class files are loaded in a separate class loader that is created for each test run.
[error] The test class loader accesses the project dependency classes using the cached project dependency classloader.
[error] With this approach, class loading may fail under the following conditions:
[error] 
[error]  * Dependencies use reflection to access classes in your project's classpath.
[error]    Java serialization/deserialization may cause this.
[error]  * An open package is accessed across layers. If the project's classes access or extend
[error]    jvm package private classes defined in a project dependency, it may cause an IllegalAccessError
[error]    because the jvm enforces package private at the classloader level.
[error] 
[error] These issues, along with others that were not enumerated above, may be resolved by changing the class loader layering strategy.
[error] The Flat and ScalaLibrary strategies bundle the full project classpath in the same class loader.
[error] To use one of these strategies, set the  ClassLoaderLayeringStrategy key
[error] in your configuration, for example:
[error] 
[error] set guava / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.ScalaLibrary
[error] set guava / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
[error] 
[error] See ClassLoaderLayeringStrategy.scala for the full list of options.
[info] ZIO Test
[info] No tests were executed
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	zio.interop.GuavaSpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 0 s, completed Feb 1, 2021, 5:40:04 PM
```

**Comment by adamgfraser** [comment]
How did this get past CI? Did we not add compiling and testing the `interop` project to CI when we moved it into ZIO Core?
