### ISSUE TITLE
Null layer passed to ZLayer leads to late cryptic errors

### ISSUE THREAD

**Issue by pshirshov** [zio/zio#4729]
I have a small piece of zlayer code. The layers are defined as `val`s, like so:

```scala
  private final val kafkaLayer: Layer[Error, Kafka]                                      = Config.live >>> Kafka.live
  private final val transactorLayer: Layer[Error, DbTransactor]                          = (Blocking.live ++ ConfigDb.live) >>> db.hikariLayer
  private final val queryConfigLayer: Layer[Error, DbConfig with QueryConfig]            = ConfigDb.live
  private final val defaultLayer: Layer[Error, DbTransactor with Kafka with QueryConfig] = transactorLayer ++ queryConfigLayer ++ kafkaLayer

//...

    tamer.kafka.runLoop(setup)(iteration(setup)).provideCustomLayer(defaultLayer)

object Test extends zio.App {
  val program: ZIO[ZEnv, Error, Unit] = (... something.provideCustom(defaultLayer) ... )

  override final def run(args: List[String]): URIO[ZEnv, ExitCode] = program.exitCode
}

```

This app fails to run on Java 15 with a cryptic error message:

```
Fiber failed.
An unchecked error was produced.
java.lang.NullPointerException: Cannot invoke "zio.ZLayer.zio$ZLayer$$isFresh()" because "layer$2" is null
	at zio.ZLayer$MemoMap$$anon$1.$anonfun$getOrElseMemoize$33(ZLayer.scala:2316)
	at zio.ZIO$MapFn.apply(ZIO.scala:4197)
	at zio.ZIO$MapFn.apply(ZIO.scala:4195)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:914)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

It helps to replace `val`s with `lazy val`s.

Apparently something about field initialization in Scala is broken by J15, though **I find the diagnostics unacceptable**. I believe that methods like `ZIO#provideCustomLayer` and composition operators must perform immediate null checks to avoid very late/postponed error detection. Also I think that in general incorrect data passed to ZLayer must lead to useful and helpful diagnostics.

**Comment by adamgfraser** [comment]
@pshirshov I think that makes sense. I can work on this.

**Comment by hearnadam** [comment]
@pshirshov is this still an issue? Please reopen if so.

**Comment by pshirshov** [comment]
It's not an issue for me, because we avoid using ZLayers when possible but I don't know if the issue is still relevant. Probably it is.
