### ISSUE TITLE
`MavenJunitSpec` test fails with scala `2.13.5`

### ISSUE THREAD

**Issue by softinio** [zio/zio#4848]
Following test failng with scala `2.13.5`:

https://github.com/zio/zio/blob/e94be1899eddf43923c979eec2dae78bdd936281/test-junit-tests/jvm/src/test/scala/zio/test/junit/MavenJunitSpec.scala#L17

# Error 

```
[info] - MavenJunitSpec
[info]   - FailingSpec results are properly reported
[info]     Fiber failed.
[info]     A checked error was not handled.
[info]     java.io.FileNotFoundException: /Users/salar/OpenSource/zio/test-junit-tests/maven/target/surefire-reports/TEST-zio.test.junit.maven.FailingSpec.xml (No such file or directory)
[info]     	at java.base/java.io.FileInputStream.open0(Native Method)
[info]     	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
[info]     	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
[info]     	at scala.xml.Source$.fromFile(XML.scala:19)
[info]     	at zio.test.junit.MavenJunitSpec$MavenDriver.$anonfun$parseSurefireReport$1(MavenJunitSpec.scala:83)
[info]     	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
[info]     	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
[info]     	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[info]     	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[info]     	at java.base/java.lang.Thread.run(Thread.java:832)
```

# Steps to reproduce

1. clone repo
2. `sbt ++2.13.5! testJVM`

**Comment by adamgfraser** [comment]
Copying @dkarlinsky.
