### ISSUE TITLE
Better support for Graal native-image `--initialize-at-build-time`

### ISSUE THREAD

**Issue by reibitto** [zio/zio#5004]
When using Graal native-image's `--initialize-at-build-time`, you need to be careful to not accidentally initialize things at build-time, like random seeds, environments variables, etc. This [tweet](https://twitter.com/reibitto/status/1384795560436113415) has a little more context if you need it.

Prior to GraalVM 21.1, using ZIO's `Random` would mean the random number generator's seed will be fixed at build-time. So each time you run your native executable, the same sequence of random numbers will be generated.

With GraalVM 21.1+, you'll get this error instead:

```
[error] Error: Detected an instance of Random/SplittableRandom class in the image heap. Inst
ances created during image generation have cached seed values and don't behave as expected.
 To see how this object got instantiated use --trace-object-instantiation=java.util.Random.
The object was probably created by a class initializer and is reachable from a static field.
 You can request class initialization at image runtime by using the option --initialize-at-r
un-time=<class-name>. Or you can write your own initialization methods and call them explici
tly from your main entry point.
[error] Detailed message:
[error] Trace: Object was reached by
[error]         reading field scala.util.Random.self of
[error]                 constant scala.util.Random$@26683265 reached by
[error]         scanning method zio.random.package$Random$Service$$anon$1.$anonfun$nextInt$1
(package.scala:55)
[error] Call path from entry point to zio.random.package$Random$Service$$anon$1.$anonfun$nex
tInt$1():
[error]         at zio.random.package$Random$Service$$anon$1.$anonfun$nextInt$1(package.scal
a:55)
[error]         at zio.random.package$Random$Service$$anon$1$$Lambda$892/0x00000007c1227040.
apply$mcI$sp(Unknown Source)
[error]         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
[error]         at zio.internal.FiberContext.evaluateNow(FiberContext.scala:398)
[error]         at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
[error]         at zio.internal.FiberContext$$Lambda$798/0x00000007c11f1440.run(Unknown Sour
ce)
[error]         at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:1
25)
[error]         at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport
.java:75)
[error]         at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
[error]         at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[error]         at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc
9a6abc971913ece43acb471d2631b(generated:0)
```

Minimal example (with `--initialize-at-build-time` set):

```scala
object Main extends App {
  def run(args: List[String]): URIO[ZEnv, ExitCode] =
    for {
      n <- random.nextInt
      _ <- putStrLn(n.toString)
    } yield ExitCode.success
}
```

ZIO should be able to avoid this by not using of the `scala.util.Random` singleton object and instead create an instance of it at ZLayer creation with `val random = new Random()`

We should check for similar issues in ZIO's codebase. I'll do a quick check right now. `zio.system.System` is one other potential area of concern, but I need to confirm.

**Comment by reibitto** [comment]
Alright, I checked `zio.system.System` and it looks safe to me. There should be no problems with getting environment variables from it. The only issue I can find is with `Random`

**Comment by adamgfraser** [comment]
@reibitto Great to fix this! The only issue I can think of is that we do expose the live services directly for interoperation with mixed code bases that does not want to have to run a layer to get access to the default services. Not sure exactly how we handle this but should be able to figure something out.

**Comment by reibitto** [comment]
Worst case, you could add a `lazy random = new Random()` in `Random.Service` directly and replace `SRandom` with it, right?

https://github.com/zio/zio/blob/b8880ff5601119d3d452e40497ca579effded4a5/core/shared/src/main/scala/zio/random/package.scala#L50

**Comment by adamgfraser** [comment]
Sure.

**Comment by hearnadam** [comment]
@reibitto is this still an issue?

**Comment by reibitto** [comment]
I think it should be fine to close. The `Random` thing I mentioned in this issue is no longer a problem.

We've been using ZIO + native-image at work for a few years now and I haven't needed to do any specific configuration for ZIO so far. Seems to work fine out of the box.
