### ISSUE TITLE
Error:  statically known to be contained within the environment are missing

### ISSUE THREAD

**Issue by ashwinbhaskar** [zio/zio#5359]
Scala version: 3.0.0
ZIO Version: 1.0.10
Sttp Version: 3.3.12

To reproduce the error:

1. Clone https://github.com/ashwinbhaskar/zio-slack-3.0-test (it's a very small project)
2. Run `sbt run`

A part of the stack trace of the error
```
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Set({{Has[=AccessToken$::Token] & Has[=package$::SlackClient$::Service]} & Has[=package$::SlackRealtimeClient$::Service]}) statically known to be contained within the environment are missing
	at zio.Has$HasSyntax$.prune$extension(Has.scala:198)
	at zio.Has$HasSyntax$.union$extension(Has.scala:210)
	at zio.Has$$anon$2.union(Has.scala:92)
	at zio.Has$$anon$2.union(Has.scala:91)
	at zio.ZLayer.$plus$plus$$anonfun$1(ZLayer.scala:60)
	at zio.ZManaged.zipWithPar$$anonfun$4$$anonfun$3$$anonfun$3(ZManaged.scala:1186)
	at zio.ZIO.coordinate$1$$anonfun$1$$anonfun$1(ZIO.scala:2273)
	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
	at zio.ZIO$MapFn.apply(ZIO.scala:4437)
	at zio.internal.FiberContext.nextInstr(FiberContext.scala:914)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:390)
	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

Note: The repository has unmanaged dependencies. They come from this PR https://github.com/Dapperware/zio-slack/pull/174

**Comment by ashwinbhaskar** [comment]
Tried this with the latest snapshot of ZIO `1.0.10+57-0441752a-SNAPSHOT`. The issue still persists.

**Comment by hearnadam** [comment]
Is this an issue with ZIO 2? Feel free to reopen if so.
