### ISSUE TITLE
Has ++ fails in Scala 3 in a method when inside a container and there is no implicit param of Tag[Has[B]]

### ISSUE THREAD

**Issue by nbenns** [zio/zio#5421]
In Scala `2.13.6` this code will run fine:

```
object Main extends App {
  def combine[A: Tag, B: Tag](za: UIO[Has[A]], zb: UIO[Has[B]]): UIO[Has[A] with Has[B]] =
    za.zip(zb).map { case (a, b) => a ++ b }

  val zint = ZIO.succeed(Has(2))
  val zstr = ZIO.succeed(Has("hi"))

  val zboth = combine(zint, zstr)

  override def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    zboth
      .flatMap(putStrLn(_))
      .exitCode
  }
}
```

If you switch the version of Scala to either `3.0.0` or `3.0.1` then it will compile fine, however it will fail with:
```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Set(_$B|<Nothing..Any>) statically known to be contained within the environment are missing
	at zio.Has$HasSyntax$.prune$extension(Has.scala:193)
	at zio.Has$HasSyntax$.union$extension(Has.scala:205)
	at zio.Has$HasSyntax$.$plus$plus$extension(Has.scala:157)
	at Main$.combine$$anonfun$1(Main.scala:18)
	at zio.ZIO$MapFn.apply(ZIO.scala:5318)
	at zio.ZIO$MapFn.apply(ZIO.scala:5317)
	at zio.internal.FiberContext.nextInstr(FiberContext.scala:1006)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:423)
	at zio.internal.FiberContext.run(FiberContext.scala:305)
	at zio.internal.ZScheduler$$anon$2.run(ZScheduler.scala:149)

Fiber:Id(1629310264581,1) was supposed to continue to:
  a future continuation at Main$.run$$anonfun$1(Main.scala:15)
  a future continuation at zio.ZIO.exitCode$$anonfun$2(ZIO.scala:717)

Fiber:Id(1629310264581,1) execution trace:
  at Main$.combine$$anonfun$1(Main.scala:6)
  at zio.ZIO.$amp$amp$amp$$anonfun$2(ZIO.scala:85)
  at zio.ZIO$.succeed$$anonfun$1(ZIO.scala:4765)
  at zio.ZIO.zipWith$$anonfun$1(ZIO.scala:2464)
  at zio.ZIO$.succeed$$anonfun$1(ZIO.scala:4765)

Fiber:Id(1629310264581,1) was spawned by:

Fiber:Id(1629310264412,0) was supposed to continue to:
  a future continuation at zio.ZApp.6$$anonfun(ZApp.scala:61)
  a future continuation at zio.Runtime.unsafeRunWith$$anonfun$2(Runtime.scala:311)

Fiber:Id(1629310264412,0) ZIO Execution trace: <empty trace>

Fiber:Id(1629310264412,0) was spawned by: <empty trace>

Process finished with exit code 1
```

Changing the combine method:
```
def combine[A: Tag, B: Tag](za: UIO[Has[A]], zb: UIO[Has[B]]): UIO[Has[A] with Has[B]] = {
    val ev = implicitly[Tag[Has[B]]]
    println(ev)
    za.zip(zb).map { case (a, b) => a ++ b }
  }
```

Outputs: `Tag[Has[=_$B|<Nothing..Any>]]`
Showing that an Invalid Tag is being picked up.

Altering the method to:
```
def combine[A: Tag, B: Tag](za: UIO[Has[A]], zb: UIO[Has[B]])(implicit ev: Tag[Has[B]]): UIO[Has[A] with Has[B]] = {
    println(ev)
    za.zip(zb).map { case (a, b) => a ++ b }
  }
```
Shows the tag is now correct and the method works fine:
```
Tag[Has[=String]]
Map(Int -> 2,
String -> hi)

Process finished with exit code 0
```

This has been tested with both ZIO `1.0.10` and `2.0.0-M1` as well as with the latest snapshot versions: `1.0.10+53-3a354737-SNAPSHOT` & `2.0.0-M1+3-9bd6aac6-SNAPSHOT`

Expected behavior:
Depending on whether this behavior is correct for Scala 3, this would not compile unless the `Tag[Has[B]]` was provided, however since it works in Scala 2.13.6 with this behavior it should most likely work.
A `Tag[B]` is already being provided, a `Tag[Has[B]]` should probably be inferable from this.

**Comment by adamgfraser** [comment]
Copying @neko-kai and @pshirshov.

**Comment by nbenns** [comment]
Note I realized you don't need to wrap in the ZIO effect, it still fails as:
```
object Main extends App {
  def combine[A: Tag, B: Tag](ha: Has[A], hb: Has[B]): Has[A] with Has[B] = {
    val ev = implicitly[Tag[Has[B]]]
    println(ev)
    ha ++ hb
  }

  val hint = Has(2)
  val hstr = Has("hi")

  val hboth = combine(hint, hstr)

  override def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    putStrLn(hboth)
      .exitCode
  }
}
```

**Comment by neko-kai** [comment]
@nbenns 
> A Tag[B] is already being provided, a Tag[Has[B]] should probably be inferable from this.

This specific part is not implemented for Scala 3 yet. See https://github.com/zio/izumi-reflect/issues/103

> Tag[Has[=_$B|<Nothing..Any>]]

Arguably we should error at compile time, rather than generate a broken tag, however we currently specifically allow this through to allow signatures in `zio-mock` to compile (they otherwise require to implement tag combining for Scala 3 to work properly) [[1]](https://github.com/zio/izumi-reflect/pull/145/files#diff-5c581e76bb38601cec2f6236b4110b6fb48c82fdc63fe374082a870058248ecdR14)

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/izumi-reflect/issues/103
