### ISSUE TITLE
`Defect in zio.Has: Could not find package`

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio#5530]
`"dev.zio" %% "zio" % "1.0.11"`

`scalaVersion := "3.0.1"`

```scala
  val serviceEnv: ZLayer[Any, Nothing, Has[ReportService]] = {
    val backend = ZLayer.fromEffect(AsyncHttpClientZioBackend()).orDie
    val settings = ZLayer.fromEffect(Settings.load).mapError(new RuntimeException(_)).orDie
    val jiraClient = {
      val jiraSettings = settings.map(x => Has(x.get.jiraSettings))
      val cache = (backend ++ jiraSettings) >>> JiraCache.live
      (jiraSettings ++ cache ++ backend) >>> JIRAClient.live
    }
    val bictbucketClient = {
      val bitbucketSettings = settings.map(x => Has(x.get.bitbucketSettings))
      val driver = (bitbucketSettings ++ backend) >>> BitBucketDriver.live
      (driver ++ bitbucketSettings) >>> BitBucketClient.live
    }    
    (bictbucketClient ++ jiraClient ++ settings ++ backend) >>> Report.live
  }

  val program: ZIO[Has[ReportService], String, Unit] = for {
    stories <- Report.stories(from, to)
    csv = StoryCsv().makeCsv(stories)
    _   = CsvWriter(csv).write(s"$from...$to.csv")
  } yield ()

  override def run(args: List[String]) = program
    .provideLayer(serviceEnv)
    .exitCode
```

```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Could not find package$::URIO[-Any,+Cache[-String,+String,+Option[+Json]]] inside Map(ZIO[-Any,+Nothing,+Cache[-String,+String,+Option[+Json]]] -> zio.ZIO$FlatMap@59442e27)
	at zio.Has$HasSyntax$.get$extension$$anonfun$2$$anonfun$1(Has.scala:181)
	at zio.Has$HasSyntax$$$Lambda$606/0x0000000063977220.apply(Unknown Source)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:228)
	at zio.Has$HasSyntax$.get$extension$$anonfun$1(Has.scala:181)
	at zio.Has$HasSyntax$$$Lambda$537/0x0000000065931220.apply(Unknown Source)
	at scala.collection.immutable.Map$Map1.getOrElse(Map.scala:250)
	at zio.Has$HasSyntax$.get$extension(Has.scala:182)
	at com.bilalfazlani.jiraClient.JiraCache$.$init$$$anonfun$2(JiraCache.scala:59)
	at com.bilalfazlani.jiraClient.JiraCache$$$Lambda$85/0x00000000648ed620.apply(Unknown Source)
	at zio.ZLayer$.fromFunctionMany$$anonfun$1(ZLayer.scala:416)
	at zio.ZLayer$$$Lambda$64/0x00000000638d1020.apply(Unknown Source)
	at zio.ZLayer$.fromFunctionManyM$$anonfun$1(ZLayer.scala:423)
	at zio.ZLayer$$$Lambda$65/0x00000000638d1620.apply(Unknown Source)
	at zio.ZManaged.map$$anonfun$1(ZManaged.scala:475)
	at zio.ZManaged$$Lambda$66/0x00000000638d2620.apply(Unknown Source)
	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
	at zio.ZIO$MapFn.apply(ZIO.scala:4437)
	at zio.internal.FiberContext.nextInstr(FiberContext.scala:914)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:390)
	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:776)
	at zio.internal.FiberContext$$Lambda$317/0x00000000660151b0.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)

Fiber:Id(1630991966030,13) was supposed to continue to:
  a future continuation at zio.ZManaged.flatMap$$anonfun$1(ZManaged.scala:329)
  a future continuation at zio.ZManaged.6$$anonfun(ZManaged.scala:330)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZLayer$.123$$anonfun(ZLayer.scala:2311)
  a future continuation at zio.ZLayer$.124$$anonfun(ZLayer.scala:2327)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZManaged.6$$anonfun(ZManaged.scala:330)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZLayer$.123$$anonfun(ZLayer.scala:2311)
  a future continuation at zio.ZLayer$.124$$anonfun(ZLayer.scala:2327)
  a future continuation at zio.ZManaged.flatMap$$anonfun$1(ZManaged.scala:329)
  a future continuation at zio.ZManaged.6$$anonfun(ZManaged.scala:330)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZLayer$.123$$anonfun(ZLayer.scala:2311)
  a future continuation at zio.ZLayer$.124$$anonfun(ZLayer.scala:2327)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZManaged.6$$anonfun(ZManaged.scala:330)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZLayer$.123$$anonfun(ZLayer.scala:2311)
  a future continuation at zio.ZLayer$.124$$anonfun(ZLayer.scala:2327)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  a future continuation at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  a future continuation at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)

Fiber:Id(1630991966030,13) execution trace:
  at zio.ZManaged.map$$anonfun$1(ZManaged.scala:475)
  at zio.ZManaged$.fromEffect$$anonfun$2(ZManaged.scala:1867)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal$$anonfun$1(ZIO.scala:2791)
  at zio.ZIO$.8$$anonfun(ZIO.scala:2398)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.ZIO$.effectSuspendTotal$$anonfun$1(ZIO.scala:2791)
  at zio.ZIO.bracket_$$anonfun$1(ZIO.scala:288)
  at zio.ZIO.run$$anonfun$2(ZIO.scala:1730)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$AccessPartiallyApplied$.apply$extension$$anonfun$1(ZIO.scala:4392)
  at zio.ZIO$.effectSuspendTotal$$anonfun$1(ZIO.scala:2791)
  at zio.ZIO.bracket_$$anonfun$2(ZIO.scala:288)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.ZIO.provideSome$$anonfun$1(ZIO.scala:1241)
  at zio.ZManaged.flatMap$$anonfun$1(ZManaged.scala:329)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.ZIO$.effectSuspendTotal$$anonfun$1(ZIO.scala:2791)
  at zio.ZIO.bracket_$$anonfun$2(ZIO.scala:288)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.ZLayer$$anon$1.2$$anonfun(ZLayer.scala:2310)
  at zio.ZManaged$ReleaseMap$.make$$anonfun$1(ZManaged.scala:1358)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.ZLayer$$anon$1.3$$anonfun(ZLayer.scala:2307)
  at zio.ZLayer$.108$$anonfun(ZLayer.scala:2307)
  at zio.ZIO$AccessPartiallyApplied$.apply$extension$$anonfun$1(ZIO.scala:4392)
  at zio.ZIO.flatten$$anonfun$1(ZIO.scala:680)
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal$$anonfun$1(ZIO.scala:2791)
```

**Comment by bilal-fazlani** [comment]
am I doing something wrong?

**Comment by adamgfraser** [comment]
@bilal-fazlani Are you using the Scala 3 version of ZIO and not the Scala 2 version in compatibility mode? That is the most frequent cause of issues I have seen here.

**Comment by bilal-fazlani** [comment]
Ok, I see a few zio library versions in vscode

![image](https://user-images.githubusercontent.com/3396271/132449416-03d73f56-7241-4434-9d74-cbda2d6180eb.png)

May be this is the reason. I will check this further and update

**Comment by adamgfraser** [comment]
@bilal-fazlani Thank you! 🙏

**Comment by bilal-fazlani** [comment]
So I cleared all cache. Extracted all dependencies in a file and searched for zio

```
cat deps.txt | grep dev.zio:zio_
```

```
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.9 (evicted by: 1.0.11)
  | | | | | | +-dev.zio:zio_3:1.0.11
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | | | +-dev.zio:zio_3:1.0.11
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.9 (evicted by: 1.0.11)
  +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | +-dev.zio:zio_3:1.0.11
  | +-dev.zio:zio_3:1.0.9 (evicted by: 1.0.11)
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.11
  | | | +-dev.zio:zio_3:1.0.8 (evicted by: 1.0.11)
  | | +-dev.zio:zio_3:1.0.11
  | | +-dev.zio:zio_3:1.0.9 (evicted by: 1.0.11)

```

I seem to have only one version of zio

**Comment by bilal-fazlani** [comment]
The entire programs works as expected if I don't try to consume `Cache` layer.

```scala
val cache = (backend ++ jiraSettings) >>> JiraCache.live
```

```scala
object JiraCache {
  val live = ZLayer.fromServices((a,b) =>
    JiraCache(a, b)
  ).flatMap(z => ZLayer.fromEffect(z.get))

  private def apply(
        settings: JiraSettings,
        backend: SttpBackend[Task, ZioStreams & WebSockets]
    ): URIO[Any, Cache[String, String, Option[Json]]] =
      val lookup = Lookup(x => getStoryJson(x, settings, backend))
      Cache.make(Int.MaxValue, Duration(5, TimeUnit.MINUTES), lookup)
}
```

This doesn't seem like a dependency issue

**Comment by bilal-fazlani** [comment]
I made it work by using 

```scala
val live = ZLayer.fromServicesM((a,b) =>
    JiraCache(a, b)
  )
``` 

instead of 

```scala
val live = ZLayer.fromServices((a,b) =>
    JiraCache(a, b)
  ).flatMap(z => ZLayer.fromEffect(z.get))
```

I was not aware of `.fromServicesM` but if you have any idea, could you please help me understand, why first approach would not work?

**Comment by adamgfraser** [comment]
@bilal-fazlani Both should work.

@neko-kai Could you take a look at this when you get the chance?

**Comment by neko-kai** [comment]
@adamgfraser I would definitely take a look, but so far I can't provide an ETA. Other contributors are welcome to take on this meanwhile.

**Comment by adamgfraser** [comment]
@neko-kai Thanks!

**Comment by quelgar** [comment]
I have another datapoint on this. My error is:

```
java.lang.Error: Defect in zio.Has: Could not find package$::Blocking$::Service inside Map(package$::Console$::Service -> zio.console.package$$anon$1@6a82eead,
package$::Random$::Service -> zio.random.package$$anon$1@7a5f987c,
package$::System$::Service -> zio.system.package$$anon$1@74f75c50,
package$::Blocking$::Service -> zio.blocking.package$$anon$1@35f613eb,
package$::Clock$::Service -> zio.clock.package$$anon$1@487c647e)
	at zio.Has$HasSyntax$.get$extension$$anonfun$2$$anonfun$1(Has.scala:181)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:228)
	at zio.Has$HasSyntax$.get$extension$$anonfun$1(Has.scala:181)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:678)
	at zio.Has$HasSyntax$.get$extension(Has.scala:182)
	at zio.ZIO$.service$$anonfun$1(ZIO.scala:3952)
	at zio.ZIO$AccessPartiallyApplied$.apply$extension$$anonfun$1(ZIO.scala:4392)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:549)
	at zio.internal.FiberContext.fork$$anonfun$3(FiberContext.scala:770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Scala 3.0.2, zio_3 1.0.11, zio-kafka_3 0.16.0. This problem occurs when the zio-kafka producer code tries to access `Blocking` from the environment. I was able to confirm in the debugger that the tag for blocking that the Kafka code generated had a different hash code to the identically named tag in the "type map".

On a hunch I checked which ZIO version zio-kafka 0.16.0 was published with: 1.0.10. **Changing my project to use zio 1.0.10 as well fixed the problem.**

So it seems like there's some obscure breaking of binary compatibility between zio 1.0.10 and 1.0.11 related to the `Has` type tagging stuff (which as you can probably guess I don't understand very well). Perhaps this issue only shows up in Scala 3.

**Comment by adamgfraser** [comment]
Ah, I think the issue is here: https://github.com/zio/izumi-reflect/releases/tag/v2.0.0.

**Comment by quelgar** [comment]
> Ah, I think the issue is here: https://github.com/zio/izumi-reflect/releases/tag/v2.0.0.

Actually, looks like zio 1.0.11 just bumped izumi-reflect from 1.1.2 to 1.1.3, but that does include [a fix to tag hash codes for Scala 3](https://github.com/zio/izumi-reflect/pull/198).

So seems the only way forward is for all libraries supporting Scala 3 to release new versions using zio 1.0.11 or later.

**Comment by bilal-fazlani** [comment]
> This problem occurs when the zio-kafka producer code tries to access Blocking from the environment.

I am running into this same issue now.. 

@quelgar were you able to find a work around for this? `Blocking` layer is now a "Blocker" for me :(


```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Could not find package$::Blocking$::Service inside Map(TestProducer -> com.example.TestProducer@51fd4bea,
package$::Random$::Service -> zio.random.package$$anon$1@f87b4b87,
package$::System$::Service -> zio.system.package$$anon$1@5c7a50a0,
package$::Blocking$::Service -> zio.blocking.package$$anon$1@ba11000f,
package$::Clock$::Service -> zio.clock.package$$anon$1@f8bd3b71,
package$::Console$::Service -> zio.console.package$$anon$1@ee8f30ff,
OrderConsumer -> com.example.OrderConsumer@667c650d)
```

**Comment by bilal-fazlani** [comment]
> Changing my project to use zio 1.0.10 as well fixed the problem.

This helped me too 👍🏽

**Comment by tellnobody1** [comment]
I had a similar runtime error with latest version of ZIO `1.0.18` and Scala both `3.3.0-RC2` and `3.2.2`:

```scala
java.lang.Error: Defect in zio.Has: Could not find package$::Blocking$::Service inside Map(
  package::Blocking::Service -> zio.blocking.package$Blocking$Service$$anon$1@12febe94, ...
```

Recompilation of all dependencies with ZIO 1.0.18 solved the problem but only for main app. zio-test still doesn't work.

In the end it is turned out that the problem with kind projections. So, instead of `RIO[R, *]` use `type AppIO[A] = RIO[R, A]; AppIO`.

**Comment by hearnadam** [comment]
ZIO 1.x issues are not being prioritized. Feel free to reopen if this is still an issue/you have a PR idea.
