### ISSUE TITLE
add testaspect for graalvm native-image

### ISSUE THREAD

**Issue by domdorn** [zio/zio#5595]
allow to limit/annotate tests in a similar way we have for js, native, etc. when run using graalvm native-image

**Comment by adamgfraser** [comment]
Do you know how we can tell whether we are running on it? Is there a system property that reflects that?

**Comment by domdorn** [comment]
hmm.. will have to search for that.. there was a sbt plugin that was also running natively compiled code + tests, need to see how that was done (and even which plugin it was...) .. for now I would rate this as low priority

**Comment by tewecske** [comment]
It's not final yet. The TestPlatform isGraalVM has some comments which contains the system properties I found to check if GrallVM native is used. But not sure which one should I use.
`java.vendor.url` and `java.vm.version` is the same in case of non native GraalVM run.

I'm also not sure about the isGraalVM/graalVMOnly name because this is for GraalVM native only and the name may be confusing. Although I don't know if GraalVM is used in general without using the native part. So which one is more common.

**Comment by tewecske** [comment]
These are the system properties.

java.vendor.url -> https://www.graalvm.org/
java.vm.version -> GraalVM 20.2.0 Java 8
org.graalvm.nativeimage.imagecode -> runtime
org.graalvm.nativeimage.kind -> executable

**Comment by tewecske** [comment]
I wasn't able to try it out yet. I can't run zio tests natively. JUnit java tests work using gradle and GraalVM native but zio tests don't.

**Comment by adamgfraser** [comment]
Do they work on ZIO 1.0? Do we have another issue that we need to figure out first?

**Comment by tewecske** [comment]
I don't think there is an issue. I just don't know yet how to do it. In the sbt graalvm native plugin there isn"t even an option to run tests as native image 
I created a simple gradle project with the graalvm plugin but could only run the java junit tests as native image.

BTW is this needed for 1.0 as well?

**Comment by domdorn** [comment]
@ezzarghili @fniephaus sorry to pull you in. could you please advice how we can determine at runtime if we're running java through a graalvm-native image? is there something else out there than `org.graalvm.nativeimage.kind` ? a simple java code snippet would be much appreciated - thanks!

**Comment by adamgfraser** [comment]
@tewecske I think we are close enough to release of ZIO 2.0 that we should be focusing new development there.

**Comment by adamgfraser** [comment]
@domdorn Thanks for jumping in on this!

**Comment by ezzarghili** [comment]
You can look at the existing [API](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java) for this:
ImageInfo.inImageRuntimeCode() is what you are looking for I think.
The property org.graalvm.nativeimage.imagecode contains the value.

**Comment by tewecske** [comment]
@adamgfraser Should I try to load this class and call the `inImageRuntimeCode()` or just simply check for this property being `"runtime"`?

**Comment by tewecske** [comment]
@adamgfraser @domdorn 
Ok I think this feature requires some other changes.

- SBT plugin doesn't run native image tests.
- zio-test-junit runs with junit 4 but the gradle native image plugin only support junit 5.
- zio-test doesn't have a junit 5 platform TestEngine (or I didn't find it). Here is the scalatest version: https://github.com/helmethair-co/scalatest-junit-runner/blob/main/src/main/java/co/helmethair/scalatest/ScalatestEngine.java
- I don't know how to build and run GraalVM native image tests without build tools :)

So there is no way (for me) to test this and probably not usable for anyone else who uses sbt or gradle.

What is the next step?

**Comment by adamgfraser** [comment]
@tewecske Thanks for following up! I think it is a little bit up to you. We can open issues for these things and wait for them to be added or if you want to take ownership of this you can work on some of these enablers as part of a larger effort to enable. Probably figuring out why tests aren't running is the first step and seeing if anyone else is able to run tests.

**Comment by tewecske** [comment]
@adamgfraser 
Tests are runnig fine if I'm using junit 4. There is no issue with that.
Only the native image test run is the problem and because of the issues I mentioned above.
Adding nativeTest to the sbt plugin and implementing the junit 5 TestEngine in zio-test-junit would solve all issues.

**Comment by tewecske** [comment]
Created an issue for the SBT plugin: https://github.com/scalameta/sbt-native-image/issues/50

**Comment by domdorn** [comment]
I propose to do this: 

`TestAspects.isGraalNativeImage` does :
```java
System.getProperty("org.graalvm.nativeimage.imagecode") != null 
```

`TestAspects.isGraalNativeImageExecutable` does:
```java
System.getProperty("org.graalvm.nativeimage.imagecode") == "executable"
```

`TestAspects.isGraalNativeImageLibrary` does:
```java
System.getProperty("org.graalvm.nativeimage.imagecode") == "shared"
```

As for compiling tests to native and then running them, we'd probably have to get in touch with the sbt masters (the only one I know of is @eed3si9n).. maybe the guys from scala-native-packager also already have some experience with it.

**Comment by tewecske** [comment]
Added zio issue: https://github.com/zio/zio/issues/6724

**Comment by tewecske** [comment]
@domdorn 
`"executable"` and `"shared"` are values of `org.graalvm.nativeimage.kind` and I'm not sure if that check is useful.
I think the check we need is `org.graalvm.nativeimage.imagecode` should be `"runtime"` or maybe simply not `null` as you wrote, but I'm not sure what `"buildtime"` means in this case.

**Comment by gergo-** [comment]
(GraalVM team member here, though not an absolute native image specialist.)

> I think the check we need is `org.graalvm.nativeimage.imagecode` should be `"runtime"` or maybe simply not `null` as you wrote

Yes, `"runtime"` is the correct check.

> , but I'm not sure what "buildtime" means in this case.

Native image offers ways for the application to run code at "build time", i.e., while the native image is being built. This can be useful for things like pre-initializing some configuration information and baking constant config values into the actual image.

A simple way to get `"buildtime"` is to use static initializers:

```
    static String staticImageCode = System.getProperty("org.graalvm.nativeimage.imagecode");
```

*and* passing the flag `--initialize-at-build-time=MyClass` to the `native-image` tool. If you don't use any native image features to force some code to run at build time, you should never observe a value of `"buildtime"` for this property.

**Comment by domdorn** [comment]
@gergo- thanks for chiming in!
We're trying to compile test suites to native-images and have  a way to enable/disable certain tests depending on which platform they run (e.g. if they run in ScalaJS or Win/Mac/Linux or in this case as a native-image). So we don't want to run something on compile time but we want to be able to e.g. disable the ScalaJS tests when the tests are executed in a native image while enabling others that might be specific for that environment. I still think that checking the `org.graalvm.nativeimage.kind` property would be the right approach to figure this out?

**Comment by gergo-** [comment]
Some context: GraalVM can build two kinds of native images: stand-alone executables and shared libraries. By default you get a stand-alone executable of a full application, i.e., if you compile a "Hello World" program you get an executable called `hello` and can run it from the shell as `./hello`. Here the `org.graalvm.nativeimage.kind` will always be `executable`.

In contrast, a [shared library](https://www.graalvm.org/22.0/reference-manual/native-image/#build-a-shared-library) (`.so`/`.dylib`/`.dll` depending on the system) can be built by passing `--shared` to the native image builder and annotating certain methods in the Java code as `@CEntryPoint`. Such shared library images cannot be executed directly from a shell, you would need another program that links or loads that library and calls an entry point exactly as if it were a C function defined in a shared library written in C. If you do all of this, then inside this library code you will have a `org.graalvm.nativeimage.kind` of `shared`.

I *suspect* that you don't actually build shared libraries in this way. Therefore I suspect the `org.graalvm.nativeimage.kind` values you can observe will always be `executable`, so checking it doesn't tell you anything.

> we want to be able to e.g. disable the ScalaJS tests when the tests are executed in a native image while enabling others that might be specific for that environment

If all you want to know is whether "the tests are executed in a native image", then `org.graalvm.nativeimage.imagecode` is the way to go. If, and *only* if you are sometimes packaging some tests as standalone executables and sometimes as shared libraries to be called from an external driver, then `org.graalvm.nativeimage.kind` will tell you something. But from your description it sounds to me like that is not the case.

**Comment by domdorn** [comment]
hmm.. we basically want to be able to do the same thing the quarkus people are doing described here 
https://quarkus.io/guides/building-native-image#testing-the-native-executable

However, I've just read that they do not compile the tests to native images but just allow to call http-methods in native images. They also seem to have added some test helpers which seem to be marked deprecated:

https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/NativeTestExtension.java
https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/DisabledOnNativeImageCondition.java
https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/DisabledOnNativeImage.java


@adamgfraser + @tewecske it looks like quarkus is only issueing http requests against a native executable. To have something similar, we'd need a kind of IntegrationTest that starts the native executable as a own process and then runs the tests in the jvm against the executable via http/https. This looks like a very special use case and I'm not sure its worth the effort as long as we don't have an explicit use case for native-images (maybe in zio-lambda ?)

**Comment by adamgfraser** [comment]
Yeah it seems like this is probably out of scope for us. I thought the idea here was just to be able to say doing some particular operation doesn't make sense if we are running on Graal, so don't run this test if we are. Is that a real use case?

**Comment by tewecske** [comment]
@gergo- 

I don't know if you can help but I can't resolve this issue:

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing zio.Random$RandomLive$$$Lambda$2fe38c43cb8b13d23626fcf015bfb9afae448528.apply$mcI$sp()
Parsing context:
   at zio.Random$RandomLive$$$Lambda$2715/0x00000007c186a040.apply$mcI$sp(Unknown Source)
   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
   at zio.internal.FiberContext.runUntil(FiberContext.scala:197)
   at zio.internal.FiberContext.run(FiberContext.scala:112)
   at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
   at com.oracle.svm.core.jdk.RuntimeSupport.executeTearDownHooks(RuntimeSupport.java:121)
```

I don't know if this is an issue in zio or something else.
I tried a bunch of things. I get this error message if I set this:
```
--initialize-at-build-time=scala,zio
```

If I don't add `zio` to build time init then I get a bunch of errors like these:
```
Error: Classes that should be initialized at run time got initialized during image building:
 zio.internal.stacktracer.Tracer$ was unintentionally initialized at build time. To see why zio.internal.stacktracer.Tracer$ got initialized use --trace-class-initialization=zio.internal.stacktracer.Tracer$
zio.Chunk$Empty$ was unintentionally initialized at build time. To see why zio.Chunk$Empty$ got initialized use --trace-class-initialization=zio.Chunk$Empty$
zio.test.Live$ was unintentionally initialized at build time. To see why zio.test.Live$ got initialized use --trace-class-initialization=zio.test.Live$
...
```

I tried to add them 1-by-1 to build init but I gave up after like 25 classes :)

If I try to add these files to --trace-class-initialization then I get this kind of error:
```
zio.Chunk$Empty$ was unintentionally initialized at build time. zio.Chunk$Empty$ has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=zio.Chunk$Empty$
```

This is the first time I'm trying to build a graalvm native image. So I guess I could miss something obvious.

All this only happens when I try to run zio-test using junit vintage engine (that's the only way to run non junit 5 tests in graalvm native afaik) with the nativeTest gradle graalvm native image plugin task.

I can run a simple zio program as a native image without any problem.
I'm kind of frustrated after 2 days without making any progress :) But at least I learned a lot :)

**Comment by fniephaus** [comment]
>I'm kind of frustrated after 2 days without making any progress :)

Trying to compile an app that uses a non-trivial library like zio that doesn't support Native Image is probably not the best way to get started with GraalVM Native Image to be honest. Nonetheless, we know that the development experience could be improved and we are working on this.

In this particular case, Native Image doesn't know what parts of zio can be initialized at build-time or at run-time. By default, all app code is initialized at run-time but the build will fail in case anything is suddenly initialized at build-time. Native Image works best if all of zio can be initialized at build-time, but that may not be possible for all bits of the library for other reasons. The best way to resolve the general problem is to add dedicated Native Image support to zio, which means adding, maintaining, and shipping zio-specific [config files for Native Image](https://www.graalvm.org/22.1/reference-manual/native-image/BuildConfiguration/).

To fix your specific problem, I think the actual error is masked by the `ParsingError`, which is unfortunate but [we know about this problem as well](https://github.com/oracle/graal/issues/4319#issuecomment-1039385620). Could you re-run this again with `--initialize-at-build-time=scala,zio` and have a look further down the stack trace, I'm sure you'll find the actual problem. You may also want to give the [Tracing Agent](https://www.graalvm.org/22.1/reference-manual/native-image/Agent/) a try, which may be able to help you find the correct config for Native Image.

**Comment by tewecske** [comment]
@fniephaus 
Thank you very much for this info!
And sorry, I'm NOT frustrated with the graalvm native image building experience, but this situation as you said it's non-trivial and I couldn't make any progress because of my lack of knowledge.

Is this agent the same as the one described [here](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support)? I have it turned on but the tracing output is not configured. I'll try that.

I'll try it again and check the stack trace.

**Comment by fniephaus** [comment]
> Is this agent the same as the one described [here](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support)?

Yes, that's the one.

Let us know how it goes!

**Comment by adamgfraser** [comment]
@fniephaus Thanks for your help with this!

Yes, it may make sense to open an issue for improved support in general. We definitely have some users using GraalVM Native Image and have done some work to address it such as [here](https://github.com/zio/zio/pull/6230) but would be good to address more comprehensively.

**Comment by fniephaus** [comment]
Let me know if you need any help with this from our side.

**Comment by guizmaii** [comment]
@tewecske What's the state of your work on this ticket?

**Comment by tewecske** [comment]
@guizmaii 
So it looks like the related issues were fixed so this should work if I remember correctly, but it was a long time ago :)
https://github.com/scalameta/sbt-native-image/pull/60
https://github.com/zio/zio/issues/6724

**Comment by guizmaii** [comment]
@tewecske Any chance you open a PR about this? 🙂
