### ISSUE TITLE
ZLayer Fails at Runtime with a 'java.lang.NoClassDefFoundError: scala/<repeated>' for Vararg Value Classes

### ISSUE THREAD

**Issue by scottweaver** [zio/zio#5736]
### Environment

**ZIO Version:**    1.0.11
**Scala Version:** 2.12.10 and 2.12.15
**JRE Version:**    14

### Expected Behavior

Exposing a value class whose argument is a vargarg e.g.  `case class VargArgsAnyVal(values: String*) extends AnyVal`,  via `ZLayer` should behave as any other type/class exposed by a ZLayer.

### Actual Behavior

Fiber crashes at runtime with a defect:
```
An unchecked error was produced.
java.lang.NoClassDefFoundError: scala/<repeated>
	at vyze.funding.dwr.healthcheck.VarArgsAnyValNoClassDefFoundSpec$.$anonfun$spec$1(VarArgsAnyValNoClassDefFoundSpec.scala:19)
	at zio.ZIO$.$anonfun$effectSuspendTotal$1(ZIO.scala:2752)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:582)
	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: scala.<repeated>
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at sbt.internal.ManagedClassLoader.findClass(LayeredClassLoaders.scala:376)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 7 more
[info]
Fiber:Id(1633537780596,87) was supposed to continue to:
  a future continuation at zio.test.package$ZTest$.apply(package.scala:119)
[info]
Fiber:Id(1633537780596,87) execution trace:
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2752)
[info]
Fiber:Id(1633537780596,87) was spawned by:
[info]
Fiber:Id(1633537780495,31) was supposed to continue to:
  a future continuation at zio.ZIO.run(ZIO.scala:1697)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:262)
  a future continuation at zio.ZIO.run(ZIO.scala:1697)
  a future continuation at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:373)
  a future continuation at zio.test.package$Annotations$$anon$1.withAnnotation(package.scala:654)
  a future continuation at zio.ZIO.run(ZIO.scala:1697)
  a future continuation at zio.ZIO$BracketRelease_.apply(ZIO.scala:4324)
  a future continuation at zio.FiberRef.locally(FiberRef.scala:96)
  a future continuation at zio.ZIO.run(ZIO.scala:1697)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:262)
[info]
Fiber:Id(1633537780495,31) execution trace:
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2752)
  at zio.ZIO.bracket_(ZIO.scala:262)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:614)
  at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:374)
  at zio.Supervisor$.fibersIn(Supervisor.scala:170)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2752)
  at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:374)
  at zio.ZIO$TapFn.apply(ZIO.scala:4393)
  at zio.test.package$Annotations$.annotate(package.scala:627)
  at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:364)
[info]
Fiber:Id(1633537780495,31) was spawned by:
[info]
Fiber:Id(1633537779861,0) was supposed to continue to:
  a future continuation at zio.ZIO$.foreach(ZIO.scala:2938)
  a future continuation at zio.ZIO.zipWith(ZIO.scala:2218)
  a future continuation at zio.ZIO$.foreach(ZIO.scala:2939)
  a future continuation at zio.ZIO$.foreachPar_(ZIO.scala:3147)
  a future continuation at zio.ZIO$.foreachPar_(ZIO.scala:3147)
  a future continuation at zio.ZIO$.foreachParN(ZIO.scala:3188)
  a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:1451)
  a future continuation at zio.ZManaged$.foreachParN(ZManaged.scala:1783)
  a future continuation at zio.ZManaged.mapM(ZManaged.scala:499)
  a future continuation at zio.ZIO.run(ZIO.scala:1697)
[info]
Fiber:Id(1633537779861,0) execution trace:
  at zio.ZIO.zipWith(ZIO.scala:2218)
  at zio.ZIO$.foreach(ZIO.scala:2938)
  at zio.ZIO.zipWith(ZIO.scala:2218)
  at zio.ZIO$.foreach(ZIO.scala:2938)
  at zio.ZIO.zipWith(ZIO.scala:2218)
  at zio.ZIO$.foreach(ZIO.scala:2937)
  at zio.ZIO$.foreachPar_(ZIO.scala:3112)
  at zio.ZIO$.foreachPar_(ZIO.scala:3112)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZIO$.foreachPar_(ZIO.scala:3112)
[info]
Fiber:Id(1633537779861,0) was spawned by: <empty trace>
```
### Reproduction Test Case

```scala
package vyze.funding.dwr.healthcheck

import zio._
import zio.test._
import zio.test.Assertion._


object VarArgsAnyValNoClassDefFoundSpec extends DefaultRunnableSpec {

	final case class VarArgs(args: String*) 
	
	final case class VarArgsAnyVal(args: String*) extends AnyVal


	def spec = suite("VargsNoClassDefFoundSpec") (
		testM("Fiber will fail at runtime with 'java.lang.NoClassDefFoundError: scala/<repeated>' for AnyVal varargs .") {
			
			val testCase = for {
				_ <- ZIO.service[VarArgsAnyVal]
			} yield {
				assert(())(anything)
			}

			testCase.provideLayer(
				ZLayer.succeed(VarArgsAnyVal())
			)
		},

		testM("Regular var args are fine.") {
			
			val testCase = for {
				_ <- ZIO.service[VarArgs]
			} yield {
				assert(())(anything)
			}

			testCase.provideLayer(
				ZLayer.succeed(VarArgs())
			)
		}
	)
}
```

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/izumi-reflect/issues/224
