### ISSUE TITLE
Include the JVM stack up to `Runtime.unsafeRun*` in the fiber trace

### ISSUE THREAD

**Issue by dkarlinsky** [zio/zio#5785]
**The problem:**
Currently the fiber traces collected and attached to errors only cover the execution inside ZIO universe.
Which is fine if your whole app (or most of it) is ZIO. 
But when interoperating with non-ZIO code we often have flows where non-ZIO code is invoking ZIO effects via `Runtime.unsafeRun*` and if the effect fails, or an error is logged by it, the trace doesn't contain any info on where `Runtime.unsafeRun*` was called from in the non-ZIO part of the application.
(For example a future based GRPC request handler calling a library that is implemented in ZIO).

**The proposal:**
When `Runtime.unsafeRunWith` is creating the main `FiberContext` it could capture the current thread's stack, convert it into a `Ztrace` and pass it to the `FiberContext` as `parentTrace`.
Then in the fiber trace it will appear that the main fiber was spawned by this other fiber, whose trace is actually the captured stack.

Example (parent trace appears as `Fiber:Id(0,0) execution trace:`)

```
Exception in thread "main" java.lang.RuntimeException: kaboom
	at zio.Somewhere$.$anonfun$kaboom$5(RuntimeSpec.scala:13)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:2864)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:407)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: zio.Cause$FiberTrace: Fiber failed.
A checked error was not handled.
java.lang.RuntimeException: kaboom

Fiber:Id(1634380884543,0) was supposed to continue to:
  a future continuation at zio.Somewhere$.kaboom(RuntimeSpec.scala:11)

Fiber:Id(1634380884543,0) execution trace:
  at zio.Somewhere$.kaboom(RuntimeSpec.scala:13)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO.onInterrupt(ZIO.scala:1066)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4248)
  at zio.clock.package$Clock$Service$$anon$1.sleep(package.scala:68)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2740)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2740)
  at zio.clock.package$.sleep(package.scala:119)
  at zio.Somewhere$.kaboom(RuntimeSpec.scala:12)
  at zio.ZIO$.debug(ZIO.scala:2642)

Fiber:Id(1634380884543,0) was spawned by:

Fiber:Id(0,0) was supposed to continue to: <empty trace>

Fiber:Id(0,0) execution trace:
  at zio.Runtime.unsafeRunWith(Runtime.scala:190)
  at zio.Runtime.unsafeRunSync(Runtime.scala:85)
  at zio.Runtime.unsafeRunSync$(Runtime.scala:82)
  at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:286)
  at zio.Runtime.unsafeRunTask(Runtime.scala:74)
  at zio.Runtime.unsafeRunTask$(Runtime.scala:73)
  at zio.Runtime$$anon$3.unsafeRunTask(Runtime.scala:286)
  at zio.Somewhere$.kaboom(RuntimeSpec.scala:12)
  at zio.RuntimeSpec$.delayedEndpoint$zio$RuntimeSpec$1(RuntimeSpec.scala:6)
  at zio.RuntimeSpec$delayedInit$body.apply(RuntimeSpec.scala:5)
  at scala.Function0.apply$mcV$sp(Function0.scala:39)
  at scala.Function0.apply$mcV$sp$(Function0.scala:39)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
  at scala.App.$anonfun$main$1(App.scala:76)
  at scala.App.$anonfun$main$1$adapted(App.scala:76)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
  at scala.App.main(App.scala:76)
  at scala.App.main$(App.scala:74)
  at zio.RuntimeSpec$.main(RuntimeSpec.scala:5)
  at zio.RuntimeSpec.main(RuntimeSpec.scala)

Fiber:Id(0,0) was spawned by: <empty trace>
```
As the capturing of the stack has some performance overhead, it could be enabled/disabled by a flag on `Platform`.

If this proposal makes sense, I will submit a PR

**Comment by adamgfraser** [comment]
I think this makes sense. We're doing some work on improving the way traces are rendered but depending on the timing we can just build on top of that. I would definitely submit against the `series/2.x` branch.

**Comment by dkarlinsky** [comment]
Hey @jdegoes, @adamgfraser, as you may know, I'm working on a talk for Functional Scala conf, about "bridging the gap" between ZIO and "legacy" code, and it occurred to me that if this feature existed it would fit nicely in the error handling part of the talk :)
Any way to revive this, so maybe I can get a new PR ready by Nov 30?  :)

**Comment by adamgfraser** [comment]
@dkarlinsky I will take a look at this.

**Comment by adamgfraser** [comment]
Closing as I think this is better handled with existing functionality provided by `FiberRef` and `ZLogger` as discussed in #8509.
