### ISSUE TITLE
`@mockable` fails to mock service that returns a stream

### ISSUE THREAD

**Issue by frekw** [zio/zio#5804]
```scala
import zio._
import zio.test._
import zio.stream._
import zio.test.mock.mockable

trait Service {
  def get(id: String): ZStream[Any, Throwable, List[String]]
}

object TestModule {
  @mockable[Service]
  object ServiceMock
}
```

results in

```
exception during macro expansion: 
scala.MatchError: (Stream(Any,Throwable,List[String]),false,false,false) (of class scala.Tuple4)
	at zio.test.mock.MockableMacro$.zio$test$mock$MockableMacro$$makeTag$1(MockableMacro.scala:161)
	at zio.test.mock.MockableMacro$$anonfun$1.applyOrElse(MockableMacro.scala:276)
	at zio.test.mock.MockableMacro$$anonfun$1.applyOrElse(MockableMacro.scala:274)
	at scala.collection.StrictOptimizedIterableOps.collect(StrictOptimizedIterableOps.scala:150)
	at scala.collection.StrictOptimizedIterableOps.collect$(StrictOptimizedIterableOps.scala:135)
	at scala.collection.immutable.HashMap.collect(HashMap.scala:39)
	at zio.test.mock.MockableMacro$.impl(MockableMacro.scala:274)
```

Scastie: https://scastie.scala-lang.org/TI31eGKgREujOvkSwUO8Ag

**Comment by KineticCookie** [comment]
I encountered the same issue.
In addition to that, I think there is no easy way of writing stream mocks in `zio-test` — there *is* a `Stream` Capability in Mock class, but `Proxy` class used in `compose` only works with `ZIO`.
As for now the only workaround I found is to manually implement service mocks using `withRuntime` and `unsafeRun` for methods that return ZStream. (and that feels kinda weird)
