### ISSUE TITLE
ZIO 2.0: Revamp fiber dump rendering

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5854]
Fibers can be "dumped", which results in a rendering of them. Currently, this rendering is based on the rendering for JVM thread dumps, but is not exactly the same. 

We should explore improving the way fibers dumps are rendered to more closely match JVM rendering to be more accessible to Scala and Java developers (who are already familiar with rendering for thread dumps).

**Comment by dkarlinsky** [comment]
Would be interested in working on this.

**Comment by jdegoes** [comment]
@dkarlinsky 🙏

**Comment by dkarlinsky** [comment]
I have run into an apparent bug in `FiberContext.captureTrace`
When I try to dump trace for a fiber that is running in a loop (using `repeatUntil`) I get `ArrayIndexOutOfBoundsException`.

```scala
for {
       promise <- Promise.make[Nothing, Unit]
       fiber1 <- ZIO.yieldNow.repeatUntilZIO(_ => promise.isDone).fork
       dump <- FiberRenderer.dumpStr(Seq(fiber1), withTrace = true)
        _ <- promise.isDone 
} yield ()
```
This fails with: 
```
 Exception in thread "zio-fiber-" java.lang.ArrayIndexOutOfBoundsException: -1
    	at zio.internal.Stack$$anon$1.next(Stack.scala:49)
    	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    	at zio.internal.Stack.foreach(Stack.scala:24)
    	at zio.internal.FiberContext.captureTrace(FiberContext.scala:86)
    	at zio.internal.FiberContext.$anonfun$trace$1(FiberContext.scala:831)
    	at zio.internal.FiberContext.runUntil(FiberContext.scala:303)
    	at zio.internal.FiberContext.run(FiberContext.scala:233)
    	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
```
Full example [here](https://github.com/dkarlinsky/zio/blob/3994832b37db20ca9d93946a00b564580edfcbfe/core-tests/shared/src/test/scala/zio/internal/FiberRendererSpec.scala)

**Comment by dkarlinsky** [comment]
Created an issue: #5948
