### ISSUE TITLE
ZIO 2.0: `ArrayIndexOutOfBoundsException` in `FiberContext.captureTrace`

### ISSUE THREAD

**Issue by dkarlinsky** [zio/zio#5948]
I have run into an apparent bug in `FiberContext.captureTrace`
When I try to dump trace for a fiber that is running in a loop (using `repeatUntil`) I get `ArrayIndexOutOfBoundsException`.

```scala
for {
       promise <- Promise.make[Nothing, Unit]
       fiber1 <- ZIO.yieldNow.repeatUntilZIO(_ => promise.isDone).fork
       dump <- FiberRenderer.dumpStr(Seq(fiber1), withTrace = true)
        _ <- promise.isDone 
} yield ()
```
This fails with: 
```
 Exception in thread "zio-fiber-" java.lang.ArrayIndexOutOfBoundsException: -1
    	at zio.internal.Stack$$anon$1.next(Stack.scala:49)
    	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    	at zio.internal.Stack.foreach(Stack.scala:24)
    	at zio.internal.FiberContext.captureTrace(FiberContext.scala:86)
    	at zio.internal.FiberContext.$anonfun$trace$1(FiberContext.scala:831)
    	at zio.internal.FiberContext.runUntil(FiberContext.scala:303)
    	at zio.internal.FiberContext.run(FiberContext.scala:233)
    	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
```
Full example [here](https://github.com/dkarlinsky/zio/blob/3994832b37db20ca9d93946a00b564580edfcbfe/core-tests/shared/src/test/scala/zio/internal/FiberRendererSpec.scala)

**Comment by adamgfraser** [comment]
I will take a look at this.

**Comment by adamgfraser** [comment]
The issue here is that the continuation stack is concurrently accessed when `Fiber#trace` is called and `Stack` is not safe for concurrent access.

@jdegoes Will take this as part of his ongoing work on tracing.
