### ISSUE TITLE
ZIO.service is unsound

### ISSUE THREAD

**Issue by ya-goodfella** [zio/zio#6053]
Given latest snapshot version (2.0.0-M5+7-9d3014fc-SNAPSHOT) running in Ammonite REPL:

```
@ trait A
defined trait A

@ trait B
defined trait B

@ val zio = ZIO.service[A & B]
zio: URIO[A & B, A & B] = zio.ZIO$Suspend@1cb83205

@ val provided = zio.provideSome((a: ZEnvironment[A]) => a.add(new B {})).provide(ZEnvironment(new A {}))
provided: IO[Nothing, A & B] = zio.ZIO$FiberRefLocally@55f2e76a

@ Runtime.default.unsafeRun(provided)
zio.FiberFailure: Exception in thread "zio-fiber-1637156552" java.lang.Error: Defect in zio.ZEnvironment: Could not find {cmd17::A & cmd18::B} inside ZEnvironment(Map(cmd17::A -> ammonite.$sess.cmd20$$anon$2@43e869ea, cmd18::B -> ammonite.$sess.cmd20$$anon$1@8f7cbcc))
	at zio.ZEnvironment.unsafeGetAll(ZEnvironment.scala:118)
	at zio.ZEnvironment.unsafeGet(ZEnvironment.scala:101)
	at zio.ZIO$ServiceWithPartiallyApplied$.$anonfun$apply$12(ZIO.scala:5783)
	at zio.ZIO$FlatMap.apply(ZIO.scala:6216)
	at zio.ZIO$FlatMap.apply(ZIO.scala:6205)
	at zio.internal.FiberContext.unsafeNextEffect(FiberContext.scala:849)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:371)
	at zio.internal.FiberContext.run(FiberContext.scala:92)
	at zio.Runtime.unsafeRunWith(Runtime.scala:327)
```

**Comment by kitlangton** [comment]
Just for bystanders, this will be rectified momentarily—hence no new release yet :)

Details here: https://twitter.com/Fellrond/status/1460967143135227909
