### ISSUE TITLE
ZIO 2.0: ZChannel.repeated throws StackOverflowError

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio#6173]
Version: 2.0.0-RC1

Example:
```scala
import zio._
import zio.stream._

object Zap extends ZIOAppDefault {

  def run: ZIO[ZEnv with ZIOAppArgs, Any, Any] =
    ZChannel.write(1).repeated.runDrain.timeout(1.second)
}
```

Output:
```
java.lang.StackOverflowError
	at zio.stream.ZChannel$Fold$.failCauseIdentity(ZChannel.scala:1078)
	at zio.stream.ZChannel.flatMap(ZChannel.scala:399)
	at zio.stream.ZChannel.flatMap$(ZChannel.scala:388)
	at zio.stream.ZChannel$Emit.flatMap(ZChannel.scala:1018)
	at zio.stream.ZChannel.$times$greater(ZChannel.scala:75)
	at zio.stream.ZChannel.$times$greater$(ZChannel.scala:64)
	at zio.stream.ZChannel$Emit.$times$greater(ZChannel.scala:1018)
```

**Comment by vigoo** [comment]
Thanks for reporting!

**Comment by ajaychandran** [comment]
I think this is similar to #5870. Perhaps the returned channel should be cached?

**Comment by ajaychandran** [comment]
What I meant was that the following optimization could be included as well.
```scala
def repeated(implicit trace: ZTraceElement): ZChannel[Env, InErr, InElem, InDone, OutErr, OutElem, Nothing] = {
  lazy val loop: ZChannel[Env, InErr, InElem, InDone, OutErr, OutElem, Nothing] = self *> loop
  loop
}
```
Similar to how `ZIO.forever` was redefined in  #5985.

**Comment by vigoo** [comment]
I see, we can do that too. Anyway, the issue helped me realize the more fundamental `flatMap` stack safety issue in the executor that is fixed by the PR. 
I added your proposal to it too.
