### ISSUE TITLE
ZIO 2.0-RC1: Chunk throws mysterious ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by BardurArantsson** [zio/zio#6180]
Hi!

I'm getting a rather mysterious ArrayOutOfBoundsException from Chunk.

Here's the smallest reproducer that I have so far:

```scala
import zio.Chunk

case class Grid[T](
  w: Int,
  h: Int,
  private val init: T,
  private val data: Chunk[Chunk[T]]) {

  private def get(x: Int, y: Int): T =
    data(y)(x)

  private def updated(x: Int, y: Int, t: T): Grid[T] =
    copy(data =
      data.updated(y,
        data(y).updated(
          x, t)))

  private def points: Iterable[(Int, Int)] = for {
    y <- 0 until h
    x <- 0 until w
  } yield (x, y)

  def map(f: T => T): Grid[T] = {
    points.foldLeft(this) { case (acc, (x, y)) =>
      Console.println(s"p = {$x, $y}")
      acc.updated(x, y, f(get(x, y)))
    }
  }

}

def fill[T](w: Int, h: Int)(init: T): Grid[T] =
  Grid(
    w = w,
    h = h,
    init = init,
    data = Chunk.fill(h)(Chunk.fill(w)(init)))

val g = fill(w = 66, h = 256)(20)

// Throws:
Console.println(g.map(_ + 1))
```

Running this shows

```txt
(snip)
p = {54, 3}
p = {55, 3}
p = {56, 3}
p = {57, 3}
p = {58, 3}
java.lang.ArrayIndexOutOfBoundsException: Index 256 out of bounds for length 256
  at zio.Chunk$Update.apply(Chunk.scala:1362)
  at Grid.updated(<console>:13)
  at Grid.$anonfun$map$1(<console>:24)
  at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
  at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
  at scala.collection.AbstractIterable.foldLeft(Iterable.scala:926)
  at Grid.map(<console>:22)
  ... 39 elided
  ```
  
  and I'm a bit mystified where the 256 in "Index 256 out of bounds" is coming from. Obviously, the "length 256" bit comes from the length I've specified.

As you can see from the output we're querying indexes 58 and 3.

The code works fine on ZIO 1.0.12.

I'll try to minimize the reproducer further.

**Comment by BardurArantsson** [comment]
Varying the parmaeters to the fill method shows that (w,h) = (65, 4) seems to be some sort of boundary where it starts to go wrong. (w,h) = (64, 4) works as does (65,3).

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!

**Comment by BardurArantsson** [comment]
Ok, reproducer shortened further to this:

```scala
import zio.Chunk

case class Grid[T](
  w: Int,
  private val init: T,
  private val data: Chunk[Chunk[T]]) {
  
  private def updated(x: Int, t: T): Grid[T] =
    copy(data =
      data.updated(0,
        data(0).updated(
          x, t)))

  def map(f: T => T): Grid[T] = {
    (0 until w).foldLeft(this) { case (acc, x) =>
      Console.println(s"p = {$x, 0}")
      acc.updated(x, f(data(0)(x)))
    }
  }

}

def fill[T](w: Int)(init: T): Grid[T] =
  Grid(
    w = w,
    init = init,
    data = Chunk.fill(1)(Chunk.fill(w)(init)))

val g = fill(w = 257)(20)

// Throws:
Console.println(g.map(_ + 1))
```

Interestingly, removing the outer wrapping Chunk seems to get rid of the problem in this reproducer.

**Comment by adamgfraser** [comment]
I think I see the issue. Will submit a PR shortly.

**Comment by BardurArantsson** [comment]
Cool! Very fast turn-around :).

Are snapshots published, or should I just wait for RC2? No rush, obviously, I realize RCs are RCs for a reason :D
