### ISSUE TITLE
Early initialization of the Random service

### ISSUE THREAD

**Issue by 4e6** [zio/zio#6228]
The change https://github.com/zio/zio/pull/5731 prevents the [GraalVM native image](https://www.graalvm.org/reference-manual/native-image/) builds because it causes the initialization of `scala.util.Random` at the image build time. It is not possible to delay the initialization as the value [`zio.random.Random.Service.live`](https://github.com/zio/zio/blob/c36312f37bcd9fd682671656f67f842f84eac9e4/core/shared/src/main/scala/zio/random/package.scala#L50-L51) initializes at the object creation time.

```
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
	reading field scala.util.Random.self of
		constant scala.util.Random$@3f89a0b2 reached by
	reading field zio.random.package$Random$Service$RandomScala.random of
		constant zio.random.package$Random$Service$RandomScala@5ec3fb43 reached by
	scanning method zio.random.package$Random$Service$.live(package.scala:50)
Call path from entry point to zio.random.package$Random$Service$.live():
	at zio.random.package$Random$Service$.live(package.scala:50)
	at zio.PlatformSpecific$ZEnv$Services$.<init>(PlatformSpecific.scala:36)
	at zio.PlatformSpecific$ZEnv$.Services$lzycompute$1(PlatformSpecific.scala:30)
	at zio.PlatformSpecific$ZEnv$.Services(PlatformSpecific.scala:30)
	at zio.BootstrapRuntime.environment(BootstrapRuntime.scala:22)
	at zio.BootstrapRuntime.environment$(BootstrapRuntime.scala:22)
	at org.enso.projectmanager.boot.ProjectManager$.environment(ProjectManager.scala:30)
	at org.enso.projectmanager.boot.ProjectManager$.environment(ProjectManager.scala:30)
	at zio.Runtime.unsafeRunWith(Runtime.scala:216)
	at zio.Runtime.unsafeRunSync(Runtime.scala:84)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:81)
	at org.enso.projectmanager.boot.ProjectManager$.unsafeRunSync(ProjectManager.scala:30)
	at zio.App$$anon$1.run(App.scala:71)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

possible solutions would be:
- make the [`zio.random.Random.Service.live`](https://github.com/zio/zio/blob/c36312f37bcd9fd682671656f67f842f84eac9e4/core/shared/src/main/scala/zio/random/package.scala#L50-L51) value lazy and suspend/make lazy the [layer](https://github.com/zio/zio/blob/c36312f37bcd9fd682671656f67f842f84eac9e4/core/shared/src/main/scala/zio/random/package.scala#L100-L101) 
- convert the [`zio.random.Random.Service.live`](https://github.com/zio/zio/blob/c36312f37bcd9fd682671656f67f842f84eac9e4/core/shared/src/main/scala/zio/random/package.scala#L50-L51) value to a function `def live(random: scala.util.Random)` and suspend/make lazy the [layer](https://github.com/zio/zio/blob/c36312f37bcd9fd682671656f67f842f84eac9e4/core/shared/src/main/scala/zio/random/package.scala#L100-L101) (providing the `scala.util.Random` value)

I can create a PR, just not sure how to fix that properly.

**Comment by adamgfraser** [comment]
@4e6 Thanks for reporting! I just submitted a PR to resolve.
