### ISSUE TITLE
zio 2.0 exception thrown in ZStream between Hubs does not generate stack trace

### ISSUE THREAD

**Issue by searler** [zio/zio#6243]
` result <- ZStream("string") .mapZIO(s => ZIO.succeed({throw new Exception("bang");s})).run(ZSink.collectAll)`
Results in stack trace to stdout, as expected.

```
outgoing <- ZHub.bounded[String](10)
incoming <- ZHub.bounded[String](10)
result<-  ZStream.fromHub(outgoing).map(_ => {throw new Exception("bang");"string"}).run(ZSink.fromHub(incoming))
```

**No stack trace is generated**.
Fiber is killed

In both cases, a defect is appropriate for the design.
But I do expect the stack trace, indicating an unexpected error in the program.

2.0.0-RC1
Azul Systems, Inc. Java 11.0.13
Ubuntu 20.04

**Comment by adamgfraser** [comment]
@searler The following program fails for me and prints a log on the last version of `series/2.x`:

```scala
package zio.stream

import zio._

object Example extends ZIOAppDefault {

  val run =
    for {
      outgoing <- ZHub.bounded[String](10)
      incoming <- ZHub.bounded[String](10)
      _        <- outgoing.publish("foo").delay(1.second).forever.fork
      result <-
        ZStream.fromHub(outgoing).map { _ => throw new Exception("bang"); "string" }.run(ZSink.fromHub(incoming))
    } yield ()
}
```

```
timestamp=2022-01-22T18:15:02.379659Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-2" java.lang.Exception: bang
        at zio.stream.Example$.$anonfun$run$9(Example.scala:13)
        at zio.Chunk.mapChunk(Chunk.scala:985)
        at zio.ChunkLike.map(ChunkLike.scala:113)
        at zio.ChunkLike.map$(ChunkLike.scala:112)
        at zio.Chunk.map(Chunk.scala:42)
        at zio.stream.ZStream.$anonfun$map$1(ZStream.scala:2312)
        at zio.stream.ZChannel.$anonfun$mapOut$1(ZChannel.scala:691)
        at zio.stream.internal.ChannelExecutor.$anonfun$run$15(ChannelExecutor.scala:198)
        at zio.stream.internal.ChannelExecutor$.read$1(ChannelExecutor.scala:924)
        at zio.stream.internal.ChannelExecutor$.$anonfun$readUpstream$5(ChannelExecutor.scala:948)
        at zio.ZIO.$anonfun$$times$greater$1(ZIO.scala:105)
        at zio.ZIO$FlatMap.apply(ZIO.scala:6141)
        at zio.ZIO$FlatMap.apply(ZIO.scala:6130)
        at zio.internal.FiberContext.unsafeNextEffect(FiberContext.scala:882)
        at zio.internal.FiberContext.runUntil(FiberContext.scala:235)
        at zio.internal.FiberContext.run(FiberContext.scala:115)
        at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
        at zio.internal.FiberContext.runUntil(FiberContext.scala:538)
        at zio.stream.Example.run(Example.scala:13)
        at zio.stream.Example.run(Example.scala:12)"
```

Note that we need to offer at least one element to the `incoming` hub to trigger this error. The `map` function is only invoked when there is a stream element, so if an element is never offered to the hub there is never a stream element to the map and the program is terminating rather than failing, which I also believe is the expected behavior.

**Comment by searler** [comment]
Apologies for not providing full replication code.

Revisiting the test code, I had failed to ensure Hub subscription exists before injecting data.

After resolving that defect, I do see exceptions.

I agree with the _termination when there is no element offered._

Thanks for addressing this so promptly
