### ISSUE TITLE
zio2.0 - ZIOAppDefault is not reporting unhandled errors

### ISSUE THREAD

**Issue by searler** [zio/zio#6278]
Discovered in the course of clarifying #6243 

The [documentation](https://zio.dev/next/overview/overview_running_effects#error-reporting) indicates

> The default unhandled error reporter merely logs the error to standard error.

#4736 might be relevant

**ZIO 2.0**

```
object Example4 extends ZIOAppDefault {
  val run =
    for {
      resultFork <- ZIO.succeed(throw new Exception("bang")).fork
     result <- resultFork.await
    } yield ()
}
```
Nothing is output .

**ZIO 1.0**

```object Example  extends zio.App {
  def run(args:List[String]) =
    program.exitCode
    val program =  for {
      resultFork <-
        ZIO.succeed(throw new Exception("bang")).fork
      result <- resultFork.await
    } yield ()
}
```

Fiber failed.
An unchecked error was produced.
java.lang.Exception: bang
	at zio.nio.Example$.$anonfun$program$1(Example.scala:10)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:398)
	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
 ...

**Comment by adamgfraser** [comment]
This is expected behavior. The program above does not actually fail because the forked fiber is never joined. Failures of fibers that are never joined are logged at the `Debug` log level and by default only logs at the `Info` level or above are rendered to the console.

**Comment by searler** [comment]
I was unable to determine how to change the default log level.

Next attempted to add a ZLogger that would printout all debug levels.
(Used println for simplicity of implementation. Managing effects to not a concern for this limited purpose)

The thrown Exception is only recorded by the builtin logger.
The ZIO.log calls are only recorded by the added custom logger.




```
import zio.{FiberId, FiberRef, LogLevel, LogSpan, RuntimeConfigAspect, ZIO, ZIOAppDefault, ZLogger, ZTraceElement}

object Example extends ZIOAppDefault {

  val loggerString: ZLogger[String, Unit] =
    (
      trace: ZTraceElement,
      fiberId: FiberId,
      level: LogLevel,
      message: () => String,
      context: Map[FiberRef.Runtime[_], AnyRef],
      spans: List[LogSpan],
      location: ZTraceElement
    ) => {
      try {
        System.err.println("custom:" + ZLogger.defaultString(trace, fiberId, level, message, context, spans, location))
        ()
      } catch {
        case t: Throwable => t.printStackTrace()
      }
    }

  override def hook = RuntimeConfigAspect.addLogger(loggerString)

  val run =
    for {
      _ <- ZIO.logDebug("Log at debug")
      _ <- ZIO.logError("Log at error")
      _ <- ZIO.succeed(throw new Exception("bang"))
    } yield ()
}
```

```
custom:timestamp=2022-01-23T15:55:50.528857Z level=DEBUG thread=#zio-fiber-1642953350 message="Log at debug" location=searler.zswing.flasher.Example.run file=Example.scala line=26
custom:timestamp=2022-01-23T15:55:50.536604Z level=ERROR thread=#zio-fiber-1642953350 message="Log at error" location=searler.zswing.flasher.Example.run file=Example.scala line=27
timestamp=2022-01-23T15:55:50.578163Z level=ERROR thread=#zio-fiber-1642953350 message="Exception in thread "zio-fiber-1642953350" java.lang.Exception: bang
	at searler.zswing.flasher.Example$.$anonfun$run$5(Example.scala:28)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:200)
	at zio.internal.FiberContext.run(FiberContext.scala:115)
	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:530)
	at searler.zswing.flasher.Example.run(Example.scala:28)"
```

**Comment by searler** [comment]
The added logger was only defined for String and ignored the Die instances.

**Comment by searler** [comment]
Functional logging setup

```

import zio.{Cause, FiberId, FiberRef, LogLevel, LogSpan, RuntimeConfigAspect, ZIO, ZIOAppDefault, ZLogger, ZTraceElement}

object Example extends ZIOAppDefault {

  val specialLogger: ZLogger[Cause[Any], Unit] =
    (
      trace: ZTraceElement,
      fiberId: FiberId,
      level: LogLevel,
      message: () => Cause[Any],
      context: Map[FiberRef.Runtime[_], AnyRef],
      spans: List[LogSpan],
      location: ZTraceElement
    ) => {
      try {
        System.err.println(message().prettyPrint)
        ()
      } catch {
        case t: Throwable => t.printStackTrace()
      }
    }

  override def hook = RuntimeConfigAspect.addLogger(specialLogger)

  val run =
    for {
      f <- ZIO.succeed(throw new Exception("bang")).fork
      _ <- f.await
    } yield ()


}
```

**Comment by olivierdeckers** [comment]
You can configure the log level at which these errors are logged:

```
object Example extends ZIOAppDefault:

  override val bootstrap: ZLayer[ZIOAppArgs, Any, Any] =
       Runtime.setUnhandledErrorLogLevel(LogLevel.Error)

```
