### ISSUE TITLE
Infinite STM transaction

### ISSUE THREAD

**Issue by durban** [zio/zio#6324]
Version `2.0.0-RC2`, Scala `3.1.1`.

The stream `intStream` in the following random generator program can "freeze" due to an STM transaction `nextInt` running infinitely. This is in turn due to STM reading inconsistent values when there is a concurrent transaction (`setMinMax`).

```scala
package com.example

import zio.{ ZIO, Duration }
import zio.stm._
import zio.stream.ZStream

/**
 * A generator of pseudorandom stream
 * of `Int`s, with transactionally
 * adjustable minimum and maximum.
 */
final class RandomInts(
  seedRef: TRef[Long], // current seed
  minIncl: TRef[Int],  // current origin
  maxExcl: TRef[Int],  // current bound
) {

  private[this] final val gamma =
    0x9e3779b97f4a7c15L

  /** Generates the next random `Int` */
  final def nextInt: STM[Nothing, Int] = {
    seedRef.get.flatMap { (sd: Long) =>
      minIncl.get.flatMap { (origin: Int) =>
        maxExcl.get.flatMap { (bound: Int) =>
          val (newSeed, r) = computeNextInt(sd, origin, bound)
          seedRef.set(newSeed).as(r)
        }
      }
    }
  }

  /**
   * Transactionally adjusts the min/max of the random `Int`s
   *
   * Invariant: minInclusive < maxExclusive
   */
  final def setMinMax(
    minInclusive: Int,
    maxExclusive: Int
  ): STM[IllegalArgumentException, Unit] = {
    if (minInclusive < maxExclusive) {
      minIncl.set(minInclusive) *> maxExcl.set(maxExclusive)
    } else {
      ZSTM.fail(new IllegalArgumentException)
    }
  }

  /**
   * An infinite stream of random integers,
   * always between the current min/max.
   */
  final def intStream: ZStream[Any, Nothing, Int] = {
    ZStream.repeatZIO(nextInt.commit)
  }

  private[this] final def computeNextInt(
    seed: Long,
    origin: Int,
    bound: Int
  ): (Long, Int) = {
    val n: Int = bound - origin
    val m: Int = n - 1
    if ((n & m) == 0) {
      // power of two
      val s: Long = seed + gamma
      (s, (mix32(s) & m) + origin)
    } else if (n > 0) {
      var s: Long = seed
      var r: Int = -1
      while ({
        s += gamma
        val u: Int = mix32(s) >>> 1
        r = u % n
        (u + m - r) < 0
      }) {}
      (s, r + origin)
    } else {
      var s: Long = seed
      var r: Int = -1
      while ({
        s += gamma
        r = mix32(s)
        (r < origin) || (r >= bound)
      }) {}
      (s, r)
    }
  }

  private[this] final def mix32(s: Long): Int = {
    var z: Long = s
    z = (z ^ (z >>> 33)) * 0x62a9d9ed799705f5L
    (((z ^ (z >>> 28)) * 0xcb24d0a5c88c35b3L) >>> 32).toInt
  }
}

object RandomInts {
  def mk(
    seed: Long,
    minIncl: Int = 0,
    maxExcl: Int = 42
  ): ZIO[Any, IllegalArgumentException, RandomInts] = {
    TRef.make(seed).flatMap { seedRef =>
      TRef.make(0).flatMap { origin =>
        TRef.make(Int.MaxValue).flatMap { bound =>
          val ri = new RandomInts(seedRef, origin, bound)
          ri.setMinMax(minInclusive = minIncl, maxExclusive = maxExcl).as(ri)
        }
      }
    }.commit
  }
}
```

The test to reproduce the infinite loop:
```scala
package com.example

import zio.{ ZIO, Duration }
import zio.stm._
import zio.stream.ZStream

final class RandomTest extends munit.FunSuite {

  // this works fine:
  test("simple test") {
    val tsk = for {
      rng <- RandomInts.mk(42L, minIncl = 0, maxExcl = 42)
      fib <- rng
        .intStream
        .mapZIO { i => ZIO.attempt(println(i)) }
        .take(64L)
        .throttleShape(1L, Duration.fromMillis(100L))(_.length.toLong)
        .foreach(_ => ZIO.unit)
        .fork
      _ <- ZIO.sleep(Duration.fromMillis(3000L))
      _ <- rng.setMinMax(1000, 4200).commit
      _ <- fib.join
    } yield ()
    zio.Runtime.default.unsafeRunTask(tsk)
  }

  // this test never finishes:
  test("stress test") {
    val tsk = for {
      rng <- RandomInts.mk(42L, minIncl = 0, maxExcl = 42)
      tsk1 = rng
        .intStream
        .take(64L)
        .foreach(_ => ZIO.unit)
      tsk2 = {
        val ta = rng.setMinMax(1000, 4200).commit
        val tb = rng.setMinMax(0, 42).commit
        (ta *> ZIO.yieldNow *> tb).replicateZIO(64)
      }
      fib1 <- (ZIO.yieldNow *> tsk1).fork
      fib2 <- (ZIO.yieldNow *> tsk2).fork
      _ <- fib1.join
      _ <- fib2.join
    } yield ()
    zio.Runtime.default.unsafeRunTask(tsk.replicateZIO(512))
  }
}
```

The infinitely running JVM thread has the following stacktrace:
```
        at com.example.RandomInts.computeNextInt(RandomInts.scala:85)
        at com.example.RandomInts.nextInt$$anonfun$1$$anonfun$1$$anonfun$1(RandomInts.scala:26)
        at com.example.RandomInts.nextInt$$anonfun$1$$anonfun$1$$anonfun$adapted$1(RandomInts.scala:27)
        at com.example.RandomInts$$Lambda$6339/0x0000000841b18840.apply(Unknown Source)
        at zio.stm.ZSTM.zio$stm$ZSTM$$run(ZSTM.scala:892)
        at zio.stm.ZSTM$internal$.tryCommitSync(ZSTM.scala:2054)
        at zio.stm.ZSTM$.atomically$$anonfun$8$$anonfun$7(ZSTM.scala:994)
        at zio.stm.ZSTM$$$Lambda$6189/0x0000000841a6d040.apply(Unknown Source)
        at zio.internal.FiberContext.runUntil(FiberContext.scala:303)
        at zio.internal.FiberContext.run(FiberContext.scala:115)
        at zio.internal.ZScheduler$$anon$2.run(ZScheduler.scala:151)
```

**Comment by adamgfraser** [comment]
So the issue here is that `computeNextInt` loops forever if `origin` is greater than `bound` without ever yielding control back to the runtime.

As we have previously discussed, the guarantee of STM is not that an inconsistent value can never be observed, but that a transaction based on an inconsistent value can never be committed. We also previously implemented functionality in #6240 to check if a transaction is based on an inconsistent state at regular intervals. However, this requires that a function eventually return control to the runtime, for example by executing a `flatMap`. There is no way in general that we can interrupt arbitrary third party code.

This is analogous to ZIO where interruption can only be observed between evaluation of third party effects. For example the snippet below will never terminate:

```scala
for {
  fiber <- ZIO.succeed { while(true) { () } }.fork
  _      <- fiber.interrupt 
} yield ()
```

Even though the main fiber attempts to interrupt the forked fiber, that interruption is never observed because the loop never returns control to the runtime. In most cases this is not an issue because idiomatic ZIO code typically frequently returns control to the runtime, but can be an issue in some situations where we need to explicitly check for interruption.

I am inclined to think the solution here is to either refactor the code to yield control back to the runtime or to just check that the boundaries are valid before entering the tight loop. For example, refactoring the implementation of `nextInt` as follows resolves the problem:

```scala
    private[this] final def computeNextInt(
      seed: Long,
      origin: Int,
      bound: Int
    ): ZSTM[Any, Nothing, (Long, Int)] =
      if (origin >= bound) ZSTM.retry
      else ZSTM.succeed(???)
```

**Comment by durban** [comment]
Okay, so, if I write `ZIO.succeed { while(true) { () } }`, that's clearly my fault. (It's also probably easier to find the bug.)

In this case, it's not that clear that it's my fault. But sure, it can be said, that it is.

Which means, that every invariant have to be re-checked manually (since the built-in consistency check in the runtime may never happen). Basically, I can't trust my own invariants. Or, alternatively, every loop must always (eventually) guarantee to return control to the runtime. Returning control is by any STM operation (flatMap, get, set, retry, fail, ...) I guess. (I think this is what you wrote, I'm just rephrasing it to make sure I understood correctly.)

**Comment by adamgfraser** [comment]
Yeah, I think most of the time when you are continuing an STM transaction you are doing some other STM effect, for example getting another item from a transactional queue, incrementing another transactional variable, or whatever. In that case you don't have to do anything because the runtime will automatically terminate any transaction based on an inconsistent state for you.

If you are going to call a function that never yields back to the runtime and might not terminate for some inputs then you should check those inputs at the beginning of the function, which is probably best practice anyway, since the function isn't a total function. For example in the situation above the most natural implementation might be for `computeNextInt` to fail if the bounds are invalid and then `nextInt` could handle that failure by retrying.

**Comment by jdegoes** [comment]
I think we could add `STM.invariant(min <= max)` that would not allow progressing beyond that point if the invariant is not satisfied. If that is of interest, please open up a ticket to describe this feature! 🙏 

I am not sure it's correct to insert `STM.retry` in an implementation for `STM.invariant`, since the guarantee of retry is that the transaction will retry when the variables involved are changed; but if observed inconsistently, I am not sure if this satisfies the current definition of "changed". We should investigate and add some test cases around this (if they don't already exist).
