### ISSUE TITLE
Incomplete fiber name in the stack trace

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6407]
When we have parallel errors like the following example:

```scala
import zio._

object MainApp extends ZIOAppDefault {
  def run = ZIO.fail("Oh!") <&> ZIO.fail("Uh!") <&> ZIO.dieMessage("Boom!")
}
```

In the first line of the stack trace, the fiber name seems incomplete: "zio-fiber-"

```scala
timestamp=2022-03-09T08:08:36.863795997Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-13" java.lang.InterruptedException: Interrupted by thread "zio-fiber-"
	at <empty>.MainApp.run(MainApp.scala:4)
Exception in thread "zio-fiber-15" java.lang.RuntimeException: Boom!
	at <empty>.MainApp.run(MainApp.scala:4)"
```

**Comment by adamgfraser** [comment]
@khajavi Thanks for reporting! Resolved in #6408.
