### ISSUE TITLE
Cause.Unified and Cause.prettyPrint do not capture Throwable.cause 

### ISSUE THREAD

**Issue by domartynov** [zio/zio#6511]
Not sure if it's the right solution, but can we add `cause: Unified` to `Unified` and adjust `Cause.prettyPrint` and maybe `Unified.toThrowable` accordingly? 

Btw `Unified.toThrowable` does not expose `className`, not sure how critical this is in practice for exception like:
```scala
class FooException(cause: Throwable) extend Exception(cause)
```
It seems most of information captured but such exception is lost.

**Comment by adamgfraser** [comment]
I don't think this is right. With the following code:

```scala
import zio._

object Example extends ZIOAppDefault {

  class FooException(cause: Throwable) extends Exception(cause)

  val cause = Cause.die(new FooException(new Exception("cause")))

  val run =
    Console.printLine(cause.prettyPrint)
}
```

The stack trace printed is:

```
Exception in thread "zio-fiber-" Example$FooException: java.lang.Exception: cause
  at Example$.<clinit>(Example.scala:7)
  at Example.main(Example.scala)
```

So both the cause and the class name are rendered.

**Comment by domartynov** [comment]
Yeah, sorry that I didn't include a sample first. It seems in the code below we loose the cause stack trace:
```scala
object Example extends ZIOAppDefault {
  val run = ZIO.succeed(m0)

  def m0 = {
    m1
  }

  def m1 = try {
    m2
  } catch {
    case t: Throwable => throw new FooException(t)
  }

  def m2 = {
    m3
  }

  def m3 = {
    throw new Exception("Cause Error!")
  }
}

class FooException(cause: Throwable) extends Exception(cause)

//class FooException(cause: Throwable) extends Exception {
//  initCause(cause)
//}

object ExampleJava {
  def main(args: Array[String]): Unit = Example.m0
}
```
`Example` outputs:
```
timestamp=2022-04-01T12:33:03.879173Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-2" example.FooException: java.lang.Exception: Cause Error!
	at example.Example$.m1(CauseSpec.scala:15)
	at example.Example$.m0(CauseSpec.scala:9)
	at example.Example$.$anonfun$run$1(CauseSpec.scala:6)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:242)
	at zio.internal.FiberContext.run(FiberContext.scala:116)
	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:539)"
```
add missing `at example.Example$.m3(CauseSpec.scala:29)` compared to `ExampleJava` ouput:
```
Exception in thread "main" example.FooException: java.lang.Exception: Cause Error!
	at example.Example$.m1(CauseSpec.scala:21)
	at example.Example$.m0(CauseSpec.scala:15)
	at example.ExampleJava$.main(CauseSpec.scala:41)
	at example.ExampleJava.main(CauseSpec.scala)
Caused by: java.lang.Exception: Cause Error!
	at example.Example$.m3(CauseSpec.scala:29)
	at example.Example$.m2(CauseSpec.scala:25)
	at example.Example$.m1(CauseSpec.scala:19)
	... 3 more
```
And I hit another case where the cause exception is attached via `initCause` (see the commented block, not sure why there is a difference) but the ZIO output is missing any details of the cause exception in this case:
```
timestamp=2022-04-01T12:38:53.166458Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-2" example.FooException: null
	at example.Example$.m1(CauseSpec.scala:15)
	at example.Example$.m0(CauseSpec.scala:9)
	at example.Example$.$anonfun$run$1(CauseSpec.scala:6)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:242)
	at zio.internal.FiberContext.run(FiberContext.scala:116)
	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:539)"
```
vs
```
Exception in thread "main" example.FooException
	at example.Example$.m1(CauseSpec.scala:15)
	at example.Example$.m0(CauseSpec.scala:9)
	at example.ExampleJava$.main(CauseSpec.scala:35)
	at example.ExampleJava.main(CauseSpec.scala)
Caused by: java.lang.Exception: Cause Error!
	at example.Example$.m3(CauseSpec.scala:23)
	at example.Example$.m2(CauseSpec.scala:19)
	at example.Example$.m1(CauseSpec.scala:13)
	... 3 more
```

**Comment by adamgfraser** [comment]
Thanks for the example! Will take a look!
