### ISSUE TITLE
2.0.0-RC5 Defect in zio.ZEnvironment

### ISSUE THREAD

**Issue by ya-goodfella** [zio/zio#6711]
scala 2.13 ([scastie](https://scastie.scala-lang.org/Cl339mXrTY6TJ3o60wCrEg))

```scala
import zio._

case object Main extends ZIOAppDefault {
  val a: "a" = "a"
  type aType = a.type
  
  def run = Console.printLine(implicitly[a.type <:< "a"]) *>
            Console.printLine(implicitly["a" <:< a.type]) *>
            Console.printLine(implicitly["a" =:= a.type]) *>
            ZIO.serviceWithZIO[a.type](Console.printLine(_))
              .provideService["a"](a)
}
```

output

```
generalized constraint
generalized constraint
generalized constraint
timestamp=2022-04-24T18:53:15.855600552Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-2" java.lang.Error: Defect in zio.ZEnvironment: Could not find Main::a inside ZEnvironment(Map(Scope -> (zio.Scope$$anon$4@2757e422,2), ZIOAppArgs -> (ZIOAppArgs(Chunk()),3), "a" -> (a,4)))
	at zio.ZEnvironment.unsafeGet(ZEnvironment.scala:125)
	at zio.ZIO$ServiceWithZIOPartiallyApplied$.$anonfun$apply$13(ZIO.scala:4816)
	at zio.ZIO$FlatMap.apply(ZIO.scala:5260)
	at zio.ZIO$FlatMap.apply(ZIO.scala:5249)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:887)
	at zio.internal.FiberContext.run(FiberContext.scala:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:538)
	at <empty>.Main.run(main.scala:11)"
```

**Comment by domdorn** [comment]
so you say because the JVM is supposed to inline "a" above, that the "a" used in provideService has to be the same?
not sure its working that way, but `provideService` is gone after RC5 anyway..

**Comment by ya-goodfella** [comment]
> so you say because the JVM is supposed to inline "a" above, that the "a" used in provideService has to be the same?
> 
> not sure its working that way, but `provideService` is gone after RC5 anyway.. 

That's not about inlining actually, it's about generated type tags. Seems like type tags generated by izumi violates the subtyping roles available from the Scala compiler itself - ZEnvironment checks if it has some element that is a subtype of requested type, but fails to do so when there is a literal type and/or value type involved, where compiler still able to generate it's `<:<` instances (notice implicitly calls above).

I'll try to reduce this example to a smaller one involving just type tags and possibly create an upstream issue. Anyway, there shouldn't be the case for an zio error in runtime if it compiles successfully.

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/izumi-reflect/issues/284
