### ISSUE TITLE
Better Logging When Blocking Pool Size Reached

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6800]
With the following code:

```scala
import zio._

object MainApp extends ZIOAppDefault {
  def run =
    ZIO.foreachParDiscard(1 to 2021)(_ =>
      ZIO.attempt {
        println(Thread.currentThread().getName)
        Thread.sleep(10000L)
      }
    )
}
```

The user will encounter the following error message:

```
zio-default-blocking-997
zio-default-blocking-998
zio-default-blocking-999
zio-default-blocking-1000
timestamp=2022-05-11T03:58:07.531723509Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-6" java.util.concurrent.RejectedExecutionException: Unable to run FiberContext(Runtime(2027,1652241487,<empty>.MainApp.run(MainApp.scala:6)))
	at zio.Executor.unsafeSubmitOrThrow(Executor.scala:84)
	at zio.internal.FiberContext.unsafeFork(FiberContext.scala:746)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:332)
	at zio.internal.FiberContext.run(FiberContext.scala:111)
	at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:415)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:518)
	at <empty>.MainApp.run(MainApp.scala:6)"
```

It might be better to log when the autoblocking starts working and also log the appropriate message why the application stopped.

**Comment by hearnadam** [comment]
Blocking pool no longer rejects tasks. See: #7387
