### ISSUE TITLE
NullPointerException when using ZChannel.mergeAllUnbounded in 2.0.0-RC6

### ISSUE THREAD

**Issue by shawjef3** [zio/zio#6870]
This is for ZIO 2.0.0-RC6 and Scala 2.13.8. I get this exception

```
timestamp=2022-05-27T13:36:12.502888Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-9" java.lang.NullPointerException: Cannot invoke "zio.stream.internal.ChannelExecutor.run(Object)" because the return value of "zio.stream.internal.ChannelExecutor$ChannelState$Read.upstream()" is null
	at zio.stream.internal.ChannelExecutor$.read$1(ChannelExecutor.scala:926)
	at zio.stream.internal.ChannelExecutor$.readUpstream(ChannelExecutor.scala:960)
	at zio.stream.ZChannel.interpret$2(ZChannel.scala:968)
	at zio.stream.ZChannel.$anonfun$toPull$12(ZChannel.scala:974)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:284)
	at zio.internal.FiberContext.run(FiberContext.scala:111)
	at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:415)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:518)
	at <empty>.Minimized.pooledSink.merged(Minimized.scala:18)"
```

from

```scala
object Minimized extends zio.ZIOAppDefault {
  import zio._
  import zio.stream._

  def mergedSink[E, In]: ZSink[Any, E, In, Unit, Unit] = {
    val channel: ZChannel[Any, E, Chunk[In], Any, E, Chunk[Unit], Unit] = {
      lazy val process: ZChannel[Any, E, Chunk[In], Any, E, Chunk[Unit], Unit] =
        ZChannel.readWithCause(
          _ => ZChannel.fromZIO(ZIO.unit) *> process,
          (halt: Cause[E]) => ZChannel.failCause(halt),
          _ => ZChannel.unit
        )
      process
    }

    val merged: ZChannel[Any, Nothing, Chunk[In], Any, E, Chunk[Unit], Unit] =
      ZChannel.mergeAllUnbounded(ZChannel.writeAll(channel)).unit

    new ZSink[Any, E, In, Unit, Unit](merged)
  }

  override def run: ZIO[ZIOAppArgs & Scope, Any, Any] = {
    ZStream.from(()).run(mergedSink)
  }

}
```
.

Replacing `new ZSink[Any, E, In, Unit, Unit](merged)` with `new ZSink[Any, E, In, Unit, Unit](channel)`, so that it doesn't use `ZChannel.mergeAllUnbounded`, clears the exception. So I suspect a bug with `ZChannel.mergeAllUnbounded`.

**Comment by vigoo** [comment]
Thank you, checking
