### ISSUE TITLE
StackOverflowError when using ZChannel.mergeAll

### ISSUE THREAD

**Issue by shawjef3** [zio/zio#6976]
This is with ZIO 2.0.0, Scala 2.13.8, and Java 8 or 17.

```
import zio._
import zio.stream._

object StackOverflow extends ZIOAppDefault {
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    def parSink[R, Err, In, L] =
      ZSink.fromChannel[R, Err, In, L, Any](ZChannel.mergeAll(ZChannel.writeChunk(Chunk.fill(32)(ZSink.drain.channel)), 32, 1))

    ZStream.unit.forever.run(parSink)
  }
}
```

gives

```
Exception in thread "ZScheduler-Worker-10" java.lang.StackOverflowError
	at java.base/java.lang.String.indexOf(String.java:2421)
	at java.base/java.lang.String.indexOf(String.java:2378)
	at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:157)
	at java.base/sun.net.www.protocol.file.Handler.parseURL(Handler.java:67)
	at java.base/java.net.URL.<init>(URL.java:703)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1239)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:319)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:757)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at zio.internal.IsFatal.apply(IsFatal.scala:8)
	at zio.internal.IsFatal.apply$(IsFatal.scala:6)
	at zio.internal.IsFatal$Single.apply(IsFatal.scala:29)
	at zio.internal.FiberRuntime.isFatal(FiberRuntime.scala:656)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1105)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:874)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:874)
...
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:874)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:324)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:447)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:217)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:415)
**** WARNING ****
Catastrophic error encountered. Application not safely interrupted. Resources may be leaked. Check the logs for more details and consider overriding `Runtime.reportFatal` to capture context.
```

**Comment by hearnadam** [comment]
I couldn't repro. Feel free to reopen.
