### ISSUE TITLE
Wrong logger used for uncaught failures in ZIOAppDefault

### ISSUE THREAD

**Issue by kluen** [zio/zio#7044]
I have created a ticket for this issue before in zio-logging: https://github.com/zio/zio-logging/issues/444
This PR was supposed to fix the problem: https://github.com/zio/zio/pull/6714

However, with the 2.0.0 releases it still seems to be an issue.

Here's some scala-cli code to reproduce:
```
//> using scala "2.13"
//> using lib "dev.zio::zio:2.0.0"
//> using lib "dev.zio::zio-logging:2.0.0"
//> using lib "dev.zio::zio-logging-slf4j:2.0.0"
//> using lib "ch.qos.logback:logback-classic:1.2.11"

import zio._
import zio.logging.backend._

object App extends ZIOAppDefault {
  def run =
    program.provide(Runtime.removeDefaultLoggers, slf4jLogging)

  lazy val program =
    ZIO.logInfo("Hey there!") *> ZIO.fail(new RuntimeException("Oh no!"))

  lazy val slf4jLogging =
    SLF4J.slf4j(LogLevel.Info)
}

App.main(Array()) // ignore this, this is just here to get ZIOAppDefault work with scala-cli
```

The successful message is logged via SLF4J whereas the failure uses the default log format.
```
18:11:37.735 [ZScheduler-Worker-12] INFO zio-slf4j-logger - timestamp=2022-07-06T18:11:37.682045+02:00 level=INFO thread=zio-fiber-6 message="Hey there!"
timestamp=2022-07-06T16:11:37.760466Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-6" java.lang.RuntimeException: java.lang.RuntimeException: Oh no!
	at <empty>.Main.App.program(Main.scala:20)
	at <empty>.Main.App.run(Main.scala:17)"
```

**Comment by adamgfraser** [comment]
@kluen I just submitted a PR to fix an issue here. However, note that if you want the logging of unhandled errors in `ZIOAppDefault` to use your logger you need to install it as part of the `bootstrap` layer in `ZIOAppDefault`.

**Comment by kluen** [comment]
Thanks, @adamgfraser! 

Ok, so when #7046 is merged would this be the correct way to use it? I was unable to find documentation on the `bootstrap` mechanism in `ZIOAppDefault`. Currently this solution has the exact same behaviour as the code above.

```
//> using scala "2.13"
//> using lib "dev.zio::zio:2.0.0"
//> using lib "dev.zio::zio-logging:2.0.0"
//> using lib "dev.zio::zio-logging-slf4j:2.0.0"
//> using lib "ch.qos.logback:logback-classic:1.2.11"

import zio._
import zio.logging.backend._

object App extends ZIOAppDefault {

  override def run =
    ZIO.logInfo("Hey there!") *> ZIO.fail(new RuntimeException("Oh no!"))

  override val bootstrap =
    Runtime.removeDefaultLoggers ++ SLF4J.slf4j(LogLevel.Info)
}

App.main(Array()) // ignore this, this is just here to get ZIOAppDefault work with scala-cli
```

**Comment by adamgfraser** [comment]
@kluen That's right!
