### ISSUE TITLE
mdoc Cannot Print The Proper Error Message Produced By ZLayer Macro

### ISSUE THREAD

**Issue by khajavi** [zio/zio#7102]
When I have the following snippet of code inside the documentation:

```scala mdoc:compile-only
import zio._

trait A

object MainApp extends zio.ZIOAppDefault {
  val a = ZLayer.succeed(new A {})

  def run = ZIO.service[A]
}
```

If I compile the above doc using `sbt mdoc` I will get the following errors:

```
info: Compiling 1 file to /home/milad/sources/scala/multi-module-mdoc/website/docs
mdoc.internal.cli.FileException: /home/milad/sources/scala/multi-module-mdoc/documentation/zio-docs-foo-tutorial/docs/foo-tutorial.md
Caused by: java.lang.IllegalArgumentException: Unknown ansi-escape [2m at index 232 inside string cannot be parsed into an fansi.Str
        at fansi.ErrorMode$Throw$.handle(Fansi.scala:440)
        at fansi.ErrorMode$Throw$.handle(Fansi.scala:428)
        at fansi.Str$.apply(Fansi.scala:280)
        at fansi.Str$.implicitApply(Fansi.scala:227)
        at mdoc.internal.io.ConsoleReporter.error(ConsoleReporter.scala:52)
        at mdoc.internal.io.ConsoleReporter.error(ConsoleReporter.scala:48)
        at mdoc.internal.markdown.MarkdownCompiler.reportMessage(MarkdownCompiler.scala:226)
        at mdoc.internal.markdown.MarkdownCompiler.$anonfun$report$2(MarkdownCompiler.scala:213)
        at mdoc.internal.markdown.MarkdownCompiler.$anonfun$report$2$adapted(MarkdownCompiler.scala:186)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at mdoc.internal.markdown.MarkdownCompiler.report(MarkdownCompiler.scala:186)
        at mdoc.internal.markdown.MarkdownCompiler.compileSources(MarkdownCompiler.scala:115)
        at mdoc.internal.markdown.MarkdownCompiler.compile(MarkdownCompiler.scala:127)
        at mdoc.internal.markdown.MarkdownBuilder$.buildDocument(MarkdownBuilder.scala:32)
        at mdoc.internal.markdown.Processor.processScalaInputs(Processor.scala:189)
        at mdoc.internal.markdown.Processor.processScalaInputs(Processor.scala:156)
        at mdoc.internal.markdown.Processor.processDocument(Processor.scala:54)
        at mdoc.internal.markdown.Markdown$.toMarkdown(Markdown.scala:137)
        at mdoc.internal.cli.MainOps.handleMarkdown(MainOps.scala:83)
        at mdoc.internal.cli.MainOps.handleFile(MainOps.scala:111)
        at mdoc.internal.cli.MainOps.$anonfun$generateCompleteSite$1(MainOps.scala:157)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at mdoc.internal.cli.MainOps.generateCompleteSite(MainOps.scala:156)
        at mdoc.internal.cli.MainOps.run(MainOps.scala:178)
        at mdoc.internal.cli.MainOps$.process(MainOps.scala:270)
        at mdoc.Main$.process(Main.scala:26)
        at mdoc.Main$.process(Main.scala:21)
        at mdoc.Main$.main(Main.scala:16)
        at mdoc.Main.main(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.Run.invokeMain(Run.scala:143)
        at sbt.Run.execute$1(Run.scala:93)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
        at sbt.Run$.executeSuccess(Run.scala:186)
        at sbt.Run.runWithLoader(Run.scala:120)
        at sbt.Defaults$.$anonfun$bgRunMainTask$7(Defaults.scala:1951)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
info: Compiled in 1.95s (1 error)
Waiting for file changes (press enter to interrupt)
```

It prevents me to find the problem in the documentation easily, sometimes I need to compile the snippets outside the `mdoc` facility to find out what the problem is. 

I'm not sure if it is related to our macro for ZLayers or something related to the `mdoc`. But, probably it might be fixed if we choose proper character settings for printing errors in the macro for ZLayers.

**Comment by khajavi** [comment]
@kitlangton Could you please take a look?

**Comment by hearnadam** [comment]
I think this is an issue with the color. Can we add a ZLayer flag to avoid printing colors?

**Comment by hearnadam** [comment]
Also probably related to #6225
