### ISSUE TITLE
Test initialization failure do not reported to sbt

### ISSUE THREAD

**Issue by darl** [zio/zio#7141]
If test failed to initialise it did not reported to `sbt.testing.EventHandler` and overall test run treated as success.

I made sample project:
https://github.com/darl/zio2-example/blob/main/src/test/scala/dev/zio/quickstart/MainSpec.scala

```bash
$ sbt test && echo 'success' || echo 'failed'
[info] welcome to sbt 1.7.1 (Homebrew Java 11.0.15)
[info] loading global plugins from /Users/darl/.sbt/1.0/plugins
[info] loading settings for project zio-quickstart-hello-world-build-build from metals.sbt ...
[info] loading project definition from /Users/darl/projects/zio-quickstart-hello-world/project/project
[info] loading settings for project zio-quickstart-hello-world-build from metals.sbt ...
[info] loading project definition from /Users/darl/projects/zio-quickstart-hello-world/project
[success] Generated .bloop/zio-quickstart-hello-world-build.json
[success] Total time: 0 s, completed Jul 28, 2022, 10:42:23 PM
[info] loading settings for project zio-quickstart-hello-world from build.sbt ...
[info] set current project to zio-quickstart-hello-world (in build file:/Users/darl/projects/zio-quickstart-hello-world/)
+ Main
    - sampleTest
      Exception in thread "zio-fiber-48" java.lang.RuntimeException: boom
      	at dev.zio.quickstart.MainSpec$.$init$$$anonfun$1(MainSpec.scala:9)
      	at dev.zio.quickstart.MainSpec$.intLayer.macro(MainSpec.scala:9)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
[info] No tests were executed
[success] Total time: 2 s, completed Jul 28, 2022, 10:42:24 PM
success
```

**Comment by adamgfraser** [comment]
@darl Thanks for reporting!

@swoogles Can you take a look?

**Comment by swoogles** [comment]
Thanks @darl , just submitted a PR that resolves this
