### ISSUE TITLE
zio-test: Comparing using orderingToOrdered in assertTrue causes compilation error

### ISSUE THREAD

**Issue by andrzejressel** [zio/zio#7182]
Tested on ZIO 2.0.0 and latest ZIO 2 snapshot

Examples:

Scala 2: https://scastie.scala-lang.org/X86aECF8Rn2zR3SsmWBW1g
Scala 3: https://scastie.scala-lang.org/6UW3lTI7RI6ErOuEACPqNA

Code:
```scala
import zio.test._
import zio._

import java.time.Instant
import scala.math.Ordered.orderingToOrdered

val instant = Instant.now()

println(instant > instant)
assertTrue(instant > instant)
```

Scala 2 error:
```
diverging implicit expansion for type scala.math.Ordering.AsComparable[scala.math.Ordered[java.time.Instant]]
starting with method orderingToOrdered in object Ordered
```

Scala 3 error:
```
Exception occurred while executing macro expansion.
java.lang.Error: NO
	at zio.test.SmartAssertMacros$.transform(Macros.scala:157)
	at zio.test.SmartAssertMacros$.smartAssertSingle_impl(Macros.scala:208)
	at zio.test.SmartAssertMacros$.smartAssert_impl(Macros.scala:219)
	at zio.test.SmartAssertMacros$.smartAssert(Macros.scala:31)
```

After commenting out `assertTrue`, `println` prints correct value - `false`

**Comment by adamgfraser** [comment]
@kitlangton Can you take a look?

**Comment by hearnadam** [comment]
Scala 2 is still broken:

> diverging implicit expansion for type scala.math.Ordering.AsComparable[scala.math.Ordered[java.time.Instant]]
starting with method orderingToOrdered in object Ordered

https://scastie.scala-lang.org/cMNjdYBsSAanUchG0VyfBw

But Scala 3 works: https://scastie.scala-lang.org/5yCIcb46Tj6sFsHGvoxNoA
