### ISSUE TITLE
SmartAssertion assertTrue macro failure

### ISSUE THREAD

**Issue by BardurArantsson** [zio/zio#7198]
Hi, it appears that the assertTrue macro doesn't quite handle comparing a literal Int to a Long on Scala 3.1.3. This might be an upstream bug, but I thought I'd raise it here.

This is a test which triggers the compilation failure:

```
test("foo") {
  for {    
    x <- ZIO.succeed(1L)
  } yield assertTrue(x == 1)
}
````

The compiler spits out

```
[error] 33 |          } yield assertTrue(
[error]    |                  ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.Exception: Expr cast exception: 1
[error]    |of type: 1
[error]    |did not conform to type: scala.Long
[error]    |
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:73)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:116)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:115)
[error]    |	at zio.test.SmartAssertMacros$.transform$$anonfun$16(Macros.scala:165)
[error]    |	at zio.test.SmartAssertMacros$.transform$$anonfun$adapted$15(Macros.scala:165)
```

(etc.)

Not a big deal, obviously, but it would probably be nice for ergonomics if the Int literal were automatically promoted to a Long.

**Comment by adamgfraser** [comment]
We should either widen or fail the compilation because the types do not match but we definitely shouldn't crash.

**Comment by Wosin** [comment]
If @kitlangton  is busy I'm happy to take a look  ;))

**Comment by adamgfraser** [comment]
@Wosin That would be great!

**Comment by 987Nabil** [comment]
I encountered a similar problem. In case you have a Scala 3 enum

```scala
enum MyEnum:
  case MyCase(i:Int)
```
the macro fails if you have one side with the explicit subtype and one with the general enum type
```
val subType: MyEnum.MyCase = ???
val enumType: MyEnum = ???
assertTrue(subType == enumType)
```

I think widen should be the way to go.

**Comment by Wosin** [comment]
I think I got that for `==` operator, but it's trickier for all inequality operators as they are summoning `Ordering` to the scope and I have no idea how to make that work with widening. Any ideas @adamgfraser  ??

**Comment by hearnadam** [comment]
This works in latest version: https://scastie.scala-lang.org/hdipTPWsTOC7Ld4zbacPLQ
