### ISSUE TITLE
StackOverflowError when running a test with getting getResource and using assertTrue 

### ISSUE THREAD

**Issue by leonfed** [zio/zio#7210]
The following code produces StackOverflowError

```
object Test extends DefaultRunnableSpec {

  val elem = XML.load(getClass.getResourceAsStream("/smth.xml"))

  override def spec: ZSpec[TestEnvironment, Any] = 
    suite("Test")(
      test("get resource") {
        assertTrue(elem.toString == "<a>123</a>")
      }
    )
}
```

```
java.lang.StackOverflowError
	at scala.collection.immutable.Seq.iterableFactory(Seq.scala:24)
	at scala.collection.immutable.Seq.iterableFactory$(Seq.scala:24)
	at scala.xml.NodeSeq.iterableFactory(NodeSeq.scala:51)
	at scala.xml.NodeSeq.iterableFactory(NodeSeq.scala:51)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:88)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.xml.NodeSeq.map(NodeSeq.scala:51)
	at zio.test.PrettyPrint$.apply(PrettyPrint.scala:18)
	at zio.test.PrettyPrint$.$anonfun$apply$2(PrettyPrint.scala:18)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.xml.NodeSeq.map(NodeSeq.scala:51)
	at zio.test.PrettyPrint$.apply(PrettyPrint.scala:18)
	at zio.test.PrettyPrint$.$anonfun$apply$2(PrettyPrint.scala:18)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.xml.NodeSeq.map(NodeSeq.scala:51)
	at zio.test.PrettyPrint$.apply(PrettyPrint.scala:18)
	...
```

Also I realized two interesting facts
1) StackOverflowError is happens only if test fails. If file "smth.xml" contains `<a>123</a>` the test will complete successfully.
2) If I use `assert(elem.toString)(equalTo("<a>1234</a>"))` instead of assertTrue, StackOverflowError doesn't happen (even if file doesn't contains `<a>123</a>`)

**Comment by adamgfraser** [comment]
That is a very weird error!

**Comment by hearnadam** [comment]
@leonfed  is this still an issue on the latest version?
