### ISSUE TITLE
Accessing dependent types in the environment causes Defect in zio.Has at runtime

### ISSUE THREAD

**Issue by erdeszt** [zio/zio#7229]
I expected this code with a dependent type (`job.Impl`) to work but it causes a runtime error:

```scala
import zio._

abstract class Job(val name: String) {
  type Impl <: JobImpl
}

trait JobImpl {
  def run(): UIO[Unit]
}

final case class TestJob() extends Job("test") {
  type Impl = TestJobImpl
}

final case class TestJobImpl() extends JobImpl {
  override def run(): UIO[Unit] = ZIO.unit
}

object TestJobImpl {
  val layer: ULayer[Has[TestJobImpl]] = ZLayer.succeed(TestJobImpl())
}

object Main extends zio.App {
  def register(job: Job): URIO[Has[job.Impl], Unit] = {
    for {
      impl <- ZIO.service[job.Impl]
      _ <- UIO(println(s"It works: ${impl}"))
    } yield ()
  }
  
  def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    register(TestJob()).provideSomeLayer[ZEnv](TestJobImpl.layer).exitCode
  }
}
```

Scastie: https://scastie.scala-lang.org/h8axSmfTQW2rQzIlRGwwjA

Types are inferred correctly because if I remove the `provideSomeLayer` part I get a compile time error:
```
type mismatch;
 found   : zio.ZIO[zio.Has[TestJobImpl],Nothing,Unit]
 required: zio.URIO[zio.ZEnv,zio.ExitCode]
```

ZIO version: `1.0.16`

Stack trace:

```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: Could not find job::Impl|<Nothing..JobImpl> inside Map(package::Blocking::Service -> zio.blocking.package$Blocking$Service$$anon$1@19b809ed,
package::Random::Service -> RandomScala(scala.util.Random$@8bdf667),
package::System::Service -> zio.system.package$System$Service$$anon$1@2db08e46,
package::Clock::Service -> zio.clock.package$Clock$Service$$anon$1@357472e0,
package::Console::Service -> zio.console.package$Console$Service$$anon$1@7ffb13a5,
TestJobImpl -> TestJobImpl())
	at zio.Has$HasSyntax$.$anonfun$get$extension$2(Has.scala:181)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:228)
	at zio.Has$HasSyntax$.$anonfun$get$extension$1(Has.scala:181)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:683)
	at zio.Has$HasSyntax$.get$extension(Has.scala:179)
	at zio.ZIO$.$anonfun$service$1(ZIO.scala:4020)
	at zio.ZIO$AccessPartiallyApplied$.$anonfun$apply$9(ZIO.scala:4470)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:553)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:785)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)

Fiber:Id(1661245247162,8) was supposed to continue to:
  a future continuation at Main$$anonfun$register$1.apply(main.scala:26)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:291)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1088)
  a future continuation at zio.ZIO.exitCode(ZIO.scala:626)

Fiber:Id(1661245247162,8) execution trace:
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4470)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZManaged.use(ZManaged.scala:1089)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.ZManaged.flatMap(ZManaged.scala:337)
  at zio.ZManaged.flatMap(ZManaged.scala:337)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at zio.ZIO.zipWithPar(ZIO.scala:2310)
  at zio.ZIO$ZipLeftFn.apply(ZIO.scala:4499)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.Fiber.join(Fiber.scala:195)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.Fiber.join(Fiber.scala:195)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO.onInterrupt(ZIO.scala:1076)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4305)
  at zio.internal.FiberContext.await(FiberContext.scala:794)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2768)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2768)
  at zio.ZIO.zipWithPar(ZIO.scala:2310)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.internal.FiberContext.raceWithImpl(FiberContext.scala:230)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.internal.FiberContext.raceWithImpl(FiberContext.scala:227)
  at zio.ZIO.zipWithPar(ZIO.scala:2324)
  at zio.ZManaged.zipWithPar(ZManaged.scala:1194)
  at zio.ZIO.$amp$amp$amp(ZIO.scala:76)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged$.makeExit(ZManaged.scala:2084)
  at zio.ZManaged$ReleaseMap$$anon$1.add(ZManaged.scala:1379)
  at zio.ZManaged$ReleaseMap$$anon$1.addIfOpen(ZManaged.scala:1389)
  at zio.ZIO.flatten(ZIO.scala:700)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.ZManaged$.makeExit(ZManaged.scala:2083)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)

  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1375)
```

**Comment by erdeszt** [comment]
I found a manual workaround by passing the `Tag[job.Impl]` manually to `ZIO.service`. I've only tested with one DT in my env so I'm not sure if I'm going to hit limitation `#3` from here: https://github.com/zio/izumi-reflect#limitations down the line.

**Comment by adamgfraser** [comment]
@erdeszt Hi! Can you please open an issue in `izumi-reflect` for this?

**Comment by adamgfraser** [comment]
Closing this issue as the original usage where the path dependent type is still abstract is not supported. This can be done as shown above or there is another example in the linked issue.
