### ISSUE TITLE
ZIO 2.0.2: MatchError from ZIO.attempt when provided an empty trace

### ISSUE THREAD

**Issue by berman7** [zio/zio#7290]
When providing `Trace.empty` to a `ZIO.attempt(..)` that fails - we get a match error from ZIO internal code originating in `Trace`.

Reproduce as follows:

`Unsafe.unsafe { implicit u =>
          zio.Runtime.default.unsafe.run(
                 zio.ZIO.attempt(throw new RuntimeException())(zio.Trace.empty).ignore)
                    .getOrThrowFiberFailure()
 }`

throws a MatchError:
`Exception in thread "zio-fiber-0" scala.MatchError: 
	at zio.Trace$.equalIgnoreLocation(Trace.scala:28)
	at zio.StackTrace$.$anonfun$fromJava$2(StackTrace.scala:64)
	at zio.StackTrace$.$anonfun$fromJava$2$adapted(StackTrace.scala:64)
	at zio.Chunk$Arr.takeWhile(Chunk.scala:1695)
	at zio.StackTrace$.fromJava(StackTrace.scala:64)
	at zio.ZIOCompanionVersionSpecific.$anonfun$attempt$1(ZIOCompanionVersionSpecific.scala:110)
	at zio.internal.FiberRuntime.liftedTree5$1(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:964)
....
`

This was tested on ZIO 2.0.2 (2.0.0 works fine), looks like introduced in this [PR](https://github.com/zio/zio/pull/7016) released in 2.0.1.

**Comment by adamgfraser** [comment]
@berman7 Thanks for reporting! This will be fixed in the next release.

**Comment by berman7** [comment]
Awesome, thanks for the quick response.
