### ISSUE TITLE
zio-streams ZStream collectZIO stucked forever

### ISSUE THREAD

**Issue by dacr** [zio/zio#7301]
With zio-streams (2.0.0), also using zio-nio (2.0.0) , the following code stucks forever  because of the `.map(ts => ts -> file)` instruction within the `collectZIO` operation on a ZStream
```scala
  def parseTimestamp(timestamp: String): ZIO[Config, Throwable, LocalDateTime] =
    for {
      config   <- ZIO.service[Config]
      parsed   <- ZIO.attempt(config.timestampFormat.parse(timestamp))
      dateTime <- ZIO.attempt(parsed.query(LocalDateTime.from))
    } yield dateTime

  val transformLogic =
    for {
      config <- ZIO.service[Config]
      _      <- ZIO.log(s"scanning ${config.path}")
      path    = Path(config.path)
      mask    = config.fileMask
      files  <- Files
                  .list(path)
                  .map(_.toString)
                  .filterNot(_.contains("Trash"))
                  .collectZIO { case file @ mask(timestamp) => parseTimestamp(timestamp).map(ts => ts -> file) }
                  .tap(f => ZIO.log(s"found $f"))
                  .runCollect
      _      <- ZIO.log(s"found ${files.size} files")
    } yield ()
```
thanks to the logs I can see that it stucks on the first collected entry;  If I remove  `.map(ts => ts -> file)` it runs perfectly and returns the right amount of file for my first test case.

Also if I replace the `collectZIO` by a mapZIO it runs fine : 
```scala
                  //.collectZIO { case file @ mask(timestamp) => parseTimestamp(timestamp).map(ts => ts -> file) }
                  .mapZIO { case file @ mask(timestamp) => parseTimestamp(timestamp).map(ts => Some(ts -> file)) case _ => ZIO.succeed(None)}
```

Thread dump extract : 
```
"main" #1 prio=5 os_prio=0 cpu=348,77ms elapsed=14,31s tid=0x00007f0e5c018b50 nid=0xffeb in Object.wait()  [0x00007f0e63192000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.4/Native Method)
	- waiting on <0x0000000450000148> (a zio.internal.OneShot)
	at java.lang.Object.wait(java.base@17.0.4/Object.java:338)
	at zio.internal.OneShot.get(OneShot.scala:83)
	- locked <0x0000000450000148> (a zio.internal.OneShot)
	at zio.Runtime$UnsafeAPIV1.run(Runtime.scala:133)
	at zio.ZIOAppPlatformSpecific.main$$anonfun$1(ZIOAppPlatformSpecific.scala:48)
	at zio.ZIOAppPlatformSpecific$$Lambda$35/0x0000000800cdf0b8.apply(Unknown Source)
	at zio.Unsafe$.unsafeCompat(Unsafe.scala:36)
	at zio.ZIOAppPlatformSpecific.main(ZIOAppPlatformSpecific.scala:48)
	at zio.ZIOAppPlatformSpecific.main$(ZIOAppPlatformSpecific.scala:6)
	at photos$minusto$minusvideo$Photos$.main(photos-to-video.sc:38)
	at photos$minusto$minusvideo$.<clinit>(photos-to-video.sc:83)
	at photos$minusto$minusvideo_sc$.main(photos-to-video.sc:100)
	at photos$minusto$minusvideo_sc.main(photos-to-video.sc)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.4/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.4/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.4/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.4/Method.java:568)
	at scala.cli.runner.Runner$.main(Runner.scala:15)
	at scala.cli.runner.Runner.main(Runner.scala)


"zio-default-blocking-1" #24 daemon prio=5 os_prio=0 cpu=30,22ms elapsed=13,77s tid=0x00007f0dbc130a10 nid=0x1000f in Object.wait()  [0x00007f0da3af2000]
   java.lang.Thread.State: RUNNABLE
	at photos$minusto$minusvideo$Photos$$anon$2$$Lambda$631/0x0000000800e603d0.apply(Unknown Source)
	- waiting on the Class initialization monitor for photos$minusto$minusvideo$
	at zio.ZIO.map$$anonfun$1(ZIO.scala:927)
	at zio.ZIO$$Lambda$91/0x0000000800d409e8.apply(Unknown Source)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:874)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:324)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:447)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:217)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.4/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.4/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.4/Thread.java:833)

```

**Comment by dacr** [comment]
full source code is available here : https://gist.github.com/dacr/96450a3133218767e833cd490d180dcf

**Comment by adamgfraser** [comment]
@dacr Hi! I took a look at the implementation of `collectZIO` and did not observe any obvious issues. I also tested it with a variety of inputs and was not able to reproduce this issue. I also notice that one of the threads is waiting on a class initiation monitor.

Can you minimize further to something that can be run without additional dependencies or other files or environment variables?

**Comment by dacr** [comment]
may be it is related to the way scala-cli work :( So first here the two simplified test case : 
- KO using collectZIO : https://gist.github.com/dacr/1edeb107fb650d1558095c4984e490c2
- OK using mapZIO : https://gist.github.com/dacr/26132a03a758fcc56a3833895887c251

For the KO collectZIO case using scala-cli for its execution : 
```scala
// ---------------------
//> using scala  "3.1.3"
//> using lib "dev.zio::zio-streams:2.0.0"
// ---------------------

import zio.*
import zio.stream.*
import scala.util.matching.Regex
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

object Photos extends ZIOAppDefault {

  def parseTimestamp(timestamp: String): ZIO[Any, Throwable, LocalDateTime] = ZIO.succeed(LocalDateTime.now())

  def run = for {
    _       <- ZIO.log(s"scanning...")
    mask    <- ZIO.attempt(""".*/(\d{8}-\d{6})-\d{2}-(.*)-evt.jpg""".r)
    entries <-
      ZStream
        .fromIterable(List("./20220902-162930-00-raspcam1-evt.jpg", "./20220901-195134-00-raspcam1-evt.jpg", "./20220901-204013-00-raspcam1-evt.jpg"))
        .filterNot(_.contains("Trash"))
        .collectZIO { case file @ mask(timestamp, group) => parseTimestamp(timestamp).map(ts => ts -> file) } // https://github.com/zio/zio/issues/7301
        .tap(f => ZIO.log(s"found $f"))
        .runCollect
    _       <- ZIO.log(s"found ${entries.size} entries")
  } yield ()
}

Photos.main(Array.empty)
```

I'm going right now to check how it works in a standard execution way (without scala-cli)

**Comment by dacr** [comment]
OK this is probably a border side effect linked to scala-cli :( because if I run exactly the same code in a traditional way, it works : 
```
dcr@lanfeust:~/dev-opensource/dummy-for-zstream-issue-7301$ sbt run
[info] Updated file /home/dcr/dev-opensource/dummy-for-zstream-issue-7301/project/build.properties: set sbt.version to 1.7.1
[info] welcome to sbt 1.7.1 (Private Build Java 17.0.4)
[info] loading settings for project global-plugins from idea.sbt ...
[info] loading global plugins from /home/dcr/.sbt/1.0/plugins
[info] loading project definition from /home/dcr/dev-opensource/dummy-for-zstream-issue-7301/project
[info] loading settings for project dummy-for-zstream-issue-7301 from build.sbt ...
[info] set current project to dummy (in build file:/home/dcr/dev-opensource/dummy-for-zstream-issue-7301/)
[info] compiling 1 Scala source to /home/dcr/dev-opensource/dummy-for-zstream-issue-7301/target/scala-3.1.3/classes ...
[info] running dummy.Dummy 
timestamp=2022-09-03T08:06:53.669243715Z level=INFO thread=#zio-fiber-6 message="scanning..." location=dummy.Dummy$.run.macro file=Main.scala line=15
timestamp=2022-09-03T08:06:53.746645055Z level=INFO thread=#zio-fiber-6 message="found (2022-09-03T10:06:53.746052798,./20220902-162930-00-raspcam1-evt.jpg)" location=dummy.Dummy$.run.macro file=Main.scala line=22
timestamp=2022-09-03T08:06:53.749009498Z level=INFO thread=#zio-fiber-6 message="found (2022-09-03T10:06:53.748938142,./20220901-195134-00-raspcam1-evt.jpg)" location=dummy.Dummy$.run.macro file=Main.scala line=22
timestamp=2022-09-03T08:06:53.749786440Z level=INFO thread=#zio-fiber-6 message="found (2022-09-03T10:06:53.749721910,./20220901-204013-00-raspcam1-evt.jpg)" location=dummy.Dummy$.run.macro file=Main.scala line=22
timestamp=2022-09-03T08:06:53.758473339Z level=INFO thread=#zio-fiber-6 message="found 3 entries" location=dummy.Dummy$.run.macro file=Main.scala line=24
```

I'm going to add more input to a scala-cli issue (https://github.com/VirtusLab/scala-cli/issues/532) I've written some times ago, and the described workaround, to this issue, object encapsulation, is in fact not a good work around as shown by this behavior.

I think we can close this issue, sorry for the inconvenience

**Comment by adamgfraser** [comment]
@dacr No worries! Love all your examples!
