### ISSUE TITLE
ZIO 2.0.x : stackoverflow fatal error

### ISSUE THREAD

**Issue by berman7** [zio/zio#7323]
Hello,
One of our (hundreds of) ZIO apps running 2.0.2 has started failing consistently with the following fatal error, after which the instance exists and restarts:
`java.lang.StackOverflowError
	at java.base/java.lang.String.getChars(String.java:854)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:229)
	at java.base/java.io.Writer.write(Writer.java:249)
	at java.base/java.io.PrintStream.write(PrintStream.java:604)
	at java.base/java.io.PrintStream.print(PrintStream.java:745)
	at java.base/java.io.PrintStream.println(PrintStream.java:899)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
	at zio.RuntimePlatformSpecific.$anonfun$defaultReportFatal$1(RuntimePlatformSpecific.scala:38)
	at zio.internal.FiberRuntime.handleFatalError(FiberRuntime.scala:587)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1107)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.liftedTree1$1(FiberRuntime.scala:818)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:817)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:330)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:448)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:223)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)` 

Running on scala 2.12.

we have only begun to investigate, and as a first measure a rollback to a zio 1.x version was successfully completed. I hope that this initial data can help here, and we will try to understand more on our end. 

Thank you.

**Comment by berman7** [comment]
update:
checked version with ZIO 2.0.0 - **not reproducing**.

**Comment by zeal18** [comment]
I have the same problem as the author of the issue. Don't know if it's related problem or not, but in addition I've also got the following StackOverflow:
```
[error] java.lang.StackOverflowError
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
[error]         at zio.stream.internal.ChannelExecutor$Subexecutor$PullFromChild.close(ChannelExecutor.scala:862)
[error]         at zio.stream.internal.ChannelExecutor.close(ChannelExecutor.scala:84)
.... 
```

**Comment by adamgfraser** [comment]
I'm not sure these issues are related. The first appears to be in the runtime itself, whereas the second seems to be in streams.

In both cases, a minimized reproducer, ideally using just ZIO or ZIO and ZIO Stream would be extremely helpful in diagnosing. Alternatively, if this is a regression versus a prior ZIO 2.0 version then identifying which commit caused the regression would be very helpful. Snapshots of every commit are published and I believe this is already in progress regarding the original issue.

**Comment by berman7** [comment]
after further investigation - it seems that the (legacy) app was started with a low -xss value, which caused the stack to be smaller than it is in normal production apps.
this caused even a stack trace of less than 256 calls to be too large, and since ZIO uses that much by default for the event loop before yielding, the StackOverflowException was thrown.

The behaviour is apparent in ZIO 2.0.0, although less frequent than in 2.0.2 it seems.

So it's not a very high priority bug it seems (setting default -xss fixed the issue), but maybe it would be better to either catch  StackOverflowException in the run loop and rethrow with some more actionable exception; or even better, restrict MaxOperationsBeforeYield considering the stack size of the jvm process.

Thanks

**Comment by shawjef3** [comment]
ZIO could also create its threads with a required stack size. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Thread.html#%3Cinit%3E(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long)

**Comment by shawjef3** [comment]
Something like this might work (totally untested). https://github.com/shawjef3/zio/commit/890b6a585be06ce4c58d8da129bbf78c11eba683

**Comment by hearnadam** [comment]
I think ZIO thread pool should initialize threads with a minimum stack size. We can add some error warnings if default is lower... @jdegoes
