### ISSUE TITLE
refineToOrDie removes part of exception stacktrace

### ISSUE THREAD

**Issue by andrzejressel** [zio/zio#7503]
Code:

```scala
//> using platform "jvm"
//> using scala "3.2.0"
//> using lib "dev.zio::zio:2.0.3"
//> using mainClass "RefineOrDie"

import zio.*
import zio.Console.printLine

object RefineOrDie extends ZIOAppDefault:
  override def run: ZIO[Environment & ZIOAppArgs & Scope, Any, Any] = {
    for {
        _ <- Console.printLine("Normal")
        _ <- ZIO.attemptBlocking(throwError()).tapErrorCause(c => Console.printLine(c.prettyPrint)).ignore
        _ <- Console.printLine("RefineToOrDie")
        _ <- ZIO.attemptBlocking(throwError()).refineToOrDie[java.lang.RuntimeException].tapErrorCause(c => Console.printLine(c.prettyPrint)).ignore
    } yield ()
  }

  def throwError() = throw RuntimeException("Exception")

```

Output:
```
Normal
Exception in thread "zio-fiber-4" java.lang.RuntimeException: java.lang.RuntimeException: Exception
	at RefineOrDie$.throwError(RefineOrDie.scala:19)
	at <empty>.RefineOrDie.run(RefineOrDie.scala:13)
	at <empty>.RefineOrDie.run(RefineOrDie.scala:16)
RefineToOrDie
Exception in thread "zio-fiber-4" java.lang.RuntimeException: java.lang.RuntimeException: Exception
	at <empty>.RefineOrDie.run(RefineOrDie.scala:15)
	at <empty>.RefineOrDie.run(RefineOrDie.scala:16)
```

While here the only line missing is the last one in my project it removed half of stacktrace from java code.

**Comment by adamgfraser** [comment]
@andrzejressel Thanks for reporting! Fixed in #7504.
