### ISSUE TITLE
Do not consume additional stack space when determining if an error is fatal

### ISSUE THREAD

**Issue by indra-rosadi-rally** [zio/zio#7529]
Hi, 
In one of my projects, I get this error when initializing ZIO/ZLayer that requires a lot of resources/memory. Anybody has any idea what this error means? It looks like it is trying to inspect if a throwable is fatal and it blew up, so I have no idea what the original throwable is. I am using ZIO 2.0.3. The JVM is Java 17 temurin.

```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 873
java.lang.StackOverflowError
	at java.base/java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.base/java.io.UnixFileSystem.hasBooleanAttributes(Unknown Source)
	at java.base/java.io.File.exists(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath.getResource(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at zio.internal.IsFatal.apply(IsFatal.scala:8)
	at zio.internal.IsFatal.apply$(IsFatal.scala:6)
	at zio.internal.IsFatal$Single.apply(IsFatal.scala:29)
	at zio.internal.FiberRuntime.isFatal(FiberRuntime.scala:739)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1247)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:918)
```

Thanks.

**Comment by adamgfraser** [comment]
@indra-rosadi-rally Thanks for reporting! Can you create a small reproducer?

**Comment by jdegoes** [comment]
What java agent are you using?

**Comment by indra-rosadi-rally** [comment]
Hi,
Sorry for the late reply. I think we used datadog as part of the java agent. The JRE that we ran in Java 17 Temurin running on Debian buster image. I can't create a small reproducer since it may be combination of things that cause this. Particularly, we were running a pretty big tensor flow model. I think my primary problem is that it looks like ZIO errored out when determining if a throwable is fatal or not so we don't know what the actual error is. We are using ZIO 2.0.3.

**Comment by jdegoes** [comment]
Perhaps we can change this ticket to: `do not consume additional stack space when determining if an error is fatal`.

**Comment by indra-rosadi-rally** [comment]
Updated. Thanks.

**Comment by adamgfraser** [comment]
But where are we consuming additional stack space? All we are doing in `isFatal` is checking if the `Throwable` is a `VirtualMachineError`. We could be using additional stack space if there were a large number of alternative classes we were checking whether the `Throwable` is a subtype of but I don't think that is happening here.

**Comment by indra-rosadi-rally** [comment]
For some reason, in this particular case, an error occurred when checking `isFatal` which obscure the actual error that happened. So what we see in the log is the error from `isFatal`, not the actual error.

**Comment by adamgfraser** [comment]
Right, but `isFatal` is just `Class#isAssignableFrom(throwable.getClass)`.

**Comment by indra-rosadi-rally** [comment]
I see, OK. Somehow, in the stack trace above, when `isFatal` is invoked, it went on and try to load some class which ends up with error.

**Comment by adamgfraser** [comment]
Right, I would think the class of the `Throwable` to determine whether it is a `VirtualMachineError`.

**Comment by jdegoes** [comment]
Possibly we need to short-circuit the case of StackOverflowException. We really can't even call 1 method, let alone a chain of methods, in the event this exception is called.

`isInstancedOf[StackOverflowException]` will not consume more stack space.

**Comment by jdegoes** [comment]
(Should we do that, we're basically saying that SOE is always fatal. Probably reasonable but to be discussed.)

**Comment by adamgfraser** [comment]
That seems reasonable to me.
