### ISSUE TITLE
ZStream OOM problem.

### ISSUE THREAD

**Issue by counter2015** [zio/zio#7535]
version: zio-streams 2.0.3

## Error message
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /tmp/test.hprof ...
Heap dump file created [114396117 bytes in 0.094 secs]
java.lang.OutOfMemoryError: Java heap space
	at scala.collection.mutable.ArrayBuilder$ofByte.mkArray(ArrayBuilder.scala:155)
	at scala.collection.mutable.ArrayBuilder$ofByte.resize(ArrayBuilder.scala:161)
	at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:43)
	at zio.ChunkBuilder$$anon$1.addOne(ChunkBuilder.scala:56)
	at zio.ChunkBuilder$$anon$1.addOne(ChunkBuilder.scala:48)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at zio.ChunkBuilder.addAll(ChunkBuilder.scala:40)
	at scala.collection.mutable.Growable.$plus$plus$eq(Growable.scala:69)
	at scala.collection.mutable.Growable.$plus$plus$eq$(Growable.scala:69)
	at zio.ChunkBuilder.$plus$plus$eq(ChunkBuilder.scala:40)
	at zio.Chunk$.fromIterable(Chunk.scala:1271)
	at Test$.$anonfun$task$6(Test.scala:18)
	at Test$$$Lambda$441/0x0000000800deecf8.apply(Unknown Source)
	at zio.Chunk$Arr.mapChunk(Chunk.scala:1729)
	at zio.ChunkLike.map(ChunkLike.scala:113)
	at zio.ChunkLike.map$(ChunkLike.scala:112)
	at zio.Chunk.map(Chunk.scala:42)
	at zio.stream.ZStream.$anonfun$map$1(ZStream.scala:1790)
	at zio.stream.ZStream$$Lambda$38/0x0000000800cb3398.apply(Unknown Source)
	at zio.stream.ZChannel.$anonfun$mapOut$1(ZChannel.scala:622)
	at zio.stream.ZChannel$$Lambda$471/0x0000000800dfa510.apply(Unknown Source)
	at zio.stream.internal.ChannelExecutor.$anonfun$run$15(ChannelExecutor.scala:202)
	at zio.stream.internal.ChannelExecutor$$Lambda$431/0x0000000800debec8.apply(Unknown Source)
	at zio.stream.internal.ChannelExecutor$.read$1(ChannelExecutor.scala:935)
	at zio.stream.internal.ChannelExecutor$.$anonfun$readUpstream$8(ChannelExecutor.scala:965)
	at zio.stream.internal.ChannelExecutor$$$Lambda$522/0x0000000800e0c440.apply(Unknown Source)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:995)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:384)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:496)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:224)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:137)
**** WARNING ****
Catastrophic error encountered. Application not safely interrupted. Resources may be leaked. Check the logs for more details and consider overriding `Runtime.reportFatal` to capture context.

```

## Code
```scala
import zio._
import zio.stream.ZStream

object Test extends ZIOAppDefault {
  val line: String = (1 to 1000).mkString + "\n"
  val streamSource: ZStream[Any, Nothing, String] = ZStream.fromIterable(1 to 622272).map(_ => line)

  // it will cause OOM
  def task() = {
    ZIO.scoped {
      streamSource
        .broadcast(n = 2, maximumLag = 128)
        .flatMap { streams =>
          for {
            countStream <- streams(0).runCount.fork
            data = streams(1).map(line => {
              println(line)
              Chunk.fromIterable(line.getBytes)
            }).flattenChunks
            uploadStream <- mockUpload(data).fork

            count <- countStream.join.zipPar(uploadStream.join)
            _ <- ZIO.debug(count)
          } yield ()
        }
    }
  }

  // it works without OOM
  def task2() = {
    ZIO.scoped{for {
      count <- streamSource.runCount
      data = streamSource.map(line => Chunk.fromIterable(line.getBytes)).flattenChunks
      _ <- mockUpload(data)
      _ <- ZIO.debug(count)
    } yield ()}
  }

  def mockUpload(content: ZStream[Any, Throwable, Byte]): ZIO[Any, Throwable, Unit] = {
    content.runDrain
  }

  override def run = {
    task()
  }
}

```

## RunTime flag
```
-Xmx100m
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=/tmp/test.hprof
```

## Heap dump summary
<img width="1763" alt="image" src="https://user-images.githubusercontent.com/13608862/202658247-8edd4778-c4b9-4720-a3d6-606ba8d75c77.png">

**Comment by svroonland** [comment]
Also experiencing an OOM on a newly developed stream processing application based on 2.0.3, within a minute after startup. Found this issue by chance. The issue goes away when downgrading to 2.0.2.

**Comment by counter2015** [comment]
@svroonland That might not be the same problem, this OOM problem also found in 2.0.2

**Comment by adamgfraser** [comment]
@counter2015 Can you try on the latest snapshot? This works for me on `series/2.x`.

**Comment by counter2015** [comment]
Well, It seems cost time to try it. I package local snapshot, but it seem only supoort JDK 18+, I will change jdk to run it.

**Comment by counter2015** [comment]
@adamgfraser It not works for me.
 My snapshot version is 2.0.2+39-0998060b-SNAPSHOT
last commit is ffa117661a1d8ae8aea92e0d11df072518a22a3d
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/13608862/202729263-98e7a92b-08dd-467c-ad94-311f210c7304.png">

**Comment by mschuwalow** [comment]
could you could a release with the fix? We just got hit by this too

**Comment by MohammadForouhesh** [comment]
We have hit with this error using zio-stream 2.0.13. @adamgfraser

**Comment by adamgfraser** [comment]
@MohammadForouhesh I do not observe any out of memory error in the example above. Note that `ZStream.fromIterable` uses the default ZIO chunk size of 4,096 elements so with the `map` every chunk consists of 4,096 strings with 1,000 characters each.  You can control that and reduce the memory usage at some cost to performance by specifying a different chunk size in `ZStream.fromIterable`.
