### ISSUE TITLE
ConfigProvider.fromFlat requires a non-empty string value to read Config.Sequence and at least one key-value pair to read a Config.Table

### ISSUE THREAD

**Issue by jeffmay** [zio/zio#7645]
### Example Specification

```scala
import zio._
import zio.test._

object EmptySeqConfigSpec extends ZIOSpecDefault {

  override val spec: Spec[TestEnvironment with Scope, Any] = suite("empty")(
    test("chunk") {
      for {
        _ <- ZIO.withConfigProviderScoped(ConfigProvider.fromMap(Map()))
        chunk <- ZIO.config(Config.chunkOf(Config.string))
      } yield assertTrue(chunk.isEmpty)
    },
    test("table") {
      for {
        _ <- ZIO.withConfigProviderScoped(ConfigProvider.fromMap(Map()))
        map <- ZIO.config(Config.table(Config.string))
      } yield assertTrue(map.isEmpty)
    },
    test("chunk.optional") {
      for {
        _ <- ZIO.withConfigProviderScoped(ConfigProvider.fromMap(Map()))
        optChunk <- ZIO.config(Config.chunkOf(Config.string).optional)
      } yield assertTrue(optChunk.isEmpty)
    },
    test("table.optional") {
      for {
        _ <- ZIO.withConfigProviderScoped(ConfigProvider.fromMap(Map()))
        optMap <- ZIO.config(Config.table(Config.string).optional)
      } yield assertTrue(optMap.isEmpty)
    },
  )
}
```

### Expectation

I would expect that parsing a `Seq` or `Map` from the config would support missing values without using the `.optional`, however,  even requiring an `Option` in the model doesn't work as expected. All of these tests fail except for the first one.

**Comment by adamgfraser** [comment]
@jeffmay The first two tests pass on `series/2.x`. I don't think the second two tests are correct. The table or map was successfully loaded, so the result should be `Some(Map.empty)` not `None`.

**Comment by jeffmay** [comment]
@adamgfraser That's strange... the second test fails for me with Scala 3.2.1, Java JDK 22.2.r17-grl, and ZIO 2.0.5. Could this bug already be fixed on the main branch but not released?

Also, I agree on the expectation of the bottom 2 tests, however, I get the same exception as the second test on the optional table. This is the output I get:
```
+ empty
  + chunk
  - table.optional
    Exception in thread "zio-fiber-142" zio.Config$Error$MissingData: (Missing data at : Expected a single value having structure Optional(MapOrFail(Table(Text),zio.Config$$Lambda$942/0x0000000800ef99c0@72466298),Lazy(zio.Config$$$Lambda$943/0x0000000800efa938@26faa86b)))
    	at com.rallyhealth.kerna.models.EmptySeqConfigSpec.spec(EmptySeqConfigSpec.scala:30)
    	at com.rallyhealth.kerna.models.EmptySeqConfigSpec.spec(EmptySeqConfigSpec.scala:27)
  - table
    Exception in thread "zio-fiber-140" zio.Config$Error$MissingData: (Missing data at : Expected a single value having structure Table(Text))
    	at com.rallyhealth.kerna.models.EmptySeqConfigSpec.spec(EmptySeqConfigSpec.scala:18)
    	at com.rallyhealth.kerna.models.EmptySeqConfigSpec.spec(EmptySeqConfigSpec.scala:15)
  - chunk.optional
    ✗ Some was not empty
    optChunk.isEmpty
    optChunk = Some(Chunk())
    at /Users/jmay34/Code/rally/kerna/models/src/test/scala/EmptySeqConfigSpec.scala:25 
```

**Comment by jeffmay** [comment]
Oh, I think this was probably fixed in https://github.com/zio/zio/pull/7626, so it just hasn't been released yet
