### ISSUE TITLE
`serviceWithZIO` compiler crash

### ISSUE THREAD

**Issue by bertlebee** [zio/zio#7704]
forgetting to add a type param using `serviceWithZIO` causes the compiler to crash on scala 3
https://scastie.scala-lang.org/VEozYp5OQlmLyTb0hn3KQw
```
java.lang.AssertionError: assertion failed: R &amp; Playground.Foo / TypeParamRef(R) &amp; HKTypeLambda(List(A), List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))), AppliedType(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class &lt;empty&gt;)),module class Playground$)),trait Foo),List(TypeParamRef(A))))
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.Types$AndType$.apply(Types.scala:3203)
	at dotty.tools.dotc.core.Types$AndType$.make(Types.scala:3238)
	at dotty.tools.dotc.core.Types$AndType.derivedAndType(Types.scala:3184)
	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.derivedAndType(Types.scala:5961)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5689)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:109)
	at dotty.tools.dotc.core.Types$TypeMap.op$proxy16$1(Types.scala:5590)
	at dotty.tools.dotc.core.Types$TypeMap.mapArgs(Types.scala:5590)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5627)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:109)
	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5603)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:103)
	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5603)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:103)
	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5603)
	at dotty.tools.dotc.core.TypeOps$AsSeenFromMap.apply(TypeOps.scala:103)
	at dotty.tools.dotc.core.TypeOps$.asSeenFrom(TypeOps.scala:51)
	at dotty.tools.dotc.core.Types$Type.asSeenFrom(Types.scala:1036)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.derived$1(Denotations.scala:1099)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:1125)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.computeAsSeenFrom(Denotations.scala:1079)
	at dotty.tools.dotc.core.Denotations$PreDenotation.asSeenFrom(Denotations.scala:134)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:2069)
```

This needs to be fixed upstream, this is just for tracking here and might help someone else who runs into it
https://github.com/lampepfl/dotty/issues/16696

**Comment by adamgfraser** [comment]
Thanks for reporting and for opening the Scala compiler issue! Going to close this as I don't think there is an actionable item for us here but again thank you for following up and reporting the compiler crash. It really helps!
