### ISSUE TITLE
[Bug]: Nested finalizers in the `ChannelExecutor` swallow exceptions

### ISSUE THREAD

**Issue by IMax153** [zio/zio#7810]
## Description

If a `ZChannel` has multiple finalizers attached via `ZChannel.ensuring`, exceptions thrown will not be propagated properly.

## Minimal Reproduction

In the example below, the unit value `()` is logged but the exception is swallowed and never logged by `ZIO.logErrorCause`:

```scala
import zio._
import zio.stream._

object Main extends ZIOAppDefault {

  def run = ZChannel.unit
    .ensuring(ZIO.die(new RuntimeException("ok")))
    .ensuring(ZIO.unit)
    .runDrain
    .flatMap(ZIO.debug(_))
    .catchAllCause(ZIO.logErrorCause(_))

}
```

However, if the second call to `ZChannel.ensuring` is removed, the error is logged properly:

```scala
import zio._
import zio.stream._

object Main extends ZIOAppDefault {

  def run = ZChannel.unit
    .ensuring(ZIO.die(new RuntimeException("ok")))
    .runDrain
    .flatMap(ZIO.debug(_))
    .catchAllCause(ZIO.logErrorCause(_))

}
```

Outupt:

```text
timestamp=2023-02-10T23:35:41.162594Z level=ERROR thread=#zio-fiber-6 message="" cause="Exception in thread "zio-fiber-6" java.lang.RuntimeException: ok
        at Main$.$anonfun$program2$2(Main.scala:13)
        at <empty>.Main.program2(Main.scala:13)
        at <empty>.Main.program2(Main.scala:14)
        at <empty>.Main.program2(Main.scala:15)
        at <empty>.Main.program2(Main.scala:16)" location=<empty>.Main.program2 file=Main.scala line=16
```

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!
