### ISSUE TITLE
Schedule intersection with secondOfMinute broken (StackOverflow) since ZIO 2.0.7

### ISSUE THREAD

**Issue by ThijsBroersen** [zio/zio#7815]
After upgrading to 2.0.7 or 2.0.8 some Schedule compositions result in an immediate stackoverflow.
See code example below. When removing  `secondOfMinute` it all works fine. 
```
import zio._

val scheduledTask = ZIO.unit.schedule(Schedule.dayOfWeek(1) && Schedule.hourOfDay(1) && Schedule.minuteOfHour(1) && Schedule.secondOfMinute(1))

val runtime = Runtime.default

Unsafe.unsafe { implicit unsafe =>
  runtime.unsafe.run(scheduledTask).getOrThrowFiberFailure()
}
```
results in
```
java.lang.StackOverflowError
        at java.base/java.time.LocalDate.equals(LocalDate.java:2134)
        at java.base/java.time.LocalDateTime.equals(LocalDateTime.java:1931)
        at java.base/java.time.OffsetDateTime.equals(OffsetDateTime.java:1884)
        at zio.Schedule$Interval$.apply(Schedule.scala:1674)
        at zio.Schedule$Interval.intersect(Schedule.scala:1644)
        at zio.Schedule$Intervals.loop$3(Schedule.scala:1757)
        at zio.Schedule$Intervals.intersect(Schedule.scala:1763)
        at zio.Schedule.$anonfun$$amp$amp$1(Schedule.scala:72)
        at zio.Schedule$$anon$12.loop(Schedule.scala:617)
        at zio.Schedule$$anon$12.$anonfun$loop$2(Schedule.scala:629)
        at zio.Exit.flatMap(ZIO.scala:5961)
        at zio.Exit.flatMap$(ZIO.scala:5959)
        at zio.Exit$Success.flatMap(ZIO.scala:6183)
        at zio.Schedule$$anon$12.loop(Schedule.scala:627)
        at zio.Schedule$$anon$12.$anonfun$loop$2(Schedule.scala:629)
        at zio.Exit.flatMap(ZIO.scala:5961)
        at zio.Exit.flatMap$(ZIO.scala:5959)
        at zio.Exit$Success.flatMap(ZIO.scala:6183)
        at zio.Schedule$$anon$12.loop(Schedule.scala:627)
        at zio.Schedule$$anon$12.$anonfun$loop$2(Schedule.scala:629)
```

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!

**Comment by ThijsBroersen** [comment]
LOL, only on Sunday it seems to work fine (`Schedule.dayOfWeek(7) && Schedule.secondOfMinute(1)`)

**Comment by ThijsBroersen** [comment]
And it seems the bug only occurs when intersecting `dayOfWeek` with `secondOfMinute`, other compositions work fine.

**Comment by adamgfraser** [comment]
I am working on this.
