### ISSUE TITLE
Compile error: Could not find implicit value for izumi.reflect.Tag[XX]

### ISSUE THREAD

**Issue by liewhite** [zio/zio#7929]
I'm sure `XX` is a declared case class, not a type parameter.
```scala
case class XX(a: Int)
object Test extends ZIOAppDefault {
  def run: ZIO[Any & (ZIOAppArgs & Scope), Any, Any] = {
     // [[ some code here ]] 
     val err = ZLayer.succeed(XX(1)) //  Could not find implicit value for izumi.reflect.Tag[XX]
     ZIO.unit
  }
}
```
It's weird that after  removing the code before `val err`, compile error gone. 

I can't reproduce here because the code before `err` is some thing complicate.

And another weird thing is i can click run and see result in vscode. But sbt compile failed.

**Comment by adamgfraser** [comment]
@liewhite We really aren't going to be able to take any action based on this without a reproducer.

**Comment by liewhite** [comment]
> @liewhite We really aren't going to be able to take any action based on this without a reproducer.

I have a macro stacktrace now:
```
could not find implicit value for izumi.reflect.Tag[XX]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in XX? e.g. def x[T: Tag, F[_]: TagK] = ....
I found:

    zio.Tag.materialize[XX]

But Exception occurred while executing macro expansion.
scala.MatchError: val <none> (of class dotty.tools.dotc.core.Symbols$NoSymbol$)
	at dotty.tools.dotc.core.Types$ThisType.cls(Types.scala:2938)
	at dotty.tools.dotc.core.Types$ThisType.underlying(Types.scala:2943)
	at dotty.tools.dotc.core.Types$Type.goThis$1(Types.scala:810)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:703)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:879)
	at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:669)
	at dotty.tools.dotc.core.Types$Type.nonPrivateMember(Types.scala:659)
	at dotty.tools.dotc.core.Types$NamedType.memberDenot(Types.scala:2392)
	at dotty.tools.dotc.core.Types$NamedType.memberDenot(Types.scala:2379)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:2355)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:2314)
	at dotty.tools.dotc.ast.Trees$DenotingTree.denot(Trees.scala:257)
	at dotty.tools.dotc.ast.Trees$Tree.symbol(Trees.scala:146)
	at dotty.tools.dotc.ast.TypedTreeInfo.definedSym(TreeInfo.scala:801)
	at dotty.tools.dotc.ast.TypedTreeInfo.definedSym$(TreeInfo.scala:420)
	at dotty.tools.dotc.ast.tpd$.definedSym(tpd.scala:23)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:813)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1621)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1529)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1531)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1562)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1613)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1529)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1531)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1562)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1617)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1529)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1531)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1624)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1621)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:811)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1529)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1531)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1630)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1535)
	at dotty.tools.dotc.ast.TypedTreeInfo$accum$2$.apply(TreeInfo.scala:815)
	at dotty.tools.dotc.ast.TypedTreeInfo.defPath(TreeInfo.scala:820)
	at dotty.tools.dotc.ast.TypedTreeInfo.defPath$(TreeInfo.scala:420)
	at dotty.tools.dotc.ast.tpd$.defPath(tpd.scala:23)
	at dotty.tools.dotc.ast.TypedTreeInfo.definingStats(TreeInfo.scala:860)
	at dotty.tools.dotc.ast.TypedTreeInfo.definingStats$(TreeInfo.scala:420)
	at dotty.tools.dotc.ast.tpd$.definingStats(tpd.scala:23)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.companionNamed(SymDenotations.scala:1250)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.scalacLinkedClass(SymDenotations.scala:1232)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:896)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:824)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:1037)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:1089)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readStats(TreeUnpickler.scala:1099)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1249)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.dotty$tools$dotc$core$tasty$TreeUnpickler$TreeReader$$_$_$$anonfun$26(TreeUnpickler.scala:1249)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:1095)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readStats(TreeUnpickler.scala:1099)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1249)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.dotty$tools$dotc$core$tasty$TreeUnpickler$TreeReader$$_$_$$anonfun$26(TreeUnpickler.scala:1249)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:1095)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readStats(TreeUnpickler.scala:1099)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1249)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1259)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1117)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.unpickle(TreeUnpickler.scala:113)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.computeRootTrees(DottyUnpickler.scala:62)
	at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees(tpd.scala:1277)
	at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees$(tpd.scala:1269)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.rootTrees(DottyUnpickler.scala:44)
	at dotty.tools.dotc.ast.tpd$TreeProvider.tree(tpd.scala:1284)
	at dotty.tools.dotc.ast.tpd$TreeProvider.tree$(tpd.scala:1269)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.tree(DottyUnpickler.scala:44)
	at dotty.tools.dotc.quoted.PickledQuotes$.unpickle(PickledQuotes.scala:257)
	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:83)
	at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3044)
	at zio.TagMacros$.materialize(ServiceTagVersionSpecific.scala:24)
```

**Comment by adamgfraser** [comment]
At this point it appears that the issue is either with the generation of tags in Izumi Reflect or with the Scala compiler itself so we will definitely need to have an actual reproducer and it likely needs to be addressed in one of those two places.

**Comment by liewhite** [comment]
May be a compiler error, close this temporarily
