### ISSUE TITLE
groupedWithin swallowing error and hanging up application

### ISSUE THREAD

**Issue by axaluss** [zio/zio#7976]
```scala
val myStream=???
myStream
.tapErrorCause(e=> ZIO.log("Error1 "+e.prettyPrint))
.groupedWithin(6,600.millis)
.tapErrorCause(e=> ZIO.log("Error2 "+e.prettyPrint))
.drain
```

This will hang if `myStream` produces an error.

`Error1` will be printed, `Error2` not.

**Comment by adamgfraser** [comment]
Both of these programs print both errors and complete on 2.0.10. Can you please provide a reproducer?

```scala
object Example extends ZIOAppDefault {

  val run =
    ZStream
      .fail("fail")
      .tapErrorCause(e => ZIO.log("Error1 " + e.prettyPrint))
      .groupedWithin(6, 1.second)
      .tapErrorCause(e => ZIO.log("Error2 " + e.prettyPrint))
      .runDrain
}
```

```
[info] timestamp=2023-04-03T18:24:18.000227Z level=INFO thread=#zio-fiber-7 message="Error1 Exception in thread "zio-fiber-" java.lang.String: fail" location=zio.stream.Example.run file=Example.scala line=10
[info] timestamp=2023-04-03T18:24:18.028734Z level=INFO thread=#zio-fiber-5 message="Error2 Exception in thread "zio-fiber-" java.lang.String: fail" location=zio.stream.Example.run file=Example.scala line=12
[info] timestamp=2023-04-03T18:24:18.032374Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-" java.lang.String: fail"
```

```scala
object Example extends ZIOAppDefault {

  val run =
    ZStream
      .die(new RuntimeException("die"))
      .tapErrorCause(e => ZIO.log("Error1 " + e.prettyPrint))
      .groupedWithin(6, 1.second)
      .tapErrorCause(e => ZIO.log("Error2 " + e.prettyPrint))
      .runDrain
}
```

```
[info] timestamp=2023-04-03T18:25:31.465367Z level=INFO thread=#zio-fiber-7 message="Error1 Exception in thread "zio-fiber-7" java.lang.RuntimeException: die
[info]  at zio.stream.Example$.$anonfun$run$1(Example.scala:9)
[info]  at zio.ZIO$.$anonfun$die$1(ZIO.scala:3081)
[info]  at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)
[info]  at zio.stream.Example.run(Example.scala:9)
[info]  at zio.stream.Example.run(Example.scala:11)" location=zio.stream.Example.run file=Example.scala line=10
[info] timestamp=2023-04-03T18:25:31.490048Z level=INFO thread=#zio-fiber-5 message="Error2 Exception in thread "zio-fiber-7" java.lang.RuntimeException: die
[info]  at zio.stream.Example$.$anonfun$run$1(Example.scala:9)
[info]  at zio.ZIO$.$anonfun$die$1(ZIO.scala:3081)
[info]  at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)
[info]  at zio.stream.Example.run(Example.scala:9)
[info]  at zio.stream.Example.run(Example.scala:11)" location=zio.stream.Example.run file=Example.scala line=12
[info] timestamp=2023-04-03T18:25:31.493113Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-7" java.lang.RuntimeException: die
[info]  at zio.stream.Example$.$anonfun$run$1(Example.scala:9)
[info]  at zio.ZIO$.$anonfun$die$1(ZIO.scala:3081)
[info]  at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)
[info]  at zio.stream.Example.run(Example.scala:9)
[info]  at zio.stream.Example.run(Example.scala:11)"
```

**Comment by axaluss** [comment]
`groupedWithin` works as expected. 

The reason for the confusion here was that the production of data in `myStream` was caused by processing data downstream. Because there was an error, that data was not processed, causing the source to not provide the next value.
