### ISSUE TITLE
zio-test: Pattern match inside smart assertion's `assertTrue`

### ISSUE THREAD

**Issue by honzatrtik** [zio/zio#8085]
Hello!
first of all, thanks for all your awesome work on zio ecosystem!

I have a problem with following code:

```scala
import zio.Scope
import zio.test.{Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

object TestTest extends ZIOSpecDefault{

  sealed trait Error
  object Error {
    case object A extends Error
    case object B extends Error
  }


  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("TestTest") (
      test("should compile") {
        val result = Left[Error, String](Error.A)
        assertTrue {
          result.is(_.left) match {
            case Error.A => true
            case Error.B => false
          }
        }
      }
    )
}
```

I'd expect the test to succeed, but I am getting:
```
timestamp=2023-04-27T09:14:04.178264Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-22" java.lang.RuntimeException: null
	at zio.test.ZIOSpecAbstract.$anonfun$runSpec$11(ZIOSpecAbstract.scala:79)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3146)
	at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)"

Process finished with exit code 1

Assertion failed:
  ✗ ERROR: zio.test.SmartAssertionExtensionError: This method can only be called inside of `assertTrue`
    zio.test.package$SmartAssertionOps$.is$extension(package.scala:1113)
    com.ematiq.manualorderbook.domain.TestTest$.$anonfun$spec$2(TestTest.scala:20)
    scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
  result.is(_.left) match {
            case Error.A => true
            case Error.B => false
          }
```

**Comment by adamgfraser** [comment]
@honzatrtik If you are using `is` you need to use operators which are supported by the smart assertions implementation. You can express the code above as `result.is(_.left) == Error.A`.

**Comment by honzatrtik** [comment]
Thanks Adam!
Out of curiosity, is there a list of supported operators documented somewhere?

**Comment by adamgfraser** [comment]
You can look in `SmartAssertions.scala` but we could definitely have better documentation there. Copying @khajavi.

**Comment by emilhotkowski** [comment]
Hi @adamgfraser do you need someone to improve documentation for smart assertions? I could do that if the issue is still relevant.

**Comment by adamgfraser** [comment]
@emilhotkowski That would be great!

**Comment by emilhotkowski** [comment]
By the way, if we don't use any functionality specific to SmartAssertions, it seems to have a behaviour of a normal assert. I'm not sure if this requires any explanation in docs or should I just add a small paragraph about operators supported by SmartAssertions?
```scala
import zio.Scope
import zio.test.Spec
import zio.test.TestEnvironment
import zio.test.ZIOSpecDefault
import zio.test.assertTrue

object TestTest extends ZIOSpecDefault {

  sealed trait Error

  object Error {
    case object A extends Error
    case object B extends Error
  }
  
  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("TestTest")(
      test("this compiles just fine") {
        assertTrue {
          val result = Left[Error, String](Error.A)
          result match {
            case Left(Error.A) => true
            case Left(Error.B) => false
          }
        }
      }
    )
}
```

**Comment by adamgfraser** [comment]
I think start with whatever you think would be helpful to a user.

**Comment by hearnadam** [comment]
@khajavi can you complete or close?
