### ISSUE TITLE
ZIO environment and quill seem not to mix in Scala 3.3.x

### ISSUE THREAD

**Issue by bishabosha** [zio/zio#8130]
see the issue in [softwaremill/realworld-tapir-zio](https://github.com/softwaremill/realworld-tapir-zio/issues/107)

the main issue seems to be that changing the scala version in that project from `3.2.1` to `3.3.0-RC6` breaks ZIO Environment, i.e. the type tag in the environment doesn't match the one requested:
```scala
13:58:24.045 [ZScheduler-Worker-4] DEBUG com.softwaremill.realworld.Main -- timestamp=2023-05-19T13:58:24.045344+02:00 level=DEBUG thread=zio-fiber-8 message="Fiber zio-fiber-8 did not handle an error" cause=
java.lang.Error: Defect in zio.ZEnvironment: Could not find Quill::Sqlite[=SnakeCase] inside ZEnvironment(Quill::Sqlite[+SnakeCase] -> io.getquill.jdbczio.Quill$Sqlite@3bc36c29)
	at zio.ZEnvironment$$anon$1.get(ZEnvironment.scala:167)
	at zio.ZIO$ServiceWithZIOPartiallyApplied$.apply$extension$$anonfun$13$$anonfun$1(ZIO.scala:5306)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1029)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
```

**Comment by adamgfraser** [comment]
@bishabosha I would make sure you are using the same `izumi-reflect` version. Otherwise this issue has to be solved at the `izumi-reflect` level. Potentially a change in Scala 3 caused a regression, looks like around the invariance versus covariance of the type parameter.

**Comment by bishabosha** [comment]
Thanks for the suggestion, I'm forcing the Izumi-reflect version with `dependencyOverrides += "dev.zio" %% "izumi-reflect" % "2.3.1",` but no change (zio 2.0.13 depends on Izumi-reflect 2.3.1)

**Comment by adamgfraser** [comment]
Yeah so the issue has to be addressed at the `izumi-reflect` level. It appears that the value we are looking for is `Quill::Sqlite[=SnakeCase]` whereas the value that actually exists in the environment is `Quill::Sqlite[+SnakeCase]`. Notice the `=` versus `+` which I believe refers to the variance. I don't know what changes in Scala 3 caused this, if those annotations are correct, or whether they should be reflected in the identity of these tags but that has to be handled at the `izumi-reflect` level.
