### ISSUE TITLE
Terminate ZIO app with failure 

### ISSUE THREAD

**Issue by fernanluyano** [zio/zio#8140]
ZIO doesn’t seem to have a way of failing the app by choice. 
Why is this important?
A use case is a Spark job. When an uncaugth exception happens in Spark, the job will normally fail.
Having a similar behavior that you can explicitly add to the app configuration would be nice. So that when a Spark job throws an uncaught exception is marked as failed, instead of showing a successful job.

**Comment by adamgfraser** [comment]
Not sure I understand. That is the behavior today.

```scala
object Example extends ZIOAppDefault {

  val run =
    ZIO.fail("fail")
}
```

```
[info] timestamp=2023-05-23T14:35:07.244865Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.String: fail
[info]  at zio.Example.run(Example.scala:6)"
[error] Nonzero exit code returned from runner: 1
[error] (Compile / run) Nonzero exit code returned from runner: 1
[error] Total time: 3 s, completed May 23, 2023, 7:35:07 AM
```

**Comment by fernanluyano** [comment]
Here's some dummy code to reproduce it (using Databricks here). My apologies if this is not the right way.
Let's say I have this simple Spark app
```
object MyJob extends ZIOAppDefault {
  override def run =
    for {
      _ <- MySparkTask.run().provide(MySparkTask.sparkSession)
    } yield ()
}
```
And the simple task looks like
```
object MySparkTask {

  def run() = {
    for {
      spark <- ZIO.service[SparkSession]
      _     <- ZIO.attempt(runTask(spark)).exitCode // with or without exitCode the result is the same
    } yield ()
  }

  def runTask(spark: SparkSession): Unit = {
    spark.sql("select 1 from a") // will fail on purpose since the table DNE
  }

  def sparkSession = {
    ZLayer.succeed {
      SparkSession
        .builder
        .appName("MySparkApp")
        .getOrCreate
    }
  }
}
```
I can see the exception being thrown but the job still succeeds. Is there a way to communicate to Spark that this job was a failure? It's behaving like it's swallowing the exception before terminating.
![Screen Shot 2023-05-23 at 11 42 07 AM](https://github.com/zio/zio/assets/7608751/847d3514-7627-457b-9934-5e1a2b73d00d)

**Comment by adamgfraser** [comment]
ZIO doesn't know anything about the internals of Spark so let's simplify this to:

```scala
object Example extends ZIOAppDefault {

  def runSparkTask(): Unit =
    throw new Exception("Spark task failed")

  val run =
    ZIO.attempt(runSparkTask())
}
```

This again fails with an error:

```
[info] timestamp=2023-05-23T15:56:27.762057Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.Exception: Spark task failed
[info]  at zio.Example$.runSparkTask(Example.scala:6)
[info]  at zio.Example$.$anonfun$run$1(Example.scala:9)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at zio.ZIOCompanionVersionSpecific.$anonfun$attempt$1(ZIOCompanionVersionSpecific.scala:100)
[info]  at zio.Example$.runSparkTask(Example.scala:6)
[info]  at zio.Example.run(Example.scala:9)"
[error] Nonzero exit code returned from runner: 1
[error] (Compile / run) Nonzero exit code returned from runner: 1
[error] Total time: 2 s, completed May 23, 2023, 8:56:28 AM
```

**Comment by fernanluyano** [comment]
Unfortunately, this does not work either. It seems a Spark app is not able to decipher when a ZIO app fails. Closing
