### ISSUE TITLE
Running valid ZIO test fails randomly with java.io.FileNotFoundException

### ISSUE THREAD

**Issue by vitaliihonta** [zio/zio#8290]
# Summary
In combination with [sbt project matrix plugin](https://github.com/sbt/sbt-projectmatrix) used for cross-compilation, a very simple ZIO test randomly fails with such an error:
```
- SampleSpec
    Exception in thread "zio-fiber-29" java.io.FileNotFoundException: target/test-reports-zio/com.example.SampleSpec_debug.txt (No such file or directory)
    	at java.io.FileInputStream.open0(Native Method)
    	at java.io.FileInputStream.open(FileInputStream.java:195)
    	at java.io.FileInputStream.<init>(FileInputStream.java:138)
    	at scala.io.Source$.fromFile(Source.scala:94)
    	at scala.io.Source$.fromFile(Source.scala:79)
    	at scala.io.Source$.fromFile(Source.scala:57)
    	at zio.test.TestDebug$.removeLine$$anonfun$1(TestDebug.scala:69)
    	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
    	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
    	at zio.UnsafeVersionSpecific.implicitFunctionIsFunction$$anonfun$1(UnsafeVersionSpecific.scala:27)
    	at zio.Unsafe$.unsafe(Unsafe.scala:37)
    	at zio.ZIOCompanionVersionSpecific.succeed$$anonfun$1(ZIOCompanionVersionSpecific.scala:185)
    	at zio.test.TestDebug.removeLine(TestDebug.scala:78)
    	at zio.test.TestDebugFileLock.updateFile(TestDebugFileLock.scala:12)
    	at zio.test.TestOutput.TestOutputLive.printOrQueue(TestOutput.scala:116)
    	at zio.test.TestOutput.TestOutputLive.printOrQueue(TestOutput.scala:128)
Executed in 484 ms
```

The test:
```scala
import zio._
import zio.test._

object SampleSpec extends ZIOSpecDefault {
  override val spec = suite("SampleSpec")(
    test("sample test") {
      for {
        _ <- Console.printLine("Running sample spec")
      } yield assertTrue(1 == 1)
    }
  )
}
```

I've decoupled a minimal reproducer here https://github.com/vitaliihonta/zio-test-bug-reproducer .
It may require running `sbt test` multiple times (preferably from a single sbt session) to catch it.
Two cross scala versions are enough to reproduce the issue.

The bug was originally caught while updating ZIO in [zio-temporal ](https://github.com/vitaliihonta/zio-temporal/pull/93).
It appeared in some ZIO versions after 2.0.12. Currently, it blocks me from upgrading the library 😢 

## Possible cause
For me, it looks like tests for different scala versions are running in parallel, while ZIO test produces a single `<spec name>_debug.txt` file for both of them. Whenever the first test succeeds, it deletes the debug file, and the second test can't find this file

**Comment by adamgfraser** [comment]
@vitaliihonta Hi! Can you please try on the latest snapshot?

**Comment by vitaliihonta** [comment]
@adamgfraser Yep, it works fine on the latest snapshot. 
Thank you for the quick feedback! I'll wait for the next release. Feel free to close the ticket 😄

**Comment by adamgfraser** [comment]
@vitaliihonta Will do another release soon!
