### ISSUE TITLE
Failing method on case class causes test failure without runner detecting it

### ISSUE THREAD

**Issue by gergelyfabian** [zio/zio#8439]
Having the following test:

```scala
import zio.test._
import zio.test.junit.JUnitRunnableSpec

class ZIOErrorReportingBugTest extends JUnitRunnableSpec { self: JUnitRunnableSpec =>
  case class Foo(a: Int) {
    override def productPrefix: String = {
      throw new Exception("Boooom!")
    }
  }

  override def spec =
    suite("ZIOErrorReportingBugTest") {
      test("properly report bug") {
        val foo1 = Foo(2)

        // Only this assert would work.
        assertTrue(foo1.a == foo1.a) &&
        // This assert causes the issue.
          assertTrue(foo1 == foo1)
      }
    }
}
```

It will produce the following test output:

```
+ ZIOErrorReportingBugTest
.    - properly report bug
      Exception in thread "zio-fiber-611" java.lang.Exception: Boooom!
      	at com.my.tests.ZIOErrorReportingBugTest$Foo.productPrefix(ZIOErrorReportingBugTest.scala:10)
      	at zio.test.PrettyPrint$.apply(PrettyPrint.scala:39)
      	at zio.test.FailureCase$.getPath(Result.scala:91)
      	at zio.test.FailureCase$.getPath(Result.scala:93)
      	at zio.test.FailureCase$.fromTrace(Result.scala:102)
      	at zio.test.FailureCase$.fromTrace(Result.scala:104)
      	at zio.test.render.TestRenderer.renderAssertionResult(TestRenderer.scala:142)
      	at zio.test.render.TestRenderer.renderAssertionResult$(TestRenderer.scala:141)
      	at zio.test.render.ConsoleRenderer$.renderAssertionResult(ConsoleRenderer.scala:235)
      	at zio.test.junit.ZTestJUnitRunner.renderFailureDetails(ZTestJUnitRunner.scala:134)
      	at zio.test.junit.ZTestJUnitRunner.reportAssertionFailure(ZTestJUnitRunner.scala:122)
      	at zio.test.junit.ZTestJUnitRunner.$anonfun$instrumentSpec$2(ZTestJUnitRunner.scala:154)
      	at zio.ZIO.$anonfun$$times$greater$1(ZIO.scala:89)
      	at zio.test.junit.ZTestJUnitRunner.instrumentSpec.instrumentTest(ZTestJUnitRunner.scala:153)
      	at zio.test.junit.ZTestJUnitRunner.instrumentSpec.instrumentTest(ZTestJUnitRunner.scala:150)
      	at zio.test.junit.ZTestJUnitRunner.run._(ZTestJUnitRunner.scala:99)

Time: 0.276

OK (0 tests)
```

I know this is maybe a bit convoluted example (why would someone override productPrefix to throw an exception), but this sometimes happens automatically, e.g. when using scalamock to mock a case class (forgetting to add a proper trait as a parent for the case class, and mock that instead).
The hard part is that there is no non-zero exit code, so if test results are silent there is no way to find this issue in one's test suite (e.g. Bazel has this behavior as a default).

**Comment by gergelyfabian** [comment]
I think the root cause is that starting here:

https://github.com/zio/zio/blob/d6f2c09b13d2e047c4c11ab1f07501fe75fcd960/test-junit/jvm/src/main/scala/zio/test/junit/ZTestJUnitRunner.scala#L134

This method is to return a simple type (not ZIO), but it may fail. It could be fixed with error handling either here, or probably also deeper.

However, what makes me wonder is why this issue is not causing a non-zero exit code.

**Comment by gergelyfabian** [comment]
If you could give me some guidance how it should/could be fixed, I can try contributing it.

**Comment by gergelyfabian** [comment]
E.g. if I modify this method:

```scala
  private def renderFailureDetails(label: String, result: TestResult): Message = {
    val assertResultLines = scala.util.Try(ConsoleRenderer.renderAssertionResult(result.result, 0)) match {
      case scala.util.Success(message) => message
      case scala.util.Failure(e) => Message(s"Detected exception as rendering assertion results: $e")
    }
    Message(
      ConsoleRenderer
        .rendered(
          Test,
          label,
          Failed,
          0,
          assertResultLines.lines: _*
        )
        .streamingLines
    )
  }
```

Then at least my test fails (exit code is non-zero):

```
+ ZIOErrorReportingBugTest
.E  - ZIOErrorReportingBugTest
    Exception in thread "zio-fiber-560" java.lang.Exception: Boooom!
    	at com.my.tests.ZIOErrorReportingBugTest$Foo.productPrefix(ZIOErrorReportingBugTest.scala:12)
    	at zio.test.PrettyPrint$.apply(PrettyPrint.scala:39)
    	at zio.test.FailureCase$.getPath(Result.scala:91)
    	at zio.test.FailureCase$.fromTrace(Result.scala:102)
    	at zio.test.render.TestRenderer.renderAssertionResult(TestRenderer.scala:142)
    	at zio.test.render.TestRenderer.renderAssertionResult$(TestRenderer.scala:141)
    	at zio.test.render.ConsoleRenderer$.renderAssertionResult(ConsoleRenderer.scala:235)
    	at zio.test.render.TestRenderer.renderFailure(TestRenderer.scala:212)
    	at zio.test.render.TestRenderer.$anonfun$testCaseOutput$2(TestRenderer.scala:77)
    	at scala.Option.map(Option.scala:230)
    	at zio.test.render.TestRenderer.testCaseOutput(TestRenderer.scala:71)
    	at zio.test.render.TestRenderer.testCaseOutput$(TestRenderer.scala:37)
    	at zio.test.render.ConsoleRenderer$.testCaseOutput(ConsoleRenderer.scala:235)
    	at zio.test.render.ConsoleRenderer.renderEvent(ConsoleRenderer.scala:59)
    	at zio.test.render.ConsoleRenderer.renderEvent$(ConsoleRenderer.scala:31)
    	at zio.test.render.ConsoleRenderer$.renderEvent(ConsoleRenderer.scala:235)
    	at zio.test.SummaryBuilder$.$anonfun$buildSummary$4(SummaryBuilder.scala:43)
    	at scala.collection.immutable.List.flatMap(List.scala:366)
    	at zio.test.SummaryBuilder$.buildSummary(SummaryBuilder.scala:43)
    	at zio.test.Summary.add(Summary.scala:34)
    	at zio.test.ExecutionEventSink$$anon$1.$anonfun$process$2(ExecutionEventSink.scala:31)
    	at zio.Ref.$anonfun$update$1(Ref.scala:106)
    	at zio.Ref$Atomic$$anon$2.modify(Ref.scala:356)
    	at zio.Ref$Atomic.$anonfun$modify$3(Ref.scala:288)
    	at zio.test.ExecutionEventSink.ExecutionEventSinkLive.$anon.process(ExecutionEventSink.scala:30)
    	at zio.test.ExecutionEventSink.ExecutionEventSinkLive.$anon.process(ExecutionEventSink.scala:32)
    	at zio.test.junit.ZTestJUnitRunner.run._(ZTestJUnitRunner.scala:99)
    	at zio.test.junit.ZTestJUnitRunner.run._(ZTestJUnitRunner.scala:100)

Time: 0.279
There was 1 failure:
1) properly report bug(com.my.tests.ZIOErrorReportingBugTest)
zio.test.junit.TestFailed: Detected exception as rendering assertion results: java.lang.Exception: Boooom!

FAILURES!!!
Tests run: 0,  Failures: 1
```

Surely, the exception I introduced is still thrown from a different path (but the same class: PrettyPrint), but at least the exit code is proper now.

**Comment by gergelytraveltime** [comment]
Thank you @adamgfraser!

**Comment by gergelyfabian** [comment]
Thank you @adamgfraser
