### ISSUE TITLE
assertTrue on zio-http Response - Exception occurred while executing macro expansion

### ISSUE THREAD

**Issue by jamesward** [zio/zio#8518]
ZIO = 2.0.18
Scala = 3.3.1
zio-http = 3.0.0-RC3

```
assertTrue(Response.ok.status.isSuccess)
```

```
[error] 12 |      assertTrue(Response.ok.status.isSuccess)
[error]    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.Exception: Expected an expression. This is a partially applied Term. Try eta-expanding the term first.
[error]    |    at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExpr(QuotesImpl.scala:110)
[error]    |    at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:116)
[error]    |    at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:115)
[error]    |    at zio.test.SmartAssertMacros$.$anonfun$14$$anonfun$1(Macros.scala:210)
[error]    |    at zio.test.SmartAssertMacros$.$anonfun$14(Macros.scala:210)
[error]    |    at zio.test.SmartAssertMacros$.$anonfun$adapted$14(Macros.scala:210)
...
```

Reproducer project:
https://github.com/jamesward/zio-assertTrue-bug-partial

**Comment by BanyMaciej** [comment]
I will try to fix this

**Comment by jamesward** [comment]
Thanks! Confirmed that zio 2.0.20 fixes this.
