### ISSUE TITLE
Improve error message when ZIO async callback is called more than 1 time

### ISSUE THREAD

**Issue by cecol** [zio/zio#857]
I am trying to use `ZIO Queue` to consume messages from `google pubsub`.
The following is my code
```
import com.typesafe.scalalogging.Logger
import scalaz.zio.{App, IO, Task, ZIO, ZQueue}

import com.google.cloud.pubsub.v1.{AckReplyConsumer, MessageReceiver, Subscriber}
import com.google.pubsub.v1.{ProjectSubscriptionName, PubsubMessage}

object PubsubApiTest extends App {
  private[this] val log = Logger(this.getClass)

  override def run(args: List[String]): ZIO[PubsubApiTest.Environment, Nothing, Int] = {
    for {
      msgQueue <- ZQueue.bounded[(PubsubMessage, AckReplyConsumer)](100)
      subscriptionName: ProjectSubscriptionName = ProjectSubscriptionName.of("GCP Project", "Pubsub Subscription")
      _ <- IO.effectAsync[Throwable, Unit] { cb =>
        val sub = Subscriber
          .newBuilder(subscriptionName, new MessageReceiver() {
            override def receiveMessage(m: PubsubMessage, c: AckReplyConsumer): Unit = cb(msgQueue.offer((m, c)).map(_ => ()))
          })
          .build()
        sub.startAsync().awaitRunning() // run subscriber
      }.either
      _ <- msgQueue.take.flatMap { case (msg, consumer) =>
        Task {
          log.info(s"receive message id: {}", msg.getMessageId)
          consumer.ack()
        }.either
      }.forever
    } yield 1
  }
}
```

Above program can successfully receive the first message from pubsub, but fail at second message with following exception:
```
Exception in thread "main" Die(java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to scalaz.zio.ZIO)
Die(java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to scalaz.zio.ZIO)
scalaz.zio.FiberFailure: Fiber failed.
An unchecked error was produced.
java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to scalaz.zio.ZIO
	at scalaz.zio.internal.FiberContext.nextInstr(FiberContext.scala:412)
	at scalaz.zio.internal.FiberContext.evaluateNow(FiberContext.scala:164)
	at scalaz.zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at scalaz.zio.Runtime.$anonfun$unsafeRun$1(Runtime.scala:45)
	at scalaz.zio.Exit.getOrElse(Exit.scala:31)
	at scalaz.zio.Exit.getOrElse$(Exit.scala:29)
	at scalaz.zio.Exit$Failure.getOrElse(Exit.scala:187)
	at scalaz.zio.Runtime.unsafeRun(Runtime.scala:45)
	at scalaz.zio.Runtime.unsafeRun$(Runtime.scala:44)
	at com.momagic.dmp.footprintcollector.PubsubApiTest$.unsafeRun(PubsubApiTest.scala:9)
	at scalaz.zio.App.main(App.scala:56)
	at scalaz.zio.App.main$(App.scala:52)
	at com.momagic.dmp.footprintcollector.PubsubApiTest$.main(PubsubApiTest.scala:9)
	at com.momagic.dmp.footprintcollector.PubsubApiTest.main(PubsubApiTest.scala)
```

the `libraryDependencies` is
```
Seq(
  "com.typesafe" % "config" % "1.3.2",
  "org.typelevel" %% "cats-effect" % "1.1.0",
  "ch.qos.logback" % "logback-classic" % "1.2.3",
  "com.typesafe.scala-logging" %% "scala-logging" % "3.8.0",
  "org.scalaz" %% "scalaz-zio" % "1.0-RC4",
  "org.scalaz" %% "scalaz-zio-interop-cats" % "1.0-RC4",
  "com.google.cloud" % "google-cloud-pubsub" % "1.67.0"
)
```

Any idea what's wrong?
Thanks for any help

**Comment by cecol** [comment]
My code work with `unsafeRun` rather than `IO.effectAsync`
```
_ <- Task {
        val sub = Subscriber
          .newBuilder(subscriptionName, new MessageReceiver() {
            override def receiveMessage(m: PubsubMessage, c: AckReplyConsumer): Unit = rts.unsafeRun(msgQueue.offer((m, c)))
          })
          .build()
        sub.startAsync().awaitRunning() // run subscriber
      }.either
```
But still have no idea why `java.lang.ClassCastException`

**Comment by ghostdogpr** [comment]
So the problem is that `effectAsync` shouldn't be used for callbacks that can be called multiple times.
But we should improve user experience:
- mention it in the documentation of `effectAsync`
- better error (no `ClassCastException`)
