### ISSUE TITLE
ZIO TEST: Using .nn feature breaks reporting on failing assertions with java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by NRBPerdijk** [zio/zio#8571]
Hello. We are using Scala 3's `ExplicitNulls` (https://www.scala-lang.org/api/3.x/docs/docs/internals/explicit-nulls.html) but interface with a fair bit of Java code, resulting in the use of `.nn` to eliminate `Null` from return types.

When using this `.nn` in a test, we ran into an issue, with a Stacktrace similar to this:

```
Assertion failed:
  Exception in thread "zio-fiber-52" java.lang.StringIndexOutOfBoundsException: Range [414, 534) out of bounds for length 58
  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
  	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
  	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
  	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
  	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
  	at java.base/java.lang.String.substring(String.java:2720)
  	at zio.test.TestArrow$Span.substring(TestArrow.scala:213)
  	at zio.test.TestTrace$Node.code(TestTrace.scala:295)
  	at zio.test.FailureCase$.getPath(Result.scala:91)
  	at zio.test.FailureCase$.fromTrace(Result.scala:102)
  	at zio.test.render.TestRenderer.renderAssertionResult(TestRenderer.scala:142)
  	at zio.test.render.TestRenderer.renderAssertionResult$(TestRenderer.scala:28)
  	at zio.test.render.ConsoleRenderer$.renderAssertionResult(ConsoleRenderer.scala:235)
  	at zio.test.render.TestRenderer.renderFailure(TestRenderer.scala:212)
  	at zio.test.render.TestRenderer.$anonfun$2(TestRenderer.scala:77)
  	at scala.Option.map(Option.scala:242)
  	at zio.test.render.TestRenderer.testCaseOutput(TestRenderer.scala:79)
  	at zio.test.render.TestRenderer.testCaseOutput$(TestRenderer.scala:28)
  	at zio.test.render.ConsoleRenderer$.testCaseOutput(ConsoleRenderer.scala:235)
  	at zio.test.render.ConsoleRenderer.renderEvent(ConsoleRenderer.scala:59)
  	at zio.test.render.ConsoleRenderer.renderEvent$(ConsoleRenderer.scala:28)
  	at zio.test.render.ConsoleRenderer$.renderEvent(ConsoleRenderer.scala:235)
  	at zio.test.SummaryBuilder$.$anonfun$4(SummaryBuilder.scala:43)
  	at scala.collection.immutable.List.flatMap(List.scala:293)
  	at scala.collection.immutable.List.flatMap(List.scala:79)
  	at zio.test.SummaryBuilder$.buildSummary(SummaryBuilder.scala:43)
  	at zio.test.Summary.add(Summary.scala:34)
  	at zio.test.ExecutionEventSink$.zio$test$ExecutionEventSink$$anon$7$$_$process$$anonfun$2(ExecutionEventSink.scala:18)
  	at zio.Ref.update$$anonfun$1(Ref.scala:106)
  	at zio.Ref$Atomic$$anon$2.modify(Ref.scala:356)
  	at zio.Ref$Atomic.modify$$anonfun$2(Ref.scala:288)
  	at zio.UnsafeVersionSpecific.implicitFunctionIsFunction$$anonfun$1(UnsafeVersionSpecific.scala:27)
  	at zio.Unsafe$.unsafe(Unsafe.scala:37)
  	at zio.ZIOCompanionVersionSpecific.succeed$$anonfun$1(ZIOCompanionVersionSpecific.scala:185)
  	at zio.test.ExecutionEventSink.ExecutionEventSinkLive.$anon.process(ExecutionEventSink.scala:32)
  	at zio.test.ExecutionEventSink.ExecutionEventSinkLive.$anon.process(ExecutionEventSink.scala:35)
  Exception in thread "zio-fiber-246" java.lang.InterruptedException: Interrupted by thread "zio-fiber-246"
  	Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-246"
  Exception in thread "zio-fiber-249" java.lang.InterruptedException: Interrupted by thread "zio-fiber-249"
  	Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-249"
```

I have tried to narrow down the problem space and came to the following conclusions:
- Using `.nn` in an Assertion that yields `true` is fine.
- Not using `.nn` in an Assertion that yields `false` is fine (provided you provide `import scala.language.unsafeNulls` in scope if ExplicitNulls is enabled)
- Using `.nn` in an Assertion that yields `false` will result in the TestReport breaking with a `java.lang.StringIndexOutOfBoundsException`, completely obfuscating that the test really did fail and why it failed.

It is not so much the testing itself that fails due to `.nn`, but it is the parsing that is part of the reporting that chokes on the `.nn`.

Easy reproduction to illustrate the conclusions above and provide a start for a deeper exploration:
```
import zio.test.*

import java.util.Properties
import scala.language.unsafeNulls

object NNBugSpec extends ZIOSpecDefault:
  override def spec: Spec[Any, Throwable] =
    suite("NNBugSpec")(
      test("will work just fine, because a true Assertion on a .nn Succeeds") {
        val someProperties = new Properties()
        someProperties.setProperty("someKey", "someValue")
        assertTrue(someProperties.getProperty("someKey").nn == "someValue")
      },
      test("will fail just fine, because a false Assertion Fails") {
        val someProperties = new Properties()
        someProperties.setProperty("someKey", "someValue")
        assertTrue(someProperties.getProperty("someKey") == "notSomeValue")
      },
      test("will explode with java.lang.StringIndexOutOfBoundsException because a false Assertion on a .nn fails to parse properly") {
        val someProperties = new Properties()
        someProperties.setProperty("someKey", "someValue")
        assertTrue(someProperties.getProperty("someKey").nn == "notSomeValue")
      }
    )
end NNBugSpec
```

Work around for anyone also running into this issue:
Use `import scala.language.unsafeNulls` in your test classes (or find another way to exclude ExplicitNulls from your tests), so you don't need to use `.nn`, which prevents the breakage.

**Comment by swoogles** [comment]
I don't think this is specific to `.nn`
I ran into a situation a few days ago where a macro being in the assertion broke with a similar out of bounds error. 

A workaround was moving the expression out and sticking it in a `val` that could be referenced in the assertion.

Definitely still buggy behavior, but I'm pretty sure it applies to any inline/macro code that's being called within the assertion parameters.

The source code gets rewritten, which screws up the positions used in the failure reporting.

**Comment by NRBPerdijk** [comment]
That sounds like a reasonable explanation to me. 

Either failure reporting will need to be more robust when it comes to macros/extensions, or it should be more informative when it does choke on a macro/extension, to make the user try to exclude it as a factor...

**Comment by pragmaxim** [comment]
Agree with @swoogles : 
This fails : 
```
assertTrue(Service.insert(foo).provide(tempDirLayer >+> openLayer).exit == Exit.fail(UserError("my error msg"))
```
However this works: 
```
val result = Service.insert(foo).provide(tempDirLayer >+> openLayer)
assertTrue(result.exit == Exit.fail(UserError("my error msg")))
```
