### ISSUE TITLE
Missing stacktraces from right-side effect of `.flatMap`

### ISSUE THREAD

**Issue by kluen** [zio/zio#8747]
When watching @adamw's recent talk where he compares the usability of direct-style approaches to plain ZIO, I was a bit surprised to see that he argued that ZIO's stacktraces are only "basic". In particular, I was surprised about ZIO's behaviour in [this example](https://youtu.be/qR_Od7qbacs?t=1656).

I experimented a bit to understand the behaviour better and found that the stacktrace only contains the "frames" of the left-hand side of a `flatMap`. Here is an example to show the issue:

```scala
//> using scala 3.4
//> using dep dev.zio::zio:2.0.22

import zio.*

object PrintsStacktrace extends ZIOAppDefault:
  def run = a
  def a = b.flatMap(_ => ZIO.unit)
  def b = c.flatMap(_ => ZIO.unit)
  def c = ZIO.fail("The failure")
```

This prints:
```
timestamp=2024-04-15T09:50:00.275792Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.String: The failure
	at <empty>.PrintsStacktrace.c(PrintsStacktrace.scala:10)
	at <empty>.PrintsStacktrace.b(PrintsStacktrace.scala:9)
	at <empty>.PrintsStacktrace.a(PrintsStacktrace.scala:8)"
```
which includes the helpful info on where the effects where constructed.

Here is the example where we do not get helpful output:
```scala
//> using scala 3.4
//> using dep dev.zio::zio:2.0.22

import zio.*

object NoStacktrace extends ZIOAppDefault:
  def run = a
  def a = ZIO.unit.flatMap(_ => b)
  def b = ZIO.unit.flatMap(_ => c)
  def c = ZIO.fail("The failure")
```
which prints
```
timestamp=2024-04-15T09:51:59.317835Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.String: The failure
	at <empty>.NoStacktrace.c(NoStacktrace.scala:10)"
```

I am not sure if this behaviour is intentional, but I agree that this is not ideal from a usability standpoint, because we are missing valuable information to locate the failed effect.

**Comment by jdegoes** [comment]
/bounty $100

I would expect to see `a` and `b` in the stack trace of `c`.

**Comment by kyri-petrou** [comment]
@jdegoes just want to add a requirement to this ticket if possible?

Fixing this can negatively impact performance of the runloop depending on the implementation. I'm actually not sure if it's even possible to fix it without impacting performance to some degree.

I thin any attempted solution should either :
1. Provide before/after benchmark results of the `NarrowFlatMapBenchmark` and `BroadFlatMapBenchmark` suites (at the very least) showing that the runloop performance wasn't affected, or
2. Perhaps create a runtime flag (disabled by default?) to enable detailed stack traces

**Comment by dheerajsingh89** [comment]
/attempt #8747

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/itsdheerajdp) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @itsdheerajdp | 4 bounties from 2 projects | <div align="center">HTML, JavaScript, <br />TypeScript & more</div> | <div align="center">﹟9153</div> | [Cancel attempt](https://console.algora.io/api/bounties/clvy4k8zc000al709x8z8s9pe/cancel-attempt) |

**Comment by IsxImattI** [comment]
/attempt #8747

**Plan to fix #8747:**

1. Modify `flatMap` in `ZIO.scala` to ensure that the right-hand side function (`f(a)`) gets properly traced by using `.traced`.
2. Ensure this does not affect left-hand stack trace behavior.
3. Add a test case in `StackTraceSpec.scala` to confirm that stack traces include both left and right frames of a `flatMap` chain.
4. Run and compare `NarrowFlatMapBenchmark` and `BroadFlatMapBenchmark` results before and after the change to confirm no significant performance regression.
5. If performance impact is noticeable, introduce an opt-in runtime flag to enable detailed tracing.

**Comment by kartikbhardwaj1111** [comment]
Attempted a fix but discovered this requires architectural changes to 
ZIO's tracing system. The problem: ZIO's single `lastTrace` field 
cannot preserve both flatMap call site AND RHS effect context. 

Proper fix needs: trace stack instead of single field, updates at 
effect entry (not continuation resolution).

Requesting guidance from @jdegoes @adamgfraser on proper approach.

**Comment by kluen** [comment]
@hearnadam Hi, could you please give some insight into why this was closed? Is it not viable?
