### ISSUE TITLE
Unable to run JCStress tests

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio#8912]
```
sbt:zio> coreTestsJVM/Jcstress/run
[info] Generating sources and test list...
error: Could not find class file for 'zio.RuntimeConfigSpec'.
1 error
[error] java.lang.RuntimeException: Nonzero exit value: 1
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:138)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:108)
[error] 	at pl.project13.sbt.jcstress.JCStressPlugin$.$anonfun$projectSettings$6(JCStressPlugin.scala:81)
[error] 	at pl.project13.sbt.jcstress.JCStressPlugin$.$anonfun$projectSettings$6$adapted(JCStressPlugin.scala:32)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

The plugin expects all source files to match the class name, `/zio/core-tests/jvm/src/test/scala/zio/RuntimeConfigSpec.scala` does not.

**Comment by ajaychandran** [comment]
Alternatively, all JCStress tests should be moved to their own sub-project (like `benchmarks` is for JMH tests).
