### ISSUE TITLE
ZPipeline.fromFunction combined with provideEnvironment leads to an internal assert in ZEnvironment

### ISSUE THREAD

**Issue by eyalfa** [zio/zio#8958]
I've seen this in one of our test suites after upgrading from 2.0.21 to 2.1.2 (happened in 2.1.3 as well), 
had to work a bit but came up with this minimal reproduction (haven't checked if it passes in 2.0.21):

```
 case class Resource(idx : Int)

  val src: ZStream[Resource, Nothing, Int] = ZStream
    .range(0, 100, 10)
    .mapZIO{a =>
      ZIO.serviceWith[Resource]{resource =>
        a - resource.idx
      }
    }

  val pl0: ZPipeline[Any, Nothing, Int, (Int, Scope)] = ZPipeline.fromFunction{ strm : ZStream[Any, Nothing, Int] =>
    ZStream
      .unwrapScoped[Any]{
        ZIO.scopeWith{scope =>
          ZIO.succeed {
            ZStream
              .serviceWithStream[Scope] { scope2 =>
                strm.map(_ -> scope2)
              }
              .provideEnvironment(ZEnvironment(scope))
          }
        }
      }
  }

override def run: ZIO[Any with ZIOAppArgs with Scope, IOException, Unit] = {
    val strm: ZStream[Resource, Nothing, (Int, Scope)] = src >>> pl0
    val z00: ZIO[Resource, IOException, Unit] = strm.runCollect
      .flatMap(zio.Console.printLine(_))

    z00.provideLayer(ZLayer.succeed(Resource(12)))
  }
```

this fails with:

```
timestamp=2024-06-20T12:06:16.659254Z level=ERROR thread=#zio-fiber-384148559 message="" cause="Exception in thread "zio-fiber-1370900562" java.lang.Error: Defect in zio.ZEnvironment: Could not find Experiments::Resource inside ZEnvironment(Scope -> zio.Scope$$anon$2@69d8c6e1)
	at zio.ZEnvironment$$anon$1.get(ZEnvironment.scala:235)
	at zio.ZIO$ServiceWithZIOPartiallyApplied$.$anonfun$apply$34(ZIO.scala:5436)
	at com.datorama.pluto.exec.arrow.zio_.ignore.Experiments.src(Experiments.scala:16)
	at com.datorama.pluto.exec.arrow.zio_.ignore.Experiments.src(Experiments.scala:15)
	at com.datorama.pluto.exec.arrow.zio_.ignore.Experiments.run.z00(Experiments.scala:59)"
```

when replacing `pl0` with a 'classic' pipeline the program succeeds (no idea why).

**Comment by eyalfa** [comment]
just confirmed, this worked in 2.0.21

**Comment by eyalfa** [comment]
@jdegoes I suspect the issue is resulting from some kind of inversion of control,
when the `fromFunction` block does `strm.map(..).provideEnvironment(..)` it's unaware of any potential env deps of the tp-be-injected upstream, however when the stream is executed by the `ChannelExecutor` it injects an actual stream instead of `strm`. This actual stream does have env requirements which are delegates through the entire composed stream's env requirements, specifically its associated `providedEnv` is set to null but it gets overridden by the `pipeTo` combinator (introduced by ZChannel.mapOut, introduced by ZStream.map) effectively resulting with any effect executed by upstream to be given the wrong environment.

I think we can somehow protect upstream's env when injecting it into `fromFunction`/`DeferedUpstream`, I'll investigate this direction

**Comment by eyalfa** [comment]
/attempt #8958
when executing a DeferedUpstream (ZPipeline.fromFunction) force the correct environment on the composed upstream

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxrlii3i0013mg09vnc3r4qz/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by eyalfa** [comment]
@jdegoes I think this can/should be closed as fixed, right?
