### ISSUE TITLE
Concatenating a Chunk[Int] with Chunk[Long] results in a ClassCastException.

### ISSUE THREAD

**Issue by wwbakker** [zio/zio#9023]
Current behavior:
```
scala> Chunk.single(1) ++ Chunk.single(1L)
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
[...]
```

Expected behavior:
```
scala> Chunk.single(1) ++ Chunk.single(1L)
val res1: Chunk[Int | Long] = Chunk(1, 1)
```

------------
Full details below:

Scala 3:

```
scala-cli repl --dep dev.zio::zio:2.1.6 
Downloading 2 dependencies
Welcome to Scala 3.4.1 (21.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> import zio.Chunk

scala> Chunk.single(1) ++ Chunk.single(1L)
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
  at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:75)
  at zio.Chunk$Singleton.toArray(Chunk.scala:1822)
  at zio.Chunk$Concat.toArray(Chunk.scala:1801)
  at zio.Chunk.toArray(Chunk.scala:1017)
  at zio.Chunk.toArray(Chunk.scala:888)
  at zio.Chunk.toArrayOption(Chunk.scala:1107)
  at zio.Chunk.toString(Chunk.scala:914)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:252)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:263)
  at scala.runtime.ScalaRunTime.stringOf(ScalaRunTime.scala)
  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  at dotty.tools.repl.Rendering.stringOfMaybeTruncated$1(Rendering.scala:65)
  at dotty.tools.repl.Rendering.classLoader$$anonfun$1(Rendering.scala:73)
  at dotty.tools.repl.Rendering.classLoader$$anonfun$adapted$1(Rendering.scala:81)
  at dotty.tools.repl.Rendering.replStringOf(Rendering.scala:98)
  at dotty.tools.repl.Rendering.$anonfun$5(Rendering.scala:111)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.Rendering.valueOf(Rendering.scala:111)
  at dotty.tools.repl.Rendering.renderVal(Rendering.scala:152)
  at dotty.tools.repl.ReplDriver.$anonfun$7(ReplDriver.scala:390)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:396)
  at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:428)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:434)
  at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:330)
  at scala.util.Either.fold(Either.scala:189)
  at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:348)
  at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:271)
  at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:170)
  at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:173)
  at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:212)
  at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:186)
  at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
  at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:186)
  at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:173)
  at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:135)
  at dotty.tools.repl.Main$.main(Main.scala:7)
  at dotty.tools.repl.Main.main(Main.scala)

scala> Chunk.single("str") ++ Chunk.single(1L)
val res1: zio.Chunk[String | Long] = Chunk(str,1)

scala> Chunk.single("str") ++ Chunk.single(1)
val res2: zio.Chunk[String | Int] = Chunk(str,1)

scala> List(1) ++ List(1L)
val res3: List[Int | Long] = List(1, 1)
```

Scala 2

```
scala-cli repl --scala-version 2.13.14 --dep dev.zio::zio:2.1.6
Downloading 2 dependencies
Welcome to Scala 2.13.14 (OpenJDK 64-Bit Server VM, Java 21.0.2).
Type in expressions for evaluation. Or try :help.

scala> import zio.Chunk
import zio.Chunk

scala> Chunk.single(1) ++ Chunk.single(1L)
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
  at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:75)
  at zio.Chunk$Singleton.toArray(Chunk.scala:1822)
  at zio.Chunk$Concat.toArray(Chunk.scala:1801)
  at zio.Chunk.toArray(Chunk.scala:1017)
  at zio.Chunk.toArray(Chunk.scala:888)
  at zio.Chunk.toArrayOption(Chunk.scala:1107)
  at zio.Chunk.toString(Chunk.scala:914)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:252)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:263)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:271)
  at .lzycompute(<synthetic>:8)
  ... 26 elided

scala> Chunk.single("asd") ++ Chunk.single(1L)
val res1: zio.Chunk[Any] = Chunk(asd,1)

scala> List(1) ++ List(1L)
val res2: List[AnyVal] = List(1, 1)

```

**Comment by 987Nabil** [comment]
That's is probably due to the fact, that int and long have specialized chunk implementation. These can't be used for union types I'd expect. It should result then probably in a generic chunk. That might mean that all values will be boxed? 
Even though this should work, you should consider if this is a good solution for youm

**Comment by wwbakker** [comment]
> That's is probably due to the fact, that int and long have specialized chunk implementation

Makes sense.

>It should result then probably in a generic chunk. That might mean that all values will be boxed? Even though this should work, you should consider if this is a good solution for youm

Depends on your use case, of course. Though personally I think the throwing of runtime errors due to implementation details for something as generic as Chunk[A] seems not good to me.

Almost all of the projects I have done until now, I have prefered stability over performance. When you use software engineering best-practices the software you write is often plenty fast enough. Stability and the lack of footguns however is the biggest reason I like the type safety, compiler-time checking of scala and the zio libraries.

I'm not suggesting to throw away the fast int/long chunk implementation. Perhaps there is a way to solve this, which only affects the Chunk operations that now throw a runtime error?
If not, maybe there is a way to warn the developer at compile-time?



Maybe as an addon, my use-case is that I use zio-schema to flatten a case class with sub-classes into a list/chunk of values.

This is to export them to a CSV file, as well as excel files. You could think, why not convert them to strings beforehand? Well, for excel, it's better to keep the original datatype (BigDecimal, LocalDate etc) because otherwise all fields in the sheet are considered as text.
Of course there are workarounds, but just wanted to mention a use-case that I would consider valid.

**Comment by 987Nabil** [comment]
I agree. It is a bug. I just say the cause of the bug is is probably this optimization. Also, as long as you are aware of the trade offs, there is nothing wrong with what you are doing. As I wrote before, you should consider alternatives, but your decision might as well be that you don't need the optimized version 🙂

**Comment by jdegoes** [comment]
/bounty $125 for fixing the class cast exception and adding a test case to prevent regression. However, the returned type will NOT be `Int | Long`. The array will be an object array and the ints and longs will be boxed.
