### ISSUE TITLE
FiberFailure doesn't fill its stacktrace

### ISSUE THREAD

**Issue by tnielens** [zio/zio#9025]
The following scala `App` throws. The printed stacktrace starts at the `subcall()` method. I expected it to capture the full trace including `cal()` and `Test.main()`. I'm integrating zio gradually in my code base and am using `unsafeRunSync` here and there. Important parts of stacktraces are missing. I wonder if this is on purpose or if it's an oversight.

```scala
import zio.{Runtime, Unsafe, ZIO}

object Test extends App {
  def call(): Unit = subcall()
  def subcall(): Unit =
    Unsafe.unsafe { implicit unsafe =>
      Runtime.default.unsafe.run(subcall2()).getOrThrowFiberFailure()
    }
  def subcall2() = ZIO.fail("boom")
  call()
}
```
```
Exception in thread "main" Exception in thread "zio-fiber-1239886032" java.lang.String: boom
	at <empty>.Test.subcall2(Test.scala:9)
	at <empty>.Test.subcall(Test.scala:7)
```

**Comment by tnielens** [comment]
Relates to #1218.

**Comment by jdegoes** [comment]
/bounty $350 to lazily(?) reconstruct the proper stack trace in the fiber failure, potentially during `getOrThrowFiberFailure` if that's the only way to have a fast happy path

**Comment by melmathari** [comment]
/attempt #9025

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz89gix6000fmh09itnopu63/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
