### ISSUE TITLE
Unable to upgrade to 2.1 due to compatibility issue with Java 8

### ISSUE THREAD

**Issue by germaniums** [zio/zio#9176]
Hi, my project is Java 8, Scala 2.12.17. See this error at runtime when running tests starting with 2.1.0 (not seen in 2.0.22):

```
[error] java.lang.UnsupportedClassVersionError: zio/internal/MutableQueueFieldsPadding has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at zio.internal.PartitionedLinkedQueue.<init>(PartitionedLinkedQueue.scala:26)
[error] 	at zio.internal.ZScheduler.<init>(ZScheduler.scala:37)
[error] 	at zio.internal.DefaultExecutors.makeDefault(DefaultExecutors.scala:29)
[error] 	at zio.RuntimePlatformSpecific.$init$(RuntimePlatformSpecific.scala:26)
[error] 	at zio.Runtime$.<init>(Runtime.scala:213)
[error] 	at zio.Runtime$.<clinit>(Runtime.scala)
[error] 	...
[error] 	...
[error] 	at zio.Unsafe$.unsafe(Unsafe.scala:37)
[error] 	...
[error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error] 	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1239)
[error] 	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error] 	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error] 	at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1880)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1237)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1249)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1249)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1231)
[error] 	at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1880)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1308)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1308)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1307)
[error] 	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1880)
[error] 	at org.scalatest.Suite.run(Suite.scala:1114)
[error] 	at org.scalatest.Suite.run$(Suite.scala:1096)
[error] 	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1880)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1353)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1353)
[error] 	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1351)
[error] 	at org.scalatest.wordspec.AnyWordSpec.run(AnyWordSpec.scala:1880)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:147)
[error] 	at sbt.TestRunner.run(TestFramework.scala:162)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:330)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:290)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:330)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:330)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:342)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:435)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
```

**Comment by 987Nabil** [comment]
We removed Java 8 from the build process of the zio eco system. Java 8 is out of support. We currently build with 17 and 21.  I don't say it is impossible to build with 8, but we won't build and upload to maven with 8. You can try to build it yourself, if you really need a Java 8 version. But I would highly recommend to update to Java 17+. If your company has no special support contract for 8, you also have no security updates. That is a liability

**Comment by kyri-petrou** [comment]
To add to @987Nabil message, we also support Java 11. We should probably document this better though for clarity and use the `-release:11` flag to enforce it

**Comment by 987Nabil** [comment]
@kyri-petrou maybe we should question the 11 build. Updating to 17+ when using 11 is usually easy. And 11 is out of support already since September 2023

**Comment by kyri-petrou** [comment]
@987Nabil the EOL for JDK11 is January 2032. Note that I'm not implying should be releasing for JDK11 until then, but as long it doesn't become prohibitive for developing new features I think we should be targeting the earliest JDK version we can. Otherwise a lot of libraries that also depend on ZIO (either `zio-*` or third-party like Caliban, Tapir, STTP, etc) will also need to drop support for it.

This is just a speculation, but since JDK17 doesn't really offer much more than JDK11 (at least for Scala), I have a feeling that the next time we'll be increasing the minimum supported JDK version will likely be to JDK21 which supports virtual threads

**Comment by 987Nabil** [comment]
@kyri-petrou 2032 is the extended aka payed support. And idk how to make a difference between extended and sustaining, wich is payed without time limit.

**Comment by germaniums** [comment]
Thank you both for your input.

Java 8 LTS also has [extended support until 2030](https://www.oracle.com/java/technologies/java-se-support-roadmap.html). In addition, there are a few OpenJDK Java 8 repositories maintained, receiving security updates, and used in production. For example [Amazon Corretto](https://github.com/corretto/corretto-8).

While I agree that upgrading would be ideal, I am not able to do so at my company. And as I work on one of the few teams using ZIO, I'm unlikely to move the needle. This means that we will eventually need to drop ZIO altogether. In the spirit of your comment about targeting the earliest JDK version you can @kyri-petrou, could I ask you to reconsider dropping support for Java 8 users in positions like ours?

**Comment by 987Nabil** [comment]
My very personal opinion: We removed Java 8 support one year ago. And afaik, this is the first issue with that. Extended support means oracle gets payed. Amazon Cornetto gets payed by amazon. Probably because of their own tech dept. And while I love ppl using zio, I don't see why we should pay the tech dept of your company. There are still versions of zio 2 that support java 8. You could publish your own artifact to some company gh repo or artifactory or something like that, if it still builds with java 8.

Note that a quick check revealed: akka build with 11 play with 17 and even spark (known for being slow with updating) uses 17. Spring boot 3, also Java 17.

So I don't think we are an outlier.

**Comment by kyri-petrou** [comment]
I agree with @987Nabil . Even if we added back support for Java 8, you will eventually run into the same issue with a different library (either Java or Scala).

**Comment by guizmaii** [comment]
I would personally vote against putting back support of Java8. 
@germaniums I'm sorry but you'll have to update your Java version.

Closing
