### ISSUE TITLE
ZIO test throws when trying to print error messages (`2.1.7`->`2.1.9`)

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [zio/zio#9209]
```scala
  private def izumiTagTest[A: Tag](exp: TypeTag.TypeRef): TestSpec =
    test(exp.polyShow(_.prefixAll)) {
      assertTrue(TypeTag.usingTag[A].tag == exp)
    }
```

```
      - TypeTagSpec / from: / izumiTag / oxygen.core.TypeTagSpec.types.Stage1.Stage2[java.lang.String]
        Exception in thread "zio-fiber-" java.lang.StringIndexOutOfBoundsException: begin 11697, end 11722, length 30
                at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
                at java.base/java.lang.String.substring(String.java:1874)
                at zio.test.TestArrow$Span.substring(TestArrow.scala:291)
                at zio.test.TestTrace$Node.code(TestTrace.scala:295)
                at zio.test.FailureCase$.getPath(Result.scala:91)
                at zio.test.FailureCase$.getPath(Result.scala:93)
                at zio.test.FailureCase$.fromTrace(Result.scala:102)
                at zio.test.render.TestRenderer.renderAssertionResult(TestRenderer.scala:143)
                at zio.test.render.TestRenderer.renderAssertionResult$(TestRenderer.scala:28)
                at zio.test.render.ConsoleRenderer$.renderAssertionResult(ConsoleRenderer.scala:235)
                at zio.test.render.TestRenderer.renderFailure(TestRenderer.scala:216)
                at zio.test.render.TestRenderer.$anonfun$2(TestRenderer.scala:78)
                at scala.Option.map(Option.scala:242)
                at zio.test.render.TestRenderer.testCaseOutput(TestRenderer.scala:79)
                at zio.test.render.TestRenderer.testCaseOutput$(TestRenderer.scala:28)
                at zio.test.render.ConsoleRenderer$.testCaseOutput(ConsoleRenderer.scala:235)
                at zio.test.render.ConsoleRenderer.renderEvent(ConsoleRenderer.scala:59)
                at zio.test.render.ConsoleRenderer.renderEvent$(ConsoleRenderer.scala:28)
                at zio.test.render.ConsoleRenderer$.renderEvent(ConsoleRenderer.scala:235)
                at zio.test.SummaryBuilder$.$anonfun$4(SummaryBuilder.scala:43)
                at scala.collection.immutable.List.flatMap(List.scala:293)
                at scala.collection.immutable.List.flatMap(List.scala:79)
                at zio.test.SummaryBuilder$.buildSummary(SummaryBuilder.scala:43)
                at zio.test.Summary.add(Summary.scala:34)
                at zio.test.ExecutionEventSink$.zio$test$ExecutionEventSink$$anon$2$$_$process$$anonfun$2(ExecutionEventSink.scala:18)
                at zio.Ref.update$$anonfun$1(Ref.scala:106)
                at zio.Ref$Atomic$$anon$2.modify(Ref.scala:356)
                at zio.Ref$Atomic.modify$$anonfun$2(Ref.scala:288)

```

**Comment by Kalin-Rudnicki** [comment]
seems to only happen with the `assertTrue`, `assert(_)(equalTo(_))` does not have this issue

**Comment by Saturn225** [comment]
/attempt #9209

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/SankeerthKoraboina) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Saturn225 | 2 bounties from 2 projects | <div align="center">Rust, Scala, <br />HTML</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm39216kb0026mh03uzdsawpm/cancel-attempt) |
