### ISSUE TITLE
ZSTM doesn't guarantee consistency

### ISSUE THREAD

**Issue by durban** [zio/zio#9264]
Tested with version `2.1.11`.

Repro:

```scala
package com.example

import zio._
import zio.stm._

import MyQueue.{ Elem, Node, End }

final object MyApp extends ZIOAppDefault {

  final override def run =
    this.task.repeatN(9999999)

  private def task = for {
    q1 <- MyQueue[String]
    q2 <- MyQueue[String]
    enq = (q1.enqueue("x") *> q2.enqueue("x")).commit.repeatN(8)
    deq = (q1.tryDequeue <*> q2.tryDequeue).commit.flatMap {
      case (None, None) =>
        ZIO.unit
      case (Some(v1), Some(v2)) =>
        if (v1 == v2) ZIO.unit
        else ZIO.dieMessage(s"err1: $v1 != $v2")
      case (x, y) =>
        ZIO.dieMessage(s"err2: $x != $y")  // <- this happens
    }.repeatN(8)
    _ <- ZIO.foreachParDiscard(List(enq, deq, deq)) { t => t }
  } yield ()
}

final class MyQueue[A >: Null] private (head: TRef[Node[A]], tail: TRef[Node[A]]) {

  def enqueue(a: A): USTM[Unit] = {
    for {
      end <- TRef.make[Elem[A]](End[A]())
      node = Node(a, end)
      t <- tail.get
      tn <- t.next.get
      _ <- tn match {
        case End() => t.next.set(node).flatMap { _ => tail.set(node) }
        case _ => ZSTM.dieMessage("this should never happen")
      }
    } yield ()
  }

  def tryDequeue: USTM[Option[A]] = {
    for {
      h <- head.get
      hn <- h.next.get
      r <- hn match {
        case n @ Node(a, _) => head.set(n.copy(data = null)).as(Some(a))
        case End() => ZSTM.succeed(None)
      }
    } yield r
  }
}

final object MyQueue {

  private sealed abstract class Elem[A]
  private final case class Node[A](data: A, next: TRef[Elem[A]]) extends Elem[A]
  private final case class End[A]() extends Elem[A]

  def apply[A >: Null]: UIO[MyQueue[A]] = for {
    end <- TRef.makeCommit[Elem[A]](End[A]())
    sentinel = Node[A](null, end)
    head <- TRef.makeCommit[Node[A]](sentinel)
    tail <- TRef.makeCommit[Node[A]](sentinel)
  } yield new MyQueue[A](head, tail)
}
```

Output:

```
[info] running (fork) com.example.MyApp 
[info] timestamp=2024-10-29T20:36:52.924969907Z level=ERROR thread=#zio-fiber-313882444 message="" cause="Exception in thread "zio-fiber-678750573" java.lang.RuntimeException: err2: None != Some(x)
[info]  at com.example.MyApp.task.deq(MyApp.scala:24)
[info]  at com.example.MyApp.task.deq(MyApp.scala:25)
[info]  at com.example.MyApp.task(MyApp.scala:26)"
[error] Nonzero exit code returned from runner: 1
[error] (bench / Test / run) Nonzero exit code returned from runner: 1
[error] Total time: 5 s, completed Oct 29, 2024, 9:36:53 PM
```

Observations:

- We always use the 2 queues together, and do the same thing with them, in a *single* transaction.
- When we enqueue, we enqueue the same item in a single transaction into both.
- When we try to dequeue, we try to dequeue once from both (also in a single transaction).
- Thus, it should *never* happen, that we see that one of the queues is empty, while the other is not.
- However, this is exactly what happens: see the `err2: None != Some(x)` message.

**Comment by ghostdogpr** [comment]
Can you check with 2.1.7? There was a big refactor of STM in 2.1.8 so I wonder if this is a regression or if it was always like that.
